use local id from webdav
nextcloud/android pull request #10011
Opened 2022-03-23 06:22 UTC by tobiasKaminsky

Fixes: https://github.com/nextcloud/android/issues/8566
Library: https://github.com/nextcloud/android-library/pull/843

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

- [x] Tests written, or not not needed

2022-03-23 09:56 UTC, AlvaroBrey approved these changes

2022-03-23 10:25 UTC, AlvaroBrey commented
Similar trace in all failing tests (including screenshot)
```
java.lang.StringIndexOutOfBoundsException: length=3; index=8
at java.lang.String.substring(String.java:1971)
at com.owncloud.android.datamodel.OCFile.getLocalId(OCFile.java:560)
at com.owncloud.android.datamodel.FileDataStorageManager.saveFile(FileDataStorageManager.java:238)
at com.owncloud.android.datamodel.FileDataStorageManager.saveNewFile(FileDataStorageManager.java:348)
at com.owncloud.android.datamodel.FileDataStorageManagerIT.testSaveNewFile(FileDataStorageManagerIT.java:349)
```

2022-03-30 14:34 UTC, AlvaroBrey requested changes
failing tests, see previous comment

2025-01-30 20:46 UTC, joshtrichards commented
Superceded by #8643

2025-01-30 20:46 UTC, closed without merging