Tile view
nextcloud/android pull request #10079
Opened 2022-04-14 06:20 UTC by tobiasKaminsky

- [ ] Tests written, or not not needed

2022-08-04 15:12 UTC, AlvaroBrey reviewed
The approach generally looks good, but it needs a lot of polish. Current implementation does weird things with changing sizes when refreshing, crashes when scrolling down, and shows the wrong aspect ratio for some images.

2022-08-04 15:12 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/datamodel/ImageDimension.kt
> +data class ImageDimension(var width: Float = -1f, var height: Float = -1f) : Serializable
Any reason why this needs to be `Serializable`? if so, it needs a serialVersionUuid

2022-08-04 15:12 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/datamodel/OCFile.java
> +    public void setImageDimension(@NonNull ImageDimension imageDimension) {
getter is nullable but setter is non null

2022-08-04 15:12 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
> +    public static class GalleryImageGenerationTask extends AsyncTask<Object, Void, Bitmap> {
We should not be writing new `AsyncTask`s at this point, they are very deprecated and lead to too many problems. Use coroutines or an Executor instead, if possible

2022-08-23 10:23 UTC, tobiasKaminsky commented on app/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
> +        cv.put(ProviderTableMeta.FILE_METADATA_SIZE, new Gson().toJson(file.getImageDimension()));
True. But we are doing it already for other values.
Let us keep it for now, and once we have a better plan, we can move it.

2022-08-23 10:48 UTC, tobiasKaminsky commented on app/src/main/java/com/owncloud/android/datamodel/ImageDimension.kt
> +data class ImageDimension(var width: Float = -1f, var height: Float = -1f) : Serializable
Indeed not needed.

2022-08-23 10:49 UTC, tobiasKaminsky commented on app/src/main/java/com/owncloud/android/datamodel/OCFile.java
> +    public void setImageDimension(@NonNull ImageDimension imageDimension) {
Can be null.

2022-08-23 10:50 UTC, tobiasKaminsky commented on app/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
> +    public static class GalleryImageGenerationTask extends AsyncTask<Object, Void, Bitmap> {
With both I do not have real experience.
Do you have an example within our app?

2022-08-23 15:29 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
> +    public static class GalleryImageGenerationTask extends AsyncTask<Object, Void, Bitmap> {
Executors: http://github.com/nextcloud/android/blob/5daf12fd65cdf1a27a5b4f00186ead6f3ae325b3/app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java#L321-L321

Coroutines: http://github.com/nextcloud/android/blob/5daf12fd65cdf1a27a5b4f00186ead6f3ae325b3/app/src/main/java/com/owncloud/android/ui/fragment/SharedListFragment.kt#L108-L108

2022-09-28 10:20 UTC, tobiasKaminsky commented on app/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
> +    public static class GalleryImageGenerationTask extends AsyncTask<Object, Void, Bitmap> {
I tend to postpone this, until we/I resolved all bugs…

2022-10-14 12:10 UTC, AlvaroBrey requested changes

2022-10-14 12:24 UTC, AlvaroBrey commented
Also, fast scroller needs to be removed from GalleryFragment

2022-10-14 12:25 UTC, tobiasKaminsky commented on app/src/main/java/com/owncloud/android/ui/adapter/GalleryAdapter.kt
> +        }
Awesome!

2022-10-14 12:29 UTC, tobiasKaminsky commented on app/src/main/java/com/owncloud/android/utils/DisplayUtils.java
> +    public static void setGalleryImage(OCFile file,
This will still have two calls to static DisplayUtils, but it is way better.

2022-10-14 19:05 UTC, AlvaroBrey commented
Rebased and fixed after m3 merge ✨

2022-10-17 15:17 UTC, merged