Media view filter options
nextcloud/android pull request #10121
Opened 2022-04-27 15:56 UTC by surinder-tsys

Media view with filter options:
1. User can select specific media folder to see the medias inside it.
2. User can filter if he wants to see only images.
3. User can filter if he wants to see only videos.

![Media_Options](https://user-images.githubusercontent.com/89455194/165560390-4835ece8-af62-4a7d-841c-00237ae64a2d.png)

![media_image_seleted](https://user-images.githubusercontent.com/89455194/165560413-a90625b6-caf1-49ad-aaaf-9b27aeab64da.png)

![media_video_selected](https://user-images.githubusercontent.com/89455194/165560440-000558d9-d0c1-4c90-8af3-21f5bb47f5da.png)

- [ ] Tests written, or not not needed

2022-04-28 08:05 UTC, AlvaroBrey commented
Ping @jancborchardt for design review

As it stands, this UX looks like it's a 1:1 copy of the iOS application, but I can see some small issues with it:

1. The "check" mark when  something is hidden doesn't add any value in my opinion, since the icon and the text of the action already change to reflect state. It also is confusing because it looks like the option is "selected", not "active", because of the checkmark; this is not a common interaction in Android.
    * I would probably just remove the  checkmark
2. The show/hide state for images and videos is stored in appPreferences so it is global. This means that if the user sets filters, leaves the gallery and later comes back, the filters will still be applied. _But_ there will be no indication that the view is being filtered, unless the user opens the three dot menu.
    * I would make this state non-persistent, i.e. resets if you leave gallery and come back
3. I think `Select the "Media" folder` is not a great text for what it does (showing only media in specific directories), but I can't think of a clearly better alternative. To me, it makes it look like "Media" is an actual folder, and this option will change it somehow.
    * Maybe just `Select folder` is better?  

@surinder-tsys Thanks for this PR! The changes above are just for design discussion, no need to make them yet. We'll do a code review soon.

2022-05-03 10:00 UTC, surinder-tsys commented
Hi @AlvaroBrey I have updated the PR with the mentioned changes. 
Please have a look.
![default_state](https://user-images.githubusercontent.com/89455194/166435138-8dbef360-4ef7-42cf-b610-64ec1dab7711.png)

![both_selected](https://user-images.githubusercontent.com/89455194/166435153-66db1009-82bd-41a8-837b-96b11c168e95.png)

![videos_only](https://user-images.githubusercontent.com/89455194/166435163-2fbabbb9-bf77-4cab-9907-52a9c2c158c4.png)

![single_selection](https://user-images.githubusercontent.com/89455194/166435125-3a6e8c48-307b-4d53-91fc-eab297587701.png)

2022-05-04 09:11 UTC, AlvaroBrey requested changes
Thanks! Some things to fix: 

* Please format your code (`./gradlew ktlintFormat`)

* There's a bug with the toolbar subtitle; once it gets set in `GalleryFragment`, it keeps showing on the rest of views (if you change to Favorites from Media for example). To prevent this, please add a call to clear the subtitle at  `FileDisplayActivity.setLeftFragment`.

* Please take a look at the comments below for other things to fix

2022-05-04 09:11 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
> +        remoteFilePath.setFolder();
`setFolder` is only for testing purposes and you shouldn't need it. You are starting at `/`and only letting the user select folders, so it should always be a folder.

2022-05-04 09:11 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
> +        if (item.getItemId() == R.id.action_three_dot_icon) {
Combine these two `if` statements with `&&`

2022-05-04 09:11 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
> +        if (requestCode == SELECT_LOCATION_REQUEST_CODE) {
Combine these two `if` statements with `&&`

2022-05-04 09:11 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
> +    private void runGallerySearchTask() {
Use this function also on line 229 (searchAndDisplay)

2022-05-04 09:11 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
> +    private void updateSubtitle(boolean isHideVideos, boolean isHidePhotos) {
Use a state enum rather than two booleans, as already commented on other classes.

2022-05-04 09:11 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/ui/fragment/GalleryFragmentBottomSheetDialog.java
> +    private static final int MEDIA_STATE_VIDEOS_ONLY = 3;
Better to use an enum rather than constantes

2022-05-04 09:11 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/utils/theme/ThemeMenuUtils.java
> +    public void tintMenuIcon(@NonNull MenuItem item, int color) {
Nice!

2022-05-04 09:11 UTC, AlvaroBrey commented on app/src/main/res/drawable/ic_tick.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Needs license header

2022-05-04 09:11 UTC, AlvaroBrey commented on app/src/main/res/drawable/ic_video_camera.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Needs license header

2022-05-09 10:25 UTC, AlvaroBrey requested changes
Great! Just two more minor things from my part

2022-05-09 10:25 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
> +            FileActivity activity = (FileActivity) getActivity();
```suggestion
```
Unused

2022-05-09 10:25 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
> +        updateToolbarSubtitle("");
The proper way to clear the subtitle is to call `actionBar.setSubtitle(null)`, not an empty string. Additionally the comment is incomplete.

2022-05-09 11:59 UTC, AlvaroBrey approved these changes
Thank you @surinder-tsys !

@tobiasKaminsky please review

2022-06-17 08:46 UTC, tobiasKaminsky commented on app/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
> +                    mChooseBtn.setText(getResources().getString(R.string.common_select));
That's unusual to put it here.
If we want to have this, then it should also be for move/copy operation.

In general this is uncommon to have, I think.

2022-06-17 08:55 UTC, tobiasKaminsky commented on app/src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
> +    private List<OCFile> mediaObject;
This List should be in Adapter, as a Fragment should not contain any real data.
We have similar approach in OcFileListAdapter, with mFiles and mFilesAll.

But actually in this case, as all items are in storageManager.allGalleryItems, I am unsure if two lists are needed, or if it not enough to retrieve subset directly from storageManager

2022-06-17 08:56 UTC, tobiasKaminsky requested changes
Please see my comments

2022-06-17 09:51 UTC, surinder-tsys commented on app/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
> +                    mChooseBtn.setText(getResources().getString(R.string.common_select));
@tobiasKaminsky  Can you elaborate more on this? What is your expectation?

2022-06-22 09:40 UTC, tobiasKaminsky commented on app/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
> +                    mChooseBtn.setText(getResources().getString(R.string.common_select));
With uncommon I mean to have a "✔" on a button.
See https://material.io/components/buttons#behavior, this is used in only rare cases, but not for a "normal" confirm dialog.

2022-06-24 05:17 UTC, surinder-tsys commented on app/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
> +                    mChooseBtn.setText(getResources().getString(R.string.common_select));
Removed the tick icon from button

2022-06-24 05:18 UTC, surinder-tsys commented on app/src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
> +    private OCFile remoteFile = new OCFile("/");//default root path
Accessed remote file path from storage manager.

2022-06-24 05:18 UTC, surinder-tsys commented on app/src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
> +    private List<OCFile> mediaObject;
Removed the mediaObject list from GalleryFragment.

2022-07-05 06:29 UTC, tobiasKaminsky commented
@surinder-tsys this looks good now, but it seems that you did a mistake while rebasing, as there are now way too many commits?
Can you recheck this?

2022-07-05 13:55 UTC, surinder-tsys commented
> @surinder-tsys this looks good now, but it seems that you did a mistake while rebasing, as there are now way too many commits? Can you recheck this?

@tobiasKaminsky I have reduced the commits now. But still there are duplicate commits which caused due to rebasing I suppose.
I tried but couldn't find anything to get rid of them. If you have any idea please let me know.

2022-07-07 07:29 UTC, tobiasKaminsky commented
Alvaro re-based it and create a new PR here: #10484

2022-07-07 07:29 UTC, closed without merging