Migrate some FileUploader and FileDownloader APIs to User
nextcloud/android pull request #10348
Opened 2022-06-07 01:13 UTC by ezaquarii

Signed-off-by: Chris Narkiewicz <hello@ezaquarii.com>

- [x] Tests written, or not not needed

2022-06-07 02:07 UTC, ezaquarii commented
@AlvaroBrey 
`testServerChangedFileContent` timeout - probably not me.

2022-06-07 07:27 UTC, AlvaroBrey requested changes
Thanks @ezaquarii, looks good except a deleted log call. Can you restore it, or explain your rationale for deleting it?

2022-06-07 07:27 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/files/services/FileUploader.java
> -                    " does not exist anymore -> cancelling all its uploads");
Please restore this deleted log call

2022-06-07 20:49 UTC, ezaquarii commented on app/src/main/java/com/owncloud/android/files/services/FileUploader.java
> -                    " does not exist anymore -> cancelling all its uploads");
Done

2022-06-08 07:38 UTC, merged

2022-06-08 07:38 UTC, AlvaroBrey commented
Thanks @ezaquarii !