Setting token permissions to read-only follows the principle of least privilege.
nextcloud/android pull request #10368
Opened 2022-06-10 06:04 UTC by tobiasKaminsky

It might be that we need to re-adjust a workflow that also needs to push…

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

- [ ] Tests written, or not not needed

2022-06-10 08:53 UTC, AlvaroBrey requested changes

2022-06-10 08:53 UTC, AlvaroBrey commented on .github/workflows/analysis.yml
> +permissions: read-all
This workflow needs `contents: read` and:
- `write` permission for `pull-requests` (to post comments, unless we merge #10345
- `write` permission for `contents` to push the lint bump-down commits (need to test it)<

2022-06-10 08:53 UTC, AlvaroBrey commented on .github/workflows/autoApproveDependabot.yml
> +permissions: read-all
This workflow likely needs `pull-requests: write` to post the review

2022-06-10 08:53 UTC, AlvaroBrey commented on .github/workflows/qa.yml
> +permissions: read-all
this workflow will need `contents: read` and `pull-requests: write` to post the comment

2022-06-10 08:53 UTC, AlvaroBrey commented on .github/workflows/command-rebase.yml
> +permissions: read-all
This workflow will need `contents: write` and `pull-requests: write`  permissions. Additionally it might not be a good idea to update this workflow, as it gets auto-updated from [organization templates](https://github.com/nextcloud/.github/)

2022-06-10 08:53 UTC, AlvaroBrey commented on .github/workflows/screenShotTest.yml
> +permissions: read-all
this workflow will need `contents: read` and `pull-requests: write` to post the comment

2022-06-10 08:53 UTC, AlvaroBrey commented on .github/workflows/stale.yml
> +permissions: read-all
this workflow will  need `pull-requests: write` to post the comment and labels

2022-06-10 08:53 UTC, AlvaroBrey commented on .github/workflows/unit-tests.yml
> +permissions: read-all
this workflow will need `contents: read` and `pull-requests: write` to post the comment

2022-06-13 12:21 UTC, tobiasKaminsky commented on .github/workflows/command-rebase.yml
> +permissions: read-all
Let us check if this works, and then adjust org template.

2022-06-13 12:24 UTC, tobiasKaminsky commented
Some checks were changed already on master.

2022-06-23 10:23 UTC, AlvaroBrey approved these changes

2022-06-23 10:23 UTC, merged