File export / download
nextcloud/android pull request #10443
Opened 2022-06-27 13:00 UTC by tobiasKaminsky

- [x] Tests written, or not not needed

2022-06-27 15:19 UTC, AlvaroBrey requested changes
Generally looks fine but needs some polish, especially `FileExportUtils`.

Additionally this PR should be squashed or rebased when merged, as many WIP commits are in this branch

2022-06-27 15:19 UTC, AlvaroBrey commented on app/src/main/java/com/nextcloud/client/jobs/FilesDownloadWork.kt
> +class FilesDownloadWork(
Should it be `FilesExportWork` instead?

2022-06-27 15:19 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/utils/FileExportUtils.kt
> +        contentResolver: ContentResolver,
If possible I'd prefer to see the `contentResolver` injected in `FileExportUtils` via constructor, and then `FileExportUtils` injected wherever needed, not sure how hard that is.

2022-06-27 15:19 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/utils/FileExportUtils.kt
> +                    throw RuntimeException("ocFile and file both may not be null")
Throw an `IllegalStateException` instead, for example.

2022-06-27 15:19 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/utils/FileExportUtils.kt
> +                e.printStackTrace()
Use `Log_OC`, do not print stack trace. Same for other occurrences in this file

2022-06-27 15:19 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/utils/FileExportUtils.kt
> +                }
Why the two different ways of copying an `InputStream` to an `OutputStream` in the two if branches? Should be the same (`IOUtils.copy` for both, for example)

2022-06-27 15:19 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/utils/FileExportUtils.kt
> +                inputStream?.close()
Already using `use`, which will autoclose the resources; no need for this `finally`. 

Additionally, the streams in the other if branch are never closed. Same `use` or try-with-resources should be  in place.

2022-06-27 15:19 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/utils/FileExportUtils.kt
> +        }
```suggestion
        val extPos = name.lastIndexOf('.')
        val suffix = " ($count)"

        return if (extPos >= 0) {
            val extension = name.substring(extPos + 1)
            val nameWithoutExtension = name.substring(0, extPos)
            "$nameWithoutExtension$suffix.$extension"
        } else {
            name + suffix
        }
```
Can be simplified and made immutable by merging the `if`s

2022-06-27 15:19 UTC, AlvaroBrey commented on app/src/main/res/values/strings.xml
> +    <string name="export_start">%1s will be downloaded. See notification for details.</string>
Mixed language: using "export" and "download" to mean the same thing. I would use "export" to not confuse users because of the current Download function, which just downloads to internal storage.

2022-06-28 05:27 UTC, tobiasKaminsky commented on app/src/main/java/com/owncloud/android/utils/FileExportUtils.kt
> +                }
Android 7 does not work with IOUtils, so I had to do it in a different way.
Basically like in UploadFileOperation -> copy()

2022-06-28 05:32 UTC, tobiasKaminsky commented on app/src/main/res/values/strings.xml
> +    <string name="export_start">%1s will be downloaded. See notification for details.</string>
in iOS Files it is called:
download -> set as available offline (which fits also in our case)
export -> save to photo gallery (for images, as iOS cannot export other file types)

With this in mind, I mixed it up… :S 

For now, to not confuse users, we could use
download -> set as available offline
export -> export

Then I can also rename all new functions / classes to "export"?

2022-06-28 07:23 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/utils/FileExportUtils.kt
> +                }
Then change the copy in the other branch (it uses `IOUtils`)

2022-06-28 07:27 UTC, AlvaroBrey commented on app/src/main/res/values/strings.xml
> +    <string name="export_start">%1s will be downloaded. See notification for details.</string>
I would keep "Download" as it is right now, and just rename export stuff to "Export"; just be careful that no strings related to exporting files say "download".

I think it might make sense to change "download" to "set as available offline" in the future, but that's a different PR.

2022-06-28 12:21 UTC, tobiasKaminsky commented
> Additionally this PR should be squashed or rebased when merged, as many WIP commits are in this branch

Of course, I do this at the end, or sometimes before creating PR, but I will make sure to not commit it in this state.

2022-06-30 04:59 UTC, tobiasKaminsky commented on app/src/main/java/com/owncloud/android/utils/FileExportUtils.kt
> +        contentResolver: ContentResolver,
I failed doing it 😇
We can do it later, I think.

2022-06-30 12:22 UTC, AlvaroBrey commented on app/src/main/java/com/nextcloud/client/jobs/BackgroundJobFactory.kt
> +    private fun createFilesDownloadWork(
should be `createFilesExportWork`

2022-07-01 08:58 UTC, tobiasKaminsky commented on app/src/main/java/com/nextcloud/client/jobs/FilesExportWork.kt
> +        val fileIDs = inputData.getLongArray(FILES_TO_DOWNLOAD) ?: LongArray(0)
I cannot really imagine how this can happen, but logging is better than nothing.

2022-07-04 15:18 UTC, AlvaroBrey commented
/rebase

2022-07-06 08:21 UTC, AlvaroBrey requested changes

2022-07-06 08:21 UTC, AlvaroBrey commented on app/src/main/java/com/nextcloud/client/jobs/FilesExportWork.kt
> +        )
This way of doing plurals doesn't work for many languages such as Spanish. The whole string (`R.string.export_successful`) needs to be pluralized, as the verb tense changes as well (`exportado` for 1,  `exportados` for more than 1).

2022-07-06 13:02 UTC, AlvaroBrey approved these changes

2022-07-07 08:02 UTC, merged