Dashboard
nextcloud/android pull request #10719
Opened 2022-09-07 14:06 UTC by tobiasKaminsky

Fix https://github.com/nextcloud/android/issues/10629

- [ ] Tests written, or not not needed

2022-09-19 10:12 UTC, nickvergessen commented
> if returned entry size is 14, then show "load more" button, else not

So should the dashboards register the button or not?
If the dashboards do, you shouldn't be able to identify/distinguish it from any other button, so I think the registration condition should be checked by the app rather than the clients?

2022-09-19 11:10 UTC, nickvergessen commented
Problem | Question
---|---
![Screenshot_2022-09-19-13-07-49-434_com nextcloud android qa](https://user-images.githubusercontent.com/213943/191004556-2b2b1c6d-3453-44cf-841d-e9a7f72f0963.jpg) | The icons you retrieve from the server are supposed to always be black I guess. So you can invert them for bright mode? But I see user status is always returning a white icon, so I guess it is broken there in bright mode?

2022-09-19 12:55 UTC, nickvergessen commented
More issues:

1. The widgets icon is rounded (cutting of the tick in the bottom right making Talk look like a circle)
2. The widget item icons are not rounded (avatars should be round)
3. If the widget item is a "small" it should be used in a suitable size (the icons are 16px iirc on the server)

![Screenshot_2022-09-19-14-52-58-881_com miui home](https://user-images.githubusercontent.com/213943/191022139-69e1ff5f-958b-4d0f-87f9-f4368103c994.jpg)

2022-09-19 12:57 UTC, nickvergessen commented
Okay the top bar icon is fixed by clicking the refresh button, but the avatars stay "square" and small

2022-09-29 16:21 UTC, AlvaroBrey commented on app/src/main/java/com/nextcloud/client/widget/DashboardWidgetProvider.kt
> +        @SuppressLint("UnspecifiedImmutableFlag")
Instead of suppressing the lint, set the correct mutability in the PendingIntents. I assume they can all just be `PendingIntent.FLAG_IMMUTABLE | PendingIntent.FLAG_UPDATE_CURRENT`

2022-09-29 16:21 UTC, AlvaroBrey commented on app/src/main/java/com/nextcloud/client/widget/DashboardWidgetProvider.kt
> +        internal fun updateAppWidget(
As outlined in another comment, I think this method does not belong here as a static function, and instead belongs in a separate class with a lot of these parameters already injected into it.

2022-09-29 16:21 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/ui/adapter/DashboardWidgetListAdapter.kt
> +    val themeDrawableUtils: ThemeDrawableUtils,
This will have to be changed when M3 work is merged, but we'll talk about that when that happens

2022-10-10 08:34 UTC, tobiasKaminsky commented on app/src/main/res/values/strings.xml
> +    <string name="app_widget_description">Shows all widgets from dashboard</string>
True

2022-10-10 08:35 UTC, tobiasKaminsky commented on app/src/main/res/values/strings.xml
> +    <string name="widgets_not_available"><![CDATA[Widgets are only available on >= NC25]]></string>
No idea. This was done by AS. I'll remove it.

2022-10-10 08:58 UTC, tobiasKaminsky commented on app/src/androidTest/java/com/nextcloud/ui/BitmapIT.kt
> +    val testActivityRule = IntentsTestRule(TestActivity::class.java, true, false)
I noted it down to do it in one step for files and library, so that then there is no old code left, which I could accidentally copy.

2022-10-10 09:01 UTC, tobiasKaminsky commented on app/src/main/java/com/owncloud/android/ui/adapter/DashboardWidgetListAdapter.kt
> +    val themeDrawableUtils: ThemeDrawableUtils,
Correct, let us merge this and then deal with M3 afterwards.
Or the other way around :)

2022-10-13 09:17 UTC, AlvaroBrey requested changes
Some suggestions. Also some conversations from the previous review are unresolved still.

2022-10-13 09:17 UTC, AlvaroBrey commented on app/src/main/java/com/nextcloud/client/network/ClientFactoryImpl.java
> +public class ClientFactoryImpl implements ClientFactory {
```suggestion
class ClientFactoryImpl implements ClientFactory {
```
Not needed anymore since injection works on the WidgetProvider. Same for the constructor, but GH won't let me add a suggestion there.

2022-10-13 09:17 UTC, AlvaroBrey commented on app/src/main/java/com/nextcloud/client/widget/DashboardWidgetProvider.kt
> +    lateinit var widgetUpdater: DashboardWidgetUpdater
```suggestion
import android.appwidget.AppWidgetManager
import android.appwidget.AppWidgetProvider
import android.content.Context
import android.content.Intent
import com.nextcloud.client.preferences.AppPreferences
import dagger.android.AndroidInjection
import javax.inject.Inject

/**
 * Manages widgets
 */
class DashboardWidgetProvider : AppWidgetProvider() {
    @Inject
    lateinit var appPreferences: AppPreferences

    @Inject
    lateinit var widgetUpdater: DashboardWidgetUpdater
```
Unused fields

2022-10-13 09:17 UTC, AlvaroBrey commented on app/src/main/res/values/strings.xml
> +    <string name="widgets_not_available">Widgets are only available on >= NC25</string>
```suggestion
    <string name="widgets_not_available">Widgets are only available on Nextcloud 25 or later</string>
```
Rewording

2022-10-13 10:34 UTC, tobiasKaminsky commented on app/src/main/java/com/nextcloud/client/network/ClientFactoryImpl.java
> +public class ClientFactoryImpl implements ClientFactory {
This is needed by BitmapIT.

2022-10-13 10:39 UTC, AlvaroBrey commented on app/src/main/java/com/nextcloud/client/network/ClientFactoryImpl.java
> +public class ClientFactoryImpl implements ClientFactory {
Then add @VisibleForTesting

2022-10-13 13:30 UTC, AlvaroBrey approved these changes
Need to fix detekt, but appart from that looks good!

2022-10-14 04:49 UTC, tobiasKaminsky commented
⚠ I rebased

2022-10-14 09:06 UTC, AlvaroBrey approved these changes

2022-10-14 09:06 UTC, merged