Upload in background
nextcloud/android pull request #10737
Opened 2022-09-15 13:46 UTC by tobiasKaminsky

- [ ] Tests written, or not not needed

2022-09-15 13:59 UTC, tobiasKaminsky commented on app/src/main/java/com/owncloud/android/files/services/FileUploader.java
> +    private static boolean useFilesUploadWorker(Context context) {
@AlvaroBrey this leads to all tests run only with new approach (in FileUploaderIT).
Do you have an idea how we can have those tests run on both scenarios, old and new upload mechanism?

2022-09-16 08:04 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/files/services/FileUploader.java
> +    private static boolean useFilesUploadWorker(Context context) {
Something like this:
```java
FileUploader.java
---
private static boolean forceLegacyUploads = false;
---
@VisibleForTesting
public static void setForceLegacyUploads(final Boolean value){
    this.forceLegacyUploads = value;
}
---
private static boolean useFilesUploadWorker(Context context) {
     if (forceLegacyUploads) return false;
     return Build.VERSION.SDK_INT >= Build.VERSION_CODES.S || context.getResources().getBoolean(R.bool.is_beta);
}
```

And just call `forceLegacyUploads(true)` before tests where you want to use the legacy service.  If this was not all static I could come up with cleaner methods, but this is the best I can think of right now.

2022-09-23 06:28 UTC, tobiasKaminsky commented on app/src/main/java/com/owncloud/android/files/services/FileUploader.java
> +    private static boolean useFilesUploadWorker(Context context) {
Then I would have to run all the tests twice, but just add this before.
Similar to FileDataStorageManagerIT

Thanks!

2022-10-05 07:57 UTC, AlvaroBrey commented
/rebase

2022-10-11 06:53 UTC, tobiasKaminsky commented
/rebase

2022-10-12 10:06 UTC, tobiasKaminsky commented
Let's see what CI says :)

2022-10-12 12:32 UTC, tobiasKaminsky commented
/rebase

2022-10-13 06:13 UTC, tobiasKaminsky commented
@AlvaroBrey spotlessKotlinCheck fails, but auto format in AS is fine with it.

2022-10-13 09:45 UTC, AlvaroBrey requested changes

2022-10-13 09:45 UTC, AlvaroBrey commented on app/build.gradle
> +        targetSdkVersion 31
Should be a separate PR I think.

2022-10-13 09:45 UTC, AlvaroBrey commented on app/src/androidTest/java/com/owncloud/android/files/services/FileUploaderIT.kt
> +abstract class FileUploaderIT : AbstractOnServerIT() {
comment: For reference, this could instead be done by using the Parameterized runner instead of creating two new classes.

2022-10-13 09:45 UTC, AlvaroBrey commented on app/src/main/java/com/nextcloud/client/di/ComponentsModule.java
> +import com.owncloud.android.utils.FilesUploadHelper;
```suggestion
```
Unused import

2022-10-13 09:45 UTC, AlvaroBrey commented on app/src/main/java/com/nextcloud/client/jobs/BackgroundJobManager.kt
> +    fun getFileUploads(user: User): LiveData<MutableList<WorkInfo>>
This should expose `JobInfo`, not `WorkInfo`. Check [fromWorkInfo](https://github.com/nextcloud/android/blob/e2ef6c41125569d67843dc22db9bfabe98d41563/app/src/main/java/com/nextcloud/client/jobs/BackgroundJobManagerImpl.kt#L131-L131) for an explanation. You will need to use `Transformations.map` to map from a `List<WorkInfo>` to a `List<JobInfo>`

2022-10-13 09:45 UTC, AlvaroBrey commented on app/src/main/java/com/nextcloud/client/jobs/BackgroundJobManagerImpl.kt
> +    override fun getFileUploads(user: User): LiveData<MutableList<WorkInfo>> {
Should expose `LiveData<List<JobInfo>>` instead. Check the comment in `BackgroundJobManager` interface.

2022-10-13 09:45 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/MainApp.java
> +        // enableStrictMode();
```suggestion
        enableStrictMode();
```
Leftover.

2022-10-13 11:02 UTC, tobiasKaminsky commented on app/build.gradle
> +        targetSdkVersion 31
Done in https://github.com/nextcloud/android/pull/10797

2022-10-13 11:02 UTC, tobiasKaminsky commented on app/src/androidTest/java/com/owncloud/android/files/services/FileUploaderIT.kt
> +abstract class FileUploaderIT : AbstractOnServerIT() {
Great idea. I will do it later.

2022-10-14 18:55 UTC, AlvaroBrey commented
Rebased and fixed for m3 ✨

2022-10-17 15:01 UTC, AlvaroBrey approved these changes

2022-10-17 16:23 UTC, merged