Cache walled check for 10 minutes
nextcloud/android pull request #10996
Opened 2022-11-07 08:35 UTC by AlvaroBrey

Tentative cache time, accepting other proposals. My rationale for 10 minutes was that 6 checks an hour seems like not too much,
while not locking the app for too long in case there's an error and the cache is not cleared on network change.

See discussion in #10993 and #10087

cc @PVince81

- [x] Tests written, or not not needed

2022-11-16 11:10 UTC, tobiasKaminsky requested changes

2022-11-16 11:40 UTC, AlvaroBrey commented on app/src/main/java/com/nextcloud/client/network/WalledCheckCache.kt
> +                diff >= CACHE_TIME_MS
This class is held only in memory so it should be reset on boot, but I'll do the changes just in case.

2022-11-16 13:08 UTC, AlvaroBrey commented on app/src/main/java/com/nextcloud/client/network/WalledCheckCache.kt
> +                diff >= CACHE_TIME_MS
Used `currentTimeMillis` instead

2022-11-16 20:00 UTC, merged

2022-11-17 10:53 UTC, PVince81 commented
thanks a lot @AlvaroBrey