E2e ux
nextcloud/android pull request #11031
Opened 2022-11-14 15:41 UTC by tobiasKaminsky

- [ ] Tests written, or not not needed

2022-11-16 13:37 UTC, AlvaroBrey requested changes
I feel like the text under the preference is too long. I'd rather show a dialog with that text, which when clicking "OK" starts the other e2e setup steps. Additionally, see comments below

2022-11-16 13:37 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/ui/activity/SetupEncryptionActivity.kt
> +            Toast.makeText(this, "Error showing setup encryption dialog!", Toast.LENGTH_LONG).show()
Message should be localized

2022-11-16 13:37 UTC, AlvaroBrey commented on app/src/main/res/values/strings.xml
> +    <string name="displays_mnemonic">Displays your 12 words passphrase</string>
```suggestion
    <string name="displays_mnemonic">Displays your 12 word passphrase</string>
```

2022-11-16 13:37 UTC, AlvaroBrey commented on app/src/main/res/values/strings.xml
> +    <string name="comon_copy">Copy</string>
Typo:  `comon`  needs an extra M

2022-11-16 14:45 UTC, tobiasKaminsky commented
> I feel like the text under the preference is too long. I'd rather show a dialog with that text, which when clicking "OK" starts the other e2e setup steps.

True, but idea from designer is that user can directly understand what is done, and do not first has to think if clicking on it might directly enable it.

2022-11-17 08:07 UTC, AlvaroBrey commented on app/src/main/res/values/strings.xml
> +    <string name="setup_e2e">During setup of end to end encryption you will receive random 12 word mnemonic, which you need to add another client. This will only be stored on this computer and can be
```suggestion
    <string name="setup_e2e">During setup of end to end encryption, you will receive a random 12 word mnemonic, which you will need to open your files on other devices. This will only be stored on this device, and can be shown again in this screen. Please note it down in a secure place!</string>
```
Sorry for not catching these yesterday 😥

2022-11-17 10:04 UTC, AlvaroBrey approved these changes

2022-11-17 17:26 UTC, AlvaroBrey commented
Screenshot tests need updating

2022-11-17 18:31 UTC, AlvaroBrey requested changes

2022-11-17 18:31 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/ui/activity/SetupEncryptionActivity.kt
> +        val setupEncryptionDialogFragment = SetupEncryptionDialogFragment.newInstance(user, -1)
Need to add a listener to close the activity when the dialog is cancelled or dismissed, otherwise user will have a blank screen

2022-11-18 08:51 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/ui/activity/SetupEncryptionActivity.kt
> +        val setupEncryptionDialogFragment = SetupEncryptionDialogFragment.newInstance(user, -1)
Done in https://github.com/nextcloud/android/pull/11031/commits/9ba895280749a7991b6fa6ed2bc9ba1984055a95

I've also set the background of the activity to transparent, so that it's more seamless for the user:

<details>

![Screenshot_1668761427](https://user-images.githubusercontent.com/8677743/202660936-e5a19e85-daee-47b9-9df5-b8c2778ba6bd.png)


</details>

2022-11-18 08:52 UTC, AlvaroBrey approved these changes

2022-11-18 11:17 UTC, AlvaroBrey commented on app/schemas/com.nextcloud.client.database.NextcloudDatabase/65.json
>  {
Already commited schemas must not be changed! The app was probably built with changed entities but before bumping db version.

- [ ] Revert this file

2022-11-18 11:17 UTC, AlvaroBrey commented on app/schemas/com.nextcloud.client.database.NextcloudDatabase/66.json
> +{
- [ ] Enable automatic upgrades in room

2022-11-18 11:17 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
> +                !CapabilityUtils.getCapability(this).getEndToEndEncryptionKeysExist().isFalse()) {
```suggestion
                CapabilityUtils.getCapability(this).getEndToEndEncryptionKeysExist().isTrue()) {
```

Otherwise it will also be hidden for UNKNOWN value.

2022-11-18 11:20 UTC, tobiasKaminsky commented on app/src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
> +                !CapabilityUtils.getCapability(this).getEndToEndEncryptionKeysExist().isFalse()) {
I thought that this is what it should be…and I was wrong :S

2022-11-18 13:08 UTC, AlvaroBrey commented
/rebase

2022-11-18 13:12 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
> +            removeE2E(preferenceCategoryMore);
In my case, when I input the passphrase and finish the setup, this hides all of the e2e prefs. Not sure what's happening there.

2022-11-18 14:20 UTC, tobiasKaminsky commented on app/src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
> +            removeE2E(preferenceCategoryMore);
This is because in first run the preferences are removed as there is no other way.
And then after setup e2e they cannot be shown again.

Right now I see no other option other that the user has to re-enter settings page.

2022-11-18 14:27 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
> +            removeE2E(preferenceCategoryMore);
I can see two options:

- Add the preferences instead (new Preference(), and then add to the group)
- Restart the Activity  (new Intent with FLAG_NO_ANIMATION, launch, finish current)

2022-11-22 07:23 UTC, tobiasKaminsky commented on app/src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
> +            removeE2E(preferenceCategoryMore);
Nice idea with restarting the activity!

2022-11-25 10:30 UTC, merged