Allow Pin to Home with file actions bottom sheet
nextcloud/android pull request #11059
Opened 2022-11-19 13:26 UTC by newhinton

- [ ] Tests written, or not not needed

This PR superseeds #10491
It implements the same functionality for the new bottom-toolbar.

Closes #10491
Closes #3175

2022-11-21 11:18 UTC, AlvaroBrey requested changes
Hey @newhinton, many thanks! This works as expected, but there's a bunch of things that need to be polished before it can be merged.

You can do this yourself and re-request review. If you feel unsure about how to implement some of my requests, feel free to reach out to me via Talk or email.

If  you feel overwhelmed I can also do some the more complicated things for you. Let me know what you think!

2022-11-21 11:18 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
> +                new ShortcutUtil(getContext()).addShortcutToHomescreen(singleFile);
This should be injected instead of created here

2022-11-21 11:18 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/utils/MimeTypeUtil.java
> +        return drawableId;
To avoid duplicating, the existing `getFolderTypeIcon`  method should be refactored so that it calls this one to get the ID. Additionally the  logic in `getFolderTypeIcon` has been changed so that the groupfolder type takes precedence, please fix that.

2022-11-21 11:18 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/utils/ShortcutUtils.kt
> +class ShortcutUtil(val mContext: Context) {
```suggestion
class ShortcutUtil @Inject constructor (val mContext: Context) {
```
This will allow you to then inject the `ShortcutUtil` in `OCFileListFragment` and wherever else is needed.

Additionally the file should be name to `ShortcutUtil.kt` or the class to `ShortcutUtils`, to have them both match.

2022-11-21 11:18 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/utils/ShortcutUtils.kt
> +package com.owncloud.android.utils
Please move to `com.nextcloud.client.utils` instead

2022-11-21 11:18 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/utils/ShortcutUtils.kt
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
If the functionality only works >= O, then the menu item should be hidden (in FileMenuFilter) when the current SDK is less than that.

2022-11-21 11:18 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/utils/ShortcutUtils.kt
> +            if (shortcutManager.isRequestPinShortcutSupported) {
Same as above: this should be taken into account in order to hide the menu entry.

2022-11-21 11:18 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/utils/ShortcutUtils.kt
> +        val adaptiveIconOuterSides = (18 * screenDensity).roundToInt()
What do these icon sizes correspond to?  In any case, they should be extracted to `dimen` resources or at least constants.

2022-11-21 11:18 UTC, AlvaroBrey commented on app/src/main/res/values/strings.xml
> +    <string name="pin_home">Pin to Homescreen</string>
```suggestion
    <string name="pin_home_text">This will create a shortcut on your Home screen</string>
    <string name="pin_home">Pin to Home screen</string>
```

2022-11-21 12:55 UTC, newhinton commented
@AlvaroBrey I know this has been mentioned before, but could you ask your team if it is possible to run all the github actions only on selected branches and or tagged branches? 

First, usually not every commit needs every action automatically run wich saves resources, and to be frank at some point the mails it sends out are just spam. It would be great if this would be applied more carefully.


Regarding the changes: i will make them, that's not a problem at all. I will rerequest a review when i am done!

2022-11-21 14:12 UTC, newhinton commented on app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
> +                new ShortcutUtil(getContext()).addShortcutToHomescreen(singleFile);
What exactly do you mean by injection?

2022-11-21 14:14 UTC, newhinton commented on app/src/main/java/com/owncloud/android/utils/MimeTypeUtil.java
> +        return drawableId;
I think i added this wrongly after pulling code from the old one to the new pr. I will remove the "broken" call completely and adapt the call at the source.

2022-11-21 14:16 UTC, AlvaroBrey commented
> @AlvaroBrey I know this has been mentioned before, but could you ask your team if it is possible to run all the github actions only on selected branches and or tagged branches?
> 
> First, usually not every commit needs every action automatically run wich saves resources, and to be frank at some point the mails it sends out are just spam. It would be great if this would be applied more carefully.

We run them on PRs that target master or a stable branch on purpose, so we can verify the changes _before_ merging. You may reduce the number of comments by:

- pushing the commits in batches rather than one at a time. actions will only run for the last of the batch
-  changing your subscription for the PR. with "customize" you can set it so that only mentions and close/merge/reopen events trigger an email
- changing your notification settings for Github as a whole so that you don't get emails for every notification

> 
> Regarding the changes: i will make them, that's not a problem at all. I will rerequest a review when i am done!

Thanks!

2022-11-21 15:39 UTC, newhinton commented on app/src/main/java/com/owncloud/android/utils/ShortcutUtils.kt
> +        val adaptiveIconOuterSides = (18 * screenDensity).roundToInt()
If i remember correctly, those are taken from here:
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

They are specified by convention, and i could not find constants for them. I will extract them to dimen, and add a comment explaining that.

2022-11-21 16:03 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
> +                new ShortcutUtil(getContext()).addShortcutToHomescreen(singleFile);
We use Dagger as a DI framework; the `ShortcutUtil` class should be injected into OCFileListFragment instead of created by it. I can do this if you want

2022-11-21 22:15 UTC, newhinton commented on app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
> +                new ShortcutUtil(getContext()).addShortcutToHomescreen(singleFile);
That would be great! I have not used Dagger so i wouldn't really know where to start. But i'll watch what you do with it!

2022-11-22 09:54 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
> +                new ShortcutUtil(getContext()).addShortcutToHomescreen(singleFile);
Done here: https://github.com/nextcloud/android/pull/11059/commits/8a24ea03a014f70fdc5d0df0d9603e83809c6c5b

2022-11-22 09:55 UTC, AlvaroBrey commented
@newhinton I just pushed the DI patch, and a couple of extras. Take a look at  https://github.com/nextcloud/android/pull/11059/commits/52e1e8cef5031a12fc57e0b75081c55d94164fa9 especially, as it will allow shortcuts on SDK < 26 too.

2022-11-22 10:06 UTC, AlvaroBrey requested changes

2022-11-22 10:06 UTC, AlvaroBrey commented on app/src/main/java/com/nextcloud/utils/ShortcutUtil.kt
> +                .setLongLabel("Open " + file.fileName)
This string needs to be extracted to strings.xml in order to be translatable. Use a parameter in the extracted string (`%1$s`) and then call `context.getString(R.string.your_string_id, file.fileName)`

2022-11-22 15:55 UTC, AlvaroBrey approved these changes
Great work @newhinton ! Thanks very much. I'll wait for @tobiasKaminsky to review, but from my perspective this is ready to go

2022-11-23 17:56 UTC, merged

2022-11-23 17:57 UTC, AlvaroBrey commented
/backport to stable-3.23