Disable StrictMode by default
nextcloud/android pull request #11073
Opened 2022-11-23 09:41 UTC by AlvaroBrey

StrictMode is not a good fit for the state of our app, since we are way too far from async operations or correct threading.
As a result, we find ourselves disabling the strict mode manually every time we actually want to work on something, as otherwise the
logspam drowns everything else.

With this PR I propose to disable StrictMode unless a prop is set in the Gradle build, which will also control LeakCanary.
Running `./gradlew installGplayDebug -P perfAnalysis` will install the app with both LeakCanary and StrictMode enabled.
This allows us to analyze performance problems on demand, without making our daily work harder.

- [x] Tests written, or not not needed

2022-11-23 10:27 UTC, AlvaroBrey commented
/backport to stable-3.23

2022-11-24 08:41 UTC, tobiasKaminsky commented
That is a way better approach!
Back then I thought it is good to enable it, so that it bugs us that we get rid of those async.
But indeed it is way harder to do, and meanwhile it distracts us.

2022-11-24 08:42 UTC, tobiasKaminsky requested changes
Please add doc

2022-11-24 08:42 UTC, tobiasKaminsky commented on app/build.gradle
> +def perfAnalysis = project.hasProperty('perfAnalysis')
Can you add this to one of our docs?
Especially "-P " might not be known to all devs.

2022-11-24 09:07 UTC, AlvaroBrey commented on app/build.gradle
> +def perfAnalysis = project.hasProperty('perfAnalysis')
Done!

2022-11-24 09:09 UTC, AlvaroBrey commented
> Back then I thought it is good to enable it, so that it bugs us that we get rid of those async.

Future project: get StrictMode warnings from logcat in CI, as another check

2022-11-29 06:26 UTC, tobiasKaminsky approved these changes
Awesome idea to combine leakCanary and strictMode with perf flag!

2022-11-29 12:23 UTC, merged