[NEXT-2] Use SplashScreen API
nextcloud/android pull request #11152
Opened 2022-12-08 08:14 UTC by gitstart

Fixes https://github.com/nextcloud/android/issues/9230

### To Test

1. Test that the splash screen is the same as before the refactor 

### Video
### Before
[next-before.webm](https://user-images.githubusercontent.com/93866435/205010355-46d49458-3515-463c-a559-b6bef5b86171.webm)
### After
[next-after.webm](https://user-images.githubusercontent.com/93866435/205012620-bf6fea94-c04f-4181-b04c-f2e44e26353c.webm)

2022-12-08 10:49 UTC, tobiasKaminsky commented
Wow. Coool!

2022-12-08 10:50 UTC, tobiasKaminsky approved these changes

2022-12-11 22:24 UTC, AlvaroBrey requested changes
Hi @gitstart and thanks for your interest in contributing!

However this is incorrectly applied, according to the docs: https://developer.android.com/reference/androidx/core/splashscreen/SplashScreen

As it stands, this only leaves the app functioning exactly the same as before, as the splash screen theme is ignored by explicitly setting window background and not correctly using the splash screen properties; and the theme is still manually switched on `FileDisplayActivity`'s `onCreate`

* There is  no call to `installSplashScreen` on `FileDisplayActivity`s `onCreate`.
* Additionally to this we should remove  the explicit `setTheme` in `FileDisplayActivity.java` as well, as the splashscreen lib will handle the theme change for us with `postSplashScreenTheme`.

2022-12-11 22:24 UTC, AlvaroBrey commented on app/src/main/res/values/styles.xml
> +        <item name="android:windowBackground">@drawable/launch_screen</item>
This theme is configured incorrectly according to the docs. Instead of setting the window background, you should use `windowSplashScreenAnimationIcon` for the icon (you can use `@drawable/ic_launcher_foreground` for this) and use `windowSplashScreenBackground` for the background.

2022-12-11 22:24 UTC, AlvaroBrey commented on app/src/main/res/values/styles.xml
>          <item name="android:textColorHint">@color/secondary_text_color</item>
Not sure if these are needed at all, if using the `windowSplashBackground` properly.

2022-12-12 10:21 UTC, AlvaroBrey commented
/rebase

2022-12-13 05:18 UTC, closed without merging

2022-12-13 05:20 UTC, gitstart commented
@AlvaroBrey 
Due to some technical glitch, we encountered this issue. We will push all the PRs again.