upon upgrade localID may be null, better use default value
nextcloud/android pull request #11287
Opened 2023-01-24 07:58 UTC by tobiasKaminsky

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

- [ ] Tests written, or not not needed

2023-01-24 08:24 UTC, AlvaroBrey requested changes

2023-01-24 08:24 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/db/ProviderMeta.java
> +    public static final int DB_VERSION = 68;
Missing the new json schema, and the `AutoMigration` in `NextcloudDatabase`

2023-01-24 09:01 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/db/ProviderMeta.java
> +    public static final int DB_VERSION = 68;
In fact, this (changing null to not null) cannot be done with an automigration. A manual migration must be used.

2023-01-24 10:23 UTC, AlvaroBrey approved these changes

2023-01-25 06:30 UTC, merged

2023-01-30 10:18 UTC, galvalarzen commented
No solution?