Migrate to media3
nextcloud/android pull request #11936
Opened 2023-09-02 23:19 UTC by parneet-guraya

Closes: #11829
## What this PR includes?
- Changes from migration script (for migrating from exoplayer2 to media3).
- Remove the old way to watch video full screen with creating a new dialog (which is breaking in new media3 API) 
- New functionality to go full screen(immersive mode) when playing video.
- [x] Tests written, or not not needed

### Before

https://github.com/nextcloud/android/assets/111801812/a46d63d3-9570-448d-acfb-1c8489772a2b

### After

https://github.com/nextcloud/android/assets/111801812/19414a90-a0c4-4d9a-9930-db5b6e82c652

2023-09-02 23:23 UTC, parneet-guraya commented
Hi, the immersive mode functionality that I added still can be improved, since it wasn't the scope of this PR I didn't do here.But, I surely can come up with some nice smooth transition (going in/out fullscreen), maybe can inspiration from Google Drive, Whatsapp etc. 

Let me know what do you think and if it needs little polishing

Thanks!

2023-09-05 17:25 UTC, parneet-guraya commented
This is how Google Drive's media playback UI looks like (in light mode)

https://github.com/nextcloud/android/assets/111801812/e3564d26-f707-42bd-b164-324e401b8e55

For both video and audio playbacks it has default dark UI (for both light and dark mode)

2023-09-05 19:41 UTC, parneet-guraya commented
This is how it looks with background black (only done for videos)

https://github.com/nextcloud/android/assets/111801812/f7798191-c223-4a8c-8447-c1243c5c1e9d

2023-09-05 19:54 UTC, AndyScherzinger commented
@parneet-guraya thanks a lot for working on this migration. Can you please address the newly introduced lint errors? See https://www.kaminsky.me/nc-dev/android-lint/5531.html

Thanks in advance, highly appreciate your contributions 🤩

2023-09-05 20:12 UTC, parneet-guraya commented
I'm happy to contribute :smile: 
You can see [here](https://developer.android.com/guide/topics/media/media3/getting-started/migration-guide#unstableapi) about the lint errors.

> If you don't require strict binary compatibility, these errors can be safely suppressed with an @OptIn annotation.

 I'm not really sure about what binary compatibility they are referring to tell me if that is something concerning otherwise we can use the annotation as mentioned, although I did use the annotation I think did not do in some file that's why lint error, I fixed them and pushing again to see if the lint error goes.

2023-09-17 12:20 UTC, parneet-guraya commented
Found out the status bar color is not applied when handling display cutout in the `FileDisplayActivity`. The change only gets applied to activities. Although we just need it for media playback but since it is a fragment, we cannot have that applied there. Looking into what can be done. Marking this as draft and removing review requests.

2023-12-15 13:29 UTC, parneet-guraya commented
Hi, @AndyScherzinger @ZetaTom. PR"s ready here's what it includes
- [x] Changes from migration script (for migrating from exoplayer2 to media3).
- [x] New functionality to go full screen(immersive mode) when playing video.
- [x] Migration to Activity from Fragment for Media preview.

### Migrate To Activity Demo -->

https://github.com/nextcloud/android/assets/111801812/168314f3-a18a-4c9b-b2af-402e46bbb577

You can see every operation in the activity works fine. 

**Note:** Activity is being used to show the preview except one place `PreviewImagePagerAdapter` as it uses fragments to show media (photo & video). So, dependency on Fragment has not been completely removed as stated here #12285. You can also see below in the pager fragment is being used. 

### Preview Media Fragment in Pager Demo -->

- [x]  Dependency on overriding internal layout resource (to add fullscreen button) has been removed as the resources were marked private in `media3`

https://github.com/nextcloud/android/assets/111801812/36602bd6-275b-4289-98e0-f453a54ca096


### Media Demo -->

- [x] You can see padding has been added to both Toolbar and media bottom control to render into the notch area just like GDrive.

https://github.com/nextcloud/android/assets/111801812/d70a4ce1-730e-4c56-baf8-b14e4a21e9ad

2023-12-18 08:58 UTC, alperozturk96 approved these changes

2023-12-26 09:40 UTC, alperozturk96 requested changes

2023-12-26 09:40 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaActivity.kt
> +        exoPlayer!!.setMediaItem(MediaItem.fromUri(uri))
Please dont use "!!" operator handle nullable variables with "?" this operator

2023-12-26 09:40 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaActivity.kt
> +            val weakReference = previewMediaActivityWeakReference.get()
Could you use "apply, let, run" function blocks to make more readable clean code?

e.g

```
weakReference?.let {
    videoUri = uri
    playVideoUri(uri)
}

...
```

2023-12-26 09:40 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaActivity.kt
> +        val showDetailsIntent = Intent(this, FileDisplayActivity::class.java)
Could you use "apply, let, run" function blocks to make more readable clean code?

2023-12-26 09:40 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
> +        binding.exoplayerView.setShowNextButton(false);
Could you use "apply, let, run" function blocks to make more readable clean code?

2023-12-26 10:27 UTC, parneet-guraya commented
@alperozturk96 Done :+1:

2023-12-26 14:42 UTC, alperozturk96 requested changes

2023-12-26 14:42 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaActivity.kt
> +            exoPlayer!!.seekTo(savedPlaybackPosition)
seekTo function also can moved into let block no need to use "!!" operator

2023-12-26 14:42 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaActivity.kt
> +        file = bundle!!.getParcelableExtra(FILE)
Please handle nullable intent with "?" operator, use getParcelableArgument rather than getParcelableExtra.

2023-12-26 14:42 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaActivity.kt
> +    override fun onCreate(savedInstanceState: Bundle?) {
onCreate function is too big. I suggest to divide into multiple single responsible functions.

2023-12-26 14:42 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaActivity.kt
> +        binding.emptyView.emptyListViewHeadline.text = headline
binding.emptyView?.run {} can we use run block to prevent multiple binding.emptyView calls?

2023-12-26 14:42 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaActivity.kt
> +        if (MimeTypeUtil.isAudio(file)) {
Reverting conditions increase readebility of function.

e.g
if (!MimeTypeUtil.isAudio(file)) {
   return
}

rest of function
...
....
......

2023-12-26 14:42 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaActivity.kt
> +        val logo = AppCompatResources.getDrawable(this, R.drawable.logo)
AppCompatResources.getDrawable(this, R.drawable.logo)?.let {
} 

this block can be used for all function

2023-12-26 14:42 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaActivity.kt
> +        outState.putParcelable(EXTRA_FILE, file)
outState?.apply {} can be used

2023-12-26 14:42 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaActivity.kt
> +        super.onStart()
onStart function is too big, it can divided into multiple functions.

2023-12-26 14:42 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaActivity.kt
> +        windowInsetsController = WindowCompat.getInsetsController(
windowInsetsController?.apply {} can be used

2023-12-26 14:42 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaActivity.kt
> +            val i = Intent(this, FileDownloader::class.java)
```
val i = Intent(this, FileDownloader::class.java).apply {
...
...
downloadBehavior?.let { behavior ->
                i.putExtra(OCFileListFragment.DOWNLOAD_BEHAVIOUR, behavior)
                i.putExtra(SendShareDialog.PACKAGE_NAME, packageName)
                i.putExtra(SendShareDialog.ACTIVITY_NAME, activityName)
            }
}

startService(i)
```

can be used

2023-12-26 14:42 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaActivity.kt
> +        exoPlayer?.stop()
exoPlayer?.apply {

}

can be used

2023-12-26 14:42 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
> +        binding.exoplayerView.setShowPreviousButton(false);
binding.exoplayerView.apply {

}

can be used instead using same variable multiple times

2023-12-27 02:45 UTC, parneet-guraya commented on app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
> +        binding.exoplayerView.setShowPreviousButton(false);
Cannot use scoping function here since this file is in Java :-)

2023-12-27 03:48 UTC, parneet-guraya commented on app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaActivity.kt
> +        windowInsetsController = WindowCompat.getInsetsController(
We're just initializing the variable and setting one property, do we really need a scoping function for just setting one property? Also It's value is non-null.

2023-12-27 03:55 UTC, parneet-guraya commented on app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaActivity.kt
> +        if (MimeTypeUtil.isAudio(file)) {
The condition `if (MimeTypeUtil.isAudio(file))` will do nothing anyways if mime type's other than `Audio`. Are you asking me to explicity return from function when condition does not satisfy?

2023-12-27 08:07 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
> +        binding.exoplayerView.setShowPreviousButton(false);
Oh yes right I mixed with PreviewMediaActivity.

2023-12-27 08:14 UTC, alperozturk96 requested changes

2023-12-27 08:14 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaActivity.kt
> +        if (MimeTypeUtil.isAudio(file)) {
Yes. Nested if conditions decreasing the readability of code.

2023-12-27 08:14 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaActivity.kt
> +        windowInsetsController = WindowCompat.getInsetsController(
No need to write windowInsetsController two times. We can achieve same thing like that as well. I suggest this approach :)

```
windowInsetsController = WindowCompat.getInsetsController(
            window,
            window.decorView
        ).apply {
            systemBarsBehavior = WindowInsetsControllerCompat.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE
        }
```

2023-12-28 13:58 UTC, alperozturk96 approved these changes

2023-12-28 17:21 UTC, JonasMayerDev approved these changes
Works as expected for me :)

2023-12-29 08:01 UTC, merged