Use Material Design 3 For ConflictResolve Dialog
nextcloud/android pull request #12036
Opened 2023-10-13 14:28 UTC by alperozturk96

Before:
<img width="372" alt="conflict_before" src="https://github.com/nextcloud/android/assets/67455295/7a04091a-aec4-4c9f-b615-72ae08b184c5">

After:
<img width="372" alt="confict_after" src="https://github.com/nextcloud/android/assets/67455295/e40fc4b7-45e1-4ee4-ae9f-539d7815b350">

- [ Done ] Tests written, or not not needed

2023-10-13 15:24 UTC, AndyScherzinger approved these changes
Code looks good, updated screenshots missing

2023-10-16 06:41 UTC, tobiasKaminsky requested changes
updated Screenshots are missing

2023-10-17 08:15 UTC, AndyScherzinger approved these changes

2023-10-18 05:08 UTC, tobiasKaminsky commented
Please revert those screenshots that are unrelated to this PR.

2023-10-20 15:07 UTC, merged