Use Material Design 3 For Confirmation Dialog
nextcloud/android pull request #12041
Opened 2023-10-16 07:21 UTC by alperozturk96

- [ Done ] Tests written, or not not needed

2023-10-18 05:09 UTC, tobiasKaminsky approved these changes

2023-10-18 05:10 UTC, tobiasKaminsky commented
:clap: :clap: for testing RTL

2023-10-18 08:40 UTC, tobiasKaminsky commented
Hm.

> java.io.FileNotFoundException: Source '/Users/runner/work/android/android/app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testConfirmationDialogWithThreeActionRTL.png' does not exist

Seems that test will not create an output if a screenshot is missing.
Maybe this has changed.
So I think you need to run it locally and add the expected screenshot.

2023-10-19 07:43 UTC, tobiasKaminsky requested changes
Add missing screenshot
rebase

2023-10-30 16:05 UTC, AndyScherzinger approved these changes

2023-10-30 18:32 UTC, merged