Use Material Design 3 share password dialog fragment
nextcloud/android pull request #12047
Opened 2023-10-16 11:39 UTC by alperozturk96

Before Enforced:
<img width="407" alt="before_enforced" src="https://github.com/nextcloud/android/assets/67455295/d0c9b40f-fa8f-42e6-95e2-f1db8d6b53fb">

After Enforced:
<img width="407" alt="after_enforced" src="https://github.com/nextcloud/android/assets/67455295/cf214ab1-827f-4a6f-9bea-2084dbd5035e">

------------------------------------------

Before Optional:
<img width="407" alt="before optional" src="https://github.com/nextcloud/android/assets/67455295/1a7d85c6-af5a-4b42-814e-6de8b5d0d8cb">

After Optional:
<img width="407" alt="after_optional" src="https://github.com/nextcloud/android/assets/67455295/290a566e-2668-4b71-be31-9eaf4509d2fa">

- [ Done ] Tests written, or not not needed

2023-10-16 17:35 UTC, AndyScherzinger approved these changes

2023-10-18 05:23 UTC, tobiasKaminsky approved these changes

2023-10-18 05:24 UTC, tobiasKaminsky commented
Please update screenshots related to this PR.

2023-10-19 07:42 UTC, tobiasKaminsky requested changes
Update screenshots

2023-10-26 12:28 UTC, alperozturk96 commented
@tobiasKaminsky Failed due to 

<img width="660" alt="Screenshot 2023-10-26 at 14 27 47" src="https://github.com/nextcloud/android/assets/67455295/1d931d4a-f12f-427b-bbd8-1dd5bb373a35">

2023-10-30 18:33 UTC, merged