Use Material Design 3 for StoragePermissionDialogFragment
nextcloud/android pull request #12050
Opened 2023-10-16 13:57 UTC by alperozturk96

Before:
<img width="363" alt="before" src="https://github.com/nextcloud/android/assets/67455295/190eb2d6-9d7a-493e-b634-7036f7faa1ed">

After:
<img width="363" alt="after" src="https://github.com/nextcloud/android/assets/67455295/47198476-2ab5-4306-92f7-64c4906d470e">

- [ Done ] Tests written, or not not needed

2023-10-17 08:10 UTC, AndyScherzinger requested changes
@alperozturk96 
<img width="363" alt="after" src="https://github.com/nextcloud/android/assets/67455295/47198476-2ab5-4306-92f7-64c4906d470e">

Dialog background tinting lost

2023-10-17 10:14 UTC, alperozturk96 commented
Updated

2023-10-18 08:38 UTC, tobiasKaminsky approved these changes

2023-10-18 10:01 UTC, AndyScherzinger approved these changes

2023-10-18 10:02 UTC, merged