Bugfix Check Network Connection When File Item Clicked
nextcloud/android pull request #12093
Opened 2023-10-25 10:46 UTC by alperozturk96

- [ Done ] Tests written, or not not needed

2023-10-30 14:56 UTC, ZetaTom reviewed
Refactoring is a necessary effort, but it is generally considered good practise to keep pull requests as modular as possible. I would suggest moving all changes, not strictly needed to fix the issue at hand, into a separate pull request.

2023-10-31 12:16 UTC, alperozturk96 commented
@ZetaTom I agree. Single responsibility in PR is important. I will revert those changes (enhanced switch case, requireActivity, requireContext usages)

2023-11-06 14:45 UTC, tobiasKaminsky commented on app/src/main/java/com/nextcloud/client/network/ConnectivityObserver.kt
> +object ConnectivityObserver {
We already have ConnectivityService for this.
Please use/combine those.

2023-11-10 08:15 UTC, tobiasKaminsky commented on app/src/main/java/com/nextcloud/client/network/ConnectivityServiceImpl.java
> +public class ConnectivityServiceImpl implements ConnectivityService {
This is implemention of an interface.
Please add the new function to its interface.

2023-11-10 08:15 UTC, tobiasKaminsky commented on app/src/main/java/com/owncloud/android/ui/activity/FileActivity.java
> +        if (ConnectivityServiceImpl.isConnected(this)) {
When it is via interface you can use "connectivityService", which is injected.

2023-11-10 08:15 UTC, tobiasKaminsky requested changes
Use interface

2023-11-10 09:27 UTC, alperozturk96 commented
@tobiasKaminsky Interface used

2023-11-15 08:49 UTC, ZetaTom reviewed
During my testing, I've found that there are certain cases where the message disappears even though the server is unavailable. For example, if you open a media preview while the server is stopped.

2023-11-15 10:13 UTC, alperozturk96 commented
@ZetaTom When user don't have internet I am always seeing Server not available message. Could you share video?

2023-11-21 08:53 UTC, ZetaTom commented
@alperozturk96, the message disappears if the device *is* online but the ***server** isn't*.

[server_availability.webm](https://github.com/nextcloud/android/assets/70907959/a892ae7d-057a-4e12-9a11-e2caf1d87a54)

2023-11-21 09:01 UTC, alperozturk96 commented
@ZetaTom I assume you expect to still see the message if our backend not available if yes then my question will be our backend providing heartbeat API? So I can check backend health?

2023-12-03 08:18 UTC, tobiasKaminsky commented
/rebase

2023-12-04 11:22 UTC, JonasMayerDev approved these changes

2023-12-06 09:14 UTC, alperozturk96 commented
/backport to stable-3.27

2023-12-11 07:12 UTC, merged