Update M3 library, Increase target sdk to 34
nextcloud/android pull request #12106
Opened 2023-10-30 08:58 UTC by alperozturk96

- [ Done ] Tests written, or not not needed

2023-10-30 08:59 UTC, alperozturk96 commented on app/build.gradle
> +        targetSdkVersion 34
Needed for latest M3 library

2023-10-30 10:16 UTC, ZetaTom reviewed
Seems to work well during my brief tests. Have the [behavioural changes](https://developer.android.com/about/versions/14/behavior-changes-all) of Android 14 been addressed already?

According to the lint bot there are apparently some missing `super` calls in various activities that haven't been changed by this pull request. Maybe something else or some requirements have changed in the meantime?

2023-10-30 11:07 UTC, alperozturk96 commented
As far as I know regarding behavioural changes on Android 14 nothing specificly done in codebase. Regardless targetSdkVersion if device have Android 14 that changes automatically done so increasing or decreasing targetSdkVersion not going to effect anything on Android 14 devices. @ZetaTom We must check "Behavior changes" for Android 14 device but I think it's not related to this PR. 

Seems like after targetSdkVersion change Linter seeing those intentionally not called super method as warning. However, I see that the default action is not requested in those activities. If we call super methods, the behavior of the application may change. In this case we can use @Suppress annotation.

2023-11-07 06:39 UTC, tobiasKaminsky commented
Unit tests are failing to compile:
> Task :app:compileGplayDebugUnitTestKotlin FAILED
e: file:///home/runner/actions-runner/_work/android/android/app/src/test/java/com/***/client/core/LocalConnectionTest.kt:68:39 Overload resolution ambiguity: 
public open fun bindService(p0: Intent, p1: ServiceConnection, p2: Context.BindServiceFlags): Boolean defined in android.content.Context
public abstract fun bindService(p0: Intent, p1: ServiceConnection, p2: Int): Boolean defined in android.content.Context
e: file:///home/runner/actions-runner/_work/android/android/app/src/test/java/com/***/client/core/LocalConnectionTest.kt:79:25 None of the following functions can be called with the arguments supplied: 
public open fun bindService(p0: Intent, p1: ServiceConnection, p2: Context.BindServiceFlags): Boolean defined in android.content.Context
public abstract fun bindService(p0: Intent, p1: ServiceConnection, p2: Int): Boolean defined in android.content.Context
e: file:///home/runner/actions-runner/_work/android/android/app/src/test/java/com/***/client/core/LocalConnectionTest.kt:79:73 The boolean literal does not conform to the expected type Unit
e: file:///home/runner/actions-runner/_work/android/android/app/src/test/java/com/***/client/core/LocalConnectionTest.kt:84:26 None of the following functions can be called with the arguments supplied: 
public open fun bindService(p0: Intent, p1: ServiceConnection, p2: Context.BindServiceFlags): Boolean defined in android.content.Context
public abstract fun bindService(p0: Intent, p1: ServiceConnection, p2: Int): Boolean defined in android.content.Context
w: Detected multiple Kotlin daemon sessions at kotlin/sessions

2023-11-07 06:40 UTC, tobiasKaminsky commented
Android 14 specific can and should be discussed in https://github.com/nextcloud/android/issues/11791

2023-11-07 06:41 UTC, tobiasKaminsky requested changes
Tests are failing to compile

2023-11-10 09:47 UTC, alperozturk96 commented
/rebase

2023-11-10 09:51 UTC, alperozturk96 commented
/rebase

2023-11-14 09:58 UTC, alperozturk96 commented
/rebase

2023-11-14 12:17 UTC, AndyScherzinger commented
@alperozturk96 has conflicts on rebase (!)

2023-11-14 13:00 UTC, alperozturk96 commented
/rebase

2023-11-15 15:15 UTC, alperozturk96 commented
/rebase

2023-11-15 17:13 UTC, AndyScherzinger commented
@alperozturk96 you need to rebase yourself, since you will have to resolve conflicts which you originally resolved during pulling in master. So the rebase comment won't work.

2023-11-16 15:50 UTC, AndyScherzinger approved these changes
Unit tests are fine, only codecov upload fails (not related) and Drone failures are also not related.

2023-11-16 19:09 UTC, AndyScherzinger commented
@tobiasKaminsky @ZetaTom works for my on my phone, however I didn't check for the behavioral changed but as stated by Tobias are to be discussed in the or ticket. So for me the PR is good to go.

2023-11-17 13:30 UTC, merged