Fix warnings for OCFileListFragment
nextcloud/android pull request #12112
Opened 2023-10-31 14:02 UTC by alperozturk96

- [ ] Tests written, or not not needed

2023-10-31 14:03 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
> -    public void onMessageEvent(FileLockEvent event) {
Unused function

2023-11-06 09:32 UTC, AndyScherzinger commented on app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
> -    public void onMessageEvent(FileLockEvent event) {
Like mentioned in the other PR, I expect the event bus to make use of them, so this should actually be a false-positive, best to check with @tobiasKaminsky

2023-11-07 07:06 UTC, tobiasKaminsky commented on app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
> -    public void onMessageEvent(FileLockEvent event) {
Yeah, this is still used.
You can check where FileLockEvent is being used:
Within FileOperationsHelper there is: EventBus.getDefault().post(new FileLockEvent(file.getRemotePath(), shouldBeLocked));

This is to send the event, and the other function receives it.

In long term I would like to get rid of it…

2023-11-07 07:08 UTC, tobiasKaminsky requested changes
Re-add event bus function.

2023-11-15 11:45 UTC, ZetaTom commented on app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
> +        if ((fragmentActivity = getActivity()) != null && fragmentActivity instanceof FileDisplayActivity fileDisplayActivity) {
```suggestion
        if (getActivity() instanceof FileDisplayActivity fileDisplayActivity) {
```

2023-11-15 11:49 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
> +    // Do not delete this function
IDE will always show as unused function better to keep that comment

2023-11-20 09:34 UTC, alperozturk96 commented
/rebase

2023-11-20 11:31 UTC, alperozturk96 commented
/rebase

2023-11-20 13:38 UTC, alperozturk96 commented
/rebase

2023-11-22 08:24 UTC, alperozturk96 commented
/rebase

2023-11-22 10:29 UTC, alperozturk96 commented
/rebase

2023-12-03 08:18 UTC, tobiasKaminsky commented
/rebase

2024-04-22 12:47 UTC, alperozturk96 commented
Out of date due to conflicts

2024-04-22 12:47 UTC, closed without merging