Fix warnings for FilesDisplayActivity
nextcloud/android pull request #12113
Opened 2023-10-31 14:13 UTC by alperozturk96

- [x] Tests written, or not not needed

2023-11-01 20:52 UTC, AndyScherzinger requested changes
see comment, best to check with Tobias

2023-11-01 20:52 UTC, AndyScherzinger commented on app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
> -    @Subscribe(threadMode = ThreadMode.BACKGROUND)
@tobiasKaminsky might know this better, but I expect these functions to be used by the event bus, so the code checks are false positives.

2023-11-08 10:12 UTC, ZetaTom commented on app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
> -    @Subscribe(threadMode = ThreadMode.BACKGROUND)
I've done some testing and found out, that these functions are indeed called when an event is dispatched on the eventbus.

For example, `public void onMessageEvent(final SearchEvent event)` is called, when the user switches to the *Favourites* tab from the main *All files* view.

2023-11-10 09:16 UTC, alperozturk96 commented
/rebase

2023-11-14 09:58 UTC, alperozturk96 commented
/rebase

2023-11-14 13:03 UTC, alperozturk96 commented
/rebase

2023-11-20 07:58 UTC, tobiasKaminsky approved these changes

2023-11-20 07:59 UTC, tobiasKaminsky commented
/rebase

2023-11-20 09:34 UTC, alperozturk96 commented
/rebase

2023-11-21 12:24 UTC, alperozturk96 commented
/rebase

2023-12-03 08:18 UTC, tobiasKaminsky commented
/rebase

2024-02-22 08:29 UTC, alperozturk96 commented
Outdated PR, too much diff to merge it.

2024-02-22 08:29 UTC, closed without merging