Convert AccountAuthenticator to Kotlin
nextcloud/android pull request #12126
Opened 2023-11-02 11:44 UTC by alperozturk96

- [ ] Tests written, or not not needed

2023-11-07 07:52 UTC, tobiasKaminsky commented
Detekt is failing.
Restarted Drone.

2023-11-07 07:53 UTC, tobiasKaminsky requested changes
Fix detekt

2023-11-10 09:28 UTC, alperozturk96 commented
/rebase

2024-04-22 12:47 UTC, alperozturk96 commented
Out of date due to conflicts

2024-04-22 12:47 UTC, closed without merging