Fix Race Condition on Passcode Manager
nextcloud/android pull request #12125
Opened 2023-11-02 10:14 UTC by alperozturk96

Normal App Launch Test After Fix:
https://github.com/nextcloud/android/assets/67455295/82b15096-741d-4236-8a8e-0c217b6bfd73

Exploit App Launch Test After Fix:
https://github.com/nextcloud/android/assets/67455295/e0f24aac-c730-4663-ba14-12a3452025f0

- [ ] Tests written, or not not needed

2023-11-07 07:04 UTC, tobiasKaminsky requested changes
Not working :disappointed:

2023-11-08 08:21 UTC, ZetaTom requested changes
Unfortunately, this change does not fix the issue.

2023-11-22 08:22 UTC, alperozturk96 commented
@ZetaTom @tobiasKaminsky Waiting response from you regarding [this](https://github.com/nextcloud-gmbh/h1/issues/478#issuecomment-1803565183) comment so that I continue work on this PR.

2023-11-27 09:53 UTC, ZetaTom commented
> @ZetaTom @tobiasKaminsky Waiting response from you regarding [this](https://github.com/nextcloud-gmbh/h1/issues/478#issuecomment-1803565183) comment so that I continue work on this PR.

@alperozturk96, please have a look at the private message I have sent you.

2024-02-20 12:08 UTC, closed without merging