Add Files Action to Search
nextcloud/android pull request #12209
Opened 2023-11-28 07:47 UTC by alperozturk96

Uploading ress.mov…

This feature needed for [this](https://github.com/nextcloud/android/pull/12092) bugfix

- [ ] Tests written, or not not needed

2023-11-29 09:34 UTC, ZetaTom requested changes

2023-11-29 09:34 UTC, ZetaTom commented on app/src/main/res/layout/unified_search_item.xml
> +        android:contentDescription="open file actions"
Please replace the hardcoded text with an `R.string` based one. We already have a similar button in `list_item.xml`, called `overflow_menu`, which could be used as a template.

2023-11-29 13:38 UTC, alperozturk96 commented on app/src/main/res/layout/unified_search_item.xml
> +        android:contentDescription="open file actions"
Fixed

2023-11-29 15:51 UTC, JonasMayerDev approved these changes

2023-11-30 06:31 UTC, tobiasKaminsky commented
For me it does not work.
When clicking on "three dots" of a search item, it opens root folder in background.
This looks different in your video, and seems also be working for Jonas.

[Screen_recording_20231130_072915.webm](https://github.com/nextcloud/android/assets/5836855/36a798ab-987c-46e4-8ae9-db75750d86b7)

2023-11-30 08:37 UTC, alperozturk96 commented
> For me it does not work. When clicking on "three dots" of a search item, it opens root folder in background. This looks different in your video, and seems also be working for Jonas.
> 
> EDIT: after reviewing above video, it is the same. So I think this is a bit wrong, as still the search view should be shown. Imagine that an user accidently clicks on "three dots" for wrong file and then needs to search again.

It's same for selecting file. If user tap wrong file needs to search again. So the question has to be asked here are we going to change all search functionality with better selection and showing files action or do we leave the selection process as it is.

Given the current structure of the project, this solution seems appropriate.

2023-11-30 09:50 UTC, alperozturk96 commented
/rebase

2023-12-01 15:19 UTC, alperozturk96 commented
/rebase

2023-12-13 14:00 UTC, JonasMayerDev approved these changes
Works for me :)

2023-12-14 14:18 UTC, merged