Use Work Manager File Download
nextcloud/android pull request #12308
Opened 2023-12-20 11:47 UTC by alperozturk96

- [ ] Tests written, or not not needed

2023-12-21 13:17 UTC, alperozturk96 commented
/rebase

2023-12-21 14:02 UTC, alperozturk96 commented
/rebase

2023-12-22 09:51 UTC, alperozturk96 commented
/rebase

2023-12-26 14:13 UTC, alperozturk96 commented
Only one test is failing - **"download_progress_is_updated[android(AVD) - 8.1.0] FAILED - java.lang.AssertionError: expected:<6> but was:<2>"**

2023-12-27 11:10 UTC, alperozturk96 commented on app/src/main/java/com/nextcloud/client/di/AppComponent.java
> +    void inject(FileDownloadHelper fileDownloadHelper);
Yes its needed for FileDownloadHelper.init {} otherwise backgroundJobManager and uploadsStorageManager can't initialize.

2023-12-27 11:33 UTC, JonasMayerDev requested changes
Synchronizing Folders only downloads one file of the folder not all as expected

2023-12-27 11:33 UTC, JonasMayerDev commented on app/src/main/java/com/nextcloud/client/notifications/download/DownloadNotificationManager.kt
> +            NotificationUtils.cancelWithDelay(
Success notification seems to not be displayed for me?

2023-12-27 11:33 UTC, JonasMayerDev commented on app/src/main/java/com/nextcloud/client/notifications/download/DownloadNotificationManager.kt
> +        notificationManager.notify(SecureRandom().nextInt(), notificationBuilder.build())
Hide old upload progress notification (else the progress of old failed upload will still be displayed)

2023-12-27 12:21 UTC, alperozturk96 commented on app/src/main/java/com/nextcloud/client/notifications/download/DownloadNotificationManager.kt
> +            NotificationUtils.cancelWithDelay(
Its canceling notification not showing success notification.

2023-12-27 14:49 UTC, alperozturk96 commented
@JonasMayerDev Fix Sync

https://github.com/nextcloud/android/assets/67455295/f8b85462-f52e-4eb8-baab-c411560f1be5

2023-12-28 11:57 UTC, JonasMayerDev requested changes
New implemented function "isDownloading" does not the same thing as old one. Maybe reimplement it and make sure it does the same thing. Be careful when changing the functionality of a function to make sure everywhere it is used it is still fitting...

2023-12-28 11:57 UTC, JonasMayerDev commented on app/src/main/java/com/owncloud/android/files/FileMenuFilter.java
>              for (Iterator<OCFile> iterator = files.iterator(); !downloading && iterator.hasNext(); ) {
Loop makes no fence anymore

2023-12-28 11:57 UTC, JonasMayerDev commented on app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
> +        if (!mDownloaderBinder.isDownloading()) {
Edge case: Won't download if any other file is downloaded -> Make isDownloading specific to user and file again?...

2023-12-28 11:57 UTC, JonasMayerDev commented on app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
> +        if (!mDownloaderBinder.isDownloading()) {
Same edge case problem here

2023-12-28 11:57 UTC, JonasMayerDev commented on app/src/main/java/com/owncloud/android/ui/adapter/OCFileListDelegate.kt
> +                fileDownloaderBinder?.isDownloading() == true ||
Is "isDownloading" working? No sync indicator is shown anymore...

2023-12-28 11:59 UTC, JonasMayerDev commented
Maybe it is a better idea to not change the download functionality and switch to chained worker in another pull request to make sure we don't introduce issues with new untested logic...? @alperozturk96

2023-12-28 12:30 UTC, alperozturk96 commented
> Maybe it is a better idea to not change the download functionality and switch to chained worker in another pull request to make sure we don't introduce issues with new untested logic...? @alperozturk96

Chain worker needed for download multiple files and its already included current functionality of FileDownloaderService. Otherwise sync feature will not work. Regarding isDownloading function do we need to pass user and ocfile? Because we can access worker without these two parameter.

2023-12-28 14:23 UTC, alperozturk96 commented
> Maybe it is a better idea to not change the download functionality and switch to chained worker in another pull request to make sure we don't introduce issues with new untested logic...? @alperozturk96

getRequestDownloads() was causing the problem. I fixed it but for future implementation chained worker can be used as well.

2023-12-28 14:24 UTC, alperozturk96 commented
> New implemented function "isDownloading" does not the same thing as old one. Maybe reimplement it and make sure it does the same thing. Be careful when changing the functionality of a function to make sure everywhere it is used it is still fitting...

New function added into BackgroundJobManagerImpl that checks status of the current file. You can test it.

2023-12-28 14:50 UTC, alperozturk96 commented
@JonasMayerDev Sync icon same as master, fyi.

**Master**


https://github.com/nextcloud/android/assets/67455295/ee89d02f-f159-4a66-8f09-b94867beb52f



**PR**

https://github.com/nextcloud/android/assets/67455295/53fc6cd9-f93b-4925-aeb5-d699a94a09fd

2023-12-28 14:57 UTC, JonasMayerDev commented
But the blue sync icon that shows that a download is in progress is only seen on master. You can see it in the video before you go inside the folder

2023-12-28 16:18 UTC, JonasMayerDev requested changes
[Screen_recording_20231228_170425.webm](https://github.com/nextcloud/android/assets/43114340/6a7b76b5-d6fa-45a9-935a-b7094fe9c448)
- Download of folder happens in parallel, which messes with the progress notification.
- Blue sync icon for a folder is only visible for first download
- Sync of a folder can not be stopped

2023-12-29 08:08 UTC, alperozturk96 commented
> Screen_recording_20231228_170425.webm 
> * Download of folder happens in parallel, which messes with the progress notification.
> * Blue sync icon for a folder is only visible for first download
> * Sync of a folder can not be stopped

I am not using chain anymore so it can't be parellel. Can you stop sync on master?

2023-12-29 08:23 UTC, alperozturk96 commented
/rebase

2024-01-02 09:16 UTC, JonasMayerDev commented
Master:
[Screen_recording_20240102_100602.webm](https://github.com/nextcloud/android/assets/43114340/6e8f33c5-2d5a-4415-8e3e-bd0fc6e1672e)
This PR:
[Screen_recording_20240102_100652.webm](https://github.com/nextcloud/android/assets/43114340/f26a5ec1-657d-416e-80e7-43fd296a7396)

- The blue sync icon you can see on master in the right bottom corner of the folder after starting to sync is not there in this PR.
- The Notifications on master show exactly one download at a time (notification has consistent name and progress), in this PR the progress jumps and filename changes, I assume it's because of multiple downloads (possibly because the worker tag is based on the name and therefore two download workers can exist, but I am not sure). 
- Sync of folder could be stopped at any time on master the same way the sync was stared, but in this PR I get the option to sync again?
Hope this clarifies what I mean. Sorry, I try to be more precise and show comparisons in the future :)

2024-01-02 09:18 UTC, JonasMayerDev commented
What do you think about showing the download success notification only when the last download completed? I think it is a bit messy right now when you download a folder. @alperozturk96

2024-01-04 09:08 UTC, alperozturk96 commented
> What do you think about showing the download success notification only when the last download completed? I think it is a bit messy right now when you download a folder. @alperozturk96

Done you can test it :)

2024-01-04 13:46 UTC, JonasMayerDev commented
[Screen_recording_20240104_143757.webm](https://github.com/nextcloud/android/assets/43114340/71d5985a-67df-4997-a82e-98426370c2d1)
Master
[Screen_recording_20240104_143935.webm](https://github.com/nextcloud/android/assets/43114340/ae99b7e8-b7bb-4f7c-9213-20bb50908e50)
This PR

- isDownloading does return true if file is in pending downloads in folder download (When folder is being synced the files do not have the sync symbol)
- Files can not be removed from pending downloads in folder sync
- You can start the same download multiple times -> Multiple upload worker -> Leads to a lot of bugs
|_ Maybe make create worker tag only from user, not from user and file to make sure only one worker is present at a time?

2024-01-04 14:02 UTC, alperozturk96 commented
> [Screen_recording_20240104_143757.webm](https://github.com/nextcloud/android/assets/43114340/71d5985a-67df-4997-a82e-98426370c2d1) Master [Screen_recording_20240104_143935.webm](https://github.com/nextcloud/android/assets/43114340/ae99b7e8-b7bb-4f7c-9213-20bb50908e50) This PR
> 
> * isDownloading does return true if file is in pending downloads in folder download (When folder is being synced the files do not have the sync symbol)
> * Files can not be removed from pending downloads in folder sync
> * You can start the same download multiple times -> Multiple upload worker -> Leads to a lot of bugs
>   |_ Maybe make create worker tag only from user, not from user and file to make sure only one worker is present at a time?

1. I wouldn't expect to see multiple sync icon inside folder because I am syncing folder. Folder might have tons of file and showing a lot of sync icon during sync process doesn't make sense to me.
2. When you can start another worker it will be replaced with previous one. Also, why would the user need to press the sync button more than once? We already show the process with notifications, user can easily track progress.

2024-01-09 13:54 UTC, JonasMayerDev requested changes

2024-01-09 13:54 UTC, JonasMayerDev commented on app/src/main/java/com/nextcloud/client/files/downloader/DownloadNotificationManager.kt
> +            notificationManager.cancelAll()
Maybe not cancel all notifications but only the one that was created with this DownloadNotificationManager else when downloading multiple files all the notifications including the ones from the other downloads will be canceled (and notifications even unrelated to download will be canceled)

2024-01-09 17:08 UTC, JonasMayerDev approved these changes
Seems to be working fine.

2024-01-09 17:09 UTC, JonasMayerDev approved these changes
Seems to be working fine.

2024-01-12 09:11 UTC, merged