Fix auto upload does not start automatically
nextcloud/android pull request #12337
Opened 2024-01-03 12:00 UTC by JonasMayerDev

[Screen_recording_20240103_123529.webm](https://github.com/nextcloud/android/assets/43114340/2a10329f-61bc-452e-abd2-655eec888cdf)
- Add foreground info (also interesting for user) to prevent android killing the worker. (Only visible if worker is active more than ca. 1s -> Use large folder with many files for testing) 

- Make getFileChecksum a lot faster (previously over 1 h for a folder of 6000 Images now only minutes)
![Screenshot_2024-01-02_13-37-46](https://github.com/nextcloud/android/assets/43114340/36ee8696-87c7-4443-89e5-242eb5c4ac73)
Previously 7.5s
![Screenshot_2024-01-02_13-45-05](https://github.com/nextcloud/android/assets/43114340/ffcec165-d28b-4f95-9015-11ad516aed34)
Now 15ms
|_ Should be tested (maybe too good to be true)

For me, it also partly fixes https://github.com/nextcloud/android/issues/12141

- [X] Tests written, or not not needed

2024-01-03 12:13 UTC, JonasMayerDev commented
Just tested my "new" getFileChecksum, and it returns the same result as the old one did for the same file (tested with 1 file), so I guess it should work fine.

2024-01-03 15:19 UTC, alperozturk96 commented
@JonasMayerDev App is crashing here is the log

```
2024-01-03 16:18:47.981 32671-32671 AndroidRuntime          com.nextcloud.client                 E  FATAL EXCEPTION: main
                                                                                                    Process: com.nextcloud.client, PID: 32671
                                                                                                    android.app.InvalidForegroundServiceTypeException: Starting FGS with type none callerApp=ProcessRecord{9752a8e 32671:com.nextcloud.client/u0a217} targetSDK=34 has been prohibited
                                                                                                    	at android.app.InvalidForegroundServiceTypeException$1.createFromParcel(InvalidForegroundServiceTypeException.java:53)
                                                                                                    	at android.app.InvalidForegroundServiceTypeException$1.createFromParcel(InvalidForegroundServiceTypeException.java:49)
                                                                                                    	at android.os.Parcel.readParcelableInternal(Parcel.java:4870)
                                                                                                    	at android.os.Parcel.readParcelable(Parcel.java:4852)
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3052)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3041)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3024)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2966)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6761)
                                                                                                    	at android.app.Service.startForeground(Service.java:862)
                                                                                                    	at androidx.work.impl.foreground.SystemForegroundService$Api31Impl.startForeground(SystemForegroundService.java:194)
                                                                                                    	at androidx.work.impl.foreground.SystemForegroundService$1.run(SystemForegroundService.java:130)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

2024-01-03 15:22 UTC, alperozturk96 requested changes
crash due to `has been prohibited at android.app.InvalidForegroundServiceTypeException.`

You must check implementation on Android 14 emulator. ForegroundServiceHelper may solve this problem

2024-01-04 17:15 UTC, JonasMayerDev commented
@alperozturk96 Do you have a better idea for the manifest.xml entry? I think this is not optimal?

2024-01-05 00:31 UTC, JonasMayerDev commented
OfflineSyncWorker fails with:
```
2024-01-05 00:34:59.185  6463-6511  WM-WorkerWrapper        com.nextcloud.android.beta           E  Work [ id=437a780d-5595-4f0a-8500-bde3a9d007f0, tags={ com.nextcloud.client.jobs.OfflineSyncWork, *, name:periodic_offline_sync, timestamp:1703777647814, class:OfflineSyncWork } ] failed because it threw an exception/error
                                                                                                    java.util.concurrent.ExecutionException: android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service com.nextcloud.android.beta/com.owncloud.android.files.services.FileDownloader
                                                                                                    	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
                                                                                                    	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
                                                                                                    	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:317)
                                                                                                    	at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:920)
                                                                                                    Caused by: android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service com.nextcloud.android.beta/com.owncloud.android.files.services.FileDownloader
                                                                                                    	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
                                                                                                    	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
                                                                                                    	at android.os.Parcel.readParcelable(Parcel.java:3333)
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:2420)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:2409)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2392)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2334)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:5971)
                                                                                                    	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1847)
                                                                                                    	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1823)
                                                                                                    	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:779)
                                                                                                    	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:779)
                                                                                                    	at com.owncloud.android.operations.SynchronizeFileOperation.requestForDownload(SynchronizeFileOperation.java:324)
                                                                                                    	at com.owncloud.android.operations.SynchronizeFileOperation.run(SynchronizeFileOperation.java:250)
                                                                                                    	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:144)
                                                                                                    	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:153)
                                                                                                    	at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:64)
                                                                                                    	at com.nextcloud.client.jobs.OfflineSyncWork.recursive(OfflineSyncWork.kt:93)
                                                                                                    	at com.nextcloud.client.jobs.OfflineSyncWork.recursive(OfflineSyncWork.kt:100)
                                                                                                    	at com.nextcloud.client.jobs.OfflineSyncWork.doWork(OfflineSyncWork.kt:64)
                                                                                                    	at androidx.work.Worker$1.run(Worker.java:82)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                                                                                                    	at java.lang.Thread.run(Thread.java:920) 
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.am.ActiveServices.startServiceLocked(ActiveServices.java:691)
                                                                                                    	at com.android.server.am.ActiveServices.startServiceLocked(ActiveServices.java:616)
                                                                                                    	at com.android.server.am.ActivityManagerService.startService(ActivityManagerService.java:11839)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2519)
                                                                                                    	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2498)```
Need to test if that's also the case on master or if it is related to my changes...

2024-01-08 09:40 UTC, ZetaTom commented on app/src/main/java/com/owncloud/android/datamodel/FilesystemDataProvider.java
>              }
As far as I can tell, the new implementation should perform the same operation as the old one.

Please re-format these lines using the auto-formatter.

2024-01-09 07:53 UTC, ZetaTom reviewed
I've given this PR a quick test run and have encountered the following exception:

<details><summary>Logcat</summary>
<p>

```
WM-Processor            I  Moving WorkSpec (29319770-c67b-40c5-bf9e-84dc3f2ac140) to the foreground
UploadsStorageManager   D  QUERY: (status== ? OR last_result==9 OR last_result==13 OR last_result==11 OR last_result==14 ) AND last_result!= 16 ROWID: -1
WM-SystemFgDispatcher   I  Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=com.nextcloud.client/androidx.work.impl.foreground.SystemForegroundService (has extras) }
MediaProvider           D  Reading images for DCIM
UploadsStorageManager   V  getUploads() got 0 rows from page 0, 0 rows total so far, last ID -1
UploadsStorageManager   V  getUploads() returning 0 (0) rows after reading 1 pages
UploadsStorageManager   D  QUERY: (status== ? OR last_result==9 OR last_result==13 OR last_result==11 OR last_result==14 ) AND last_result!= 16 ROWID: -1
UploadsStorageManager   V  getUploads() got 0 rows from page 0, 0 rows total so far, last ID -1
UploadsStorageManager   V  getUploads() returning 0 (0) rows after reading 1 pages
WM-Processor            I  Moving WorkSpec (29319770-c67b-40c5-bf9e-84dc3f2ac140) to the foreground
WM-Processor            I  Moving WorkSpec (29319770-c67b-40c5-bf9e-84dc3f2ac140) to the foreground
WM-WorkerWrapper        E  Work [ id=2f00d1e0-c91b-40e6-8524-501dffca5e18, tags={ com.nextcloud.client.jobs.MediaFoldersDetectionWork, *, name:immediate_media_folder_detection, timestamp:1704785714230, class:MediaFoldersDetectionWork } ] failed because it threw an exception/error
                           java.util.concurrent.ExecutionException: android.database.CursorIndexOutOfBoundsException: Index -1 requested, with a size of 1 
                                at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
                                at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
                                at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:317)
                                at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                at java.lang.Thread.run(Thread.java:1012)
                           Caused by: android.database.CursorIndexOutOfBoundsException: Index -1 requested, with a size of 1 
                                at android.database.AbstractCursor.checkPosition(AbstractCursor.java:521)
                                at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:139)
                                at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:77)
                                at android.database.CursorWrapper.getLong(CursorWrapper.java:131)
                                at com.owncloud.android.datamodel.SyncedFolderProvider.createSyncedFolderFromCursor(SyncedFolderProvider.java:346)
                                at com.owncloud.android.datamodel.SyncedFolderProvider.findByLocalPathAndAccount(SyncedFolderProvider.java:208)
                                at com.nextcloud.client.jobs.MediaFoldersDetectionWork.doWork(MediaFoldersDetectionWork.kt:154)
                                at androidx.work.Worker$1.run(Worker.java:82)
                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
                                at java.lang.Thread.run(Thread.java:1012)  
WM-WorkerWrapper        I  Worker result FAILURE for Work [ id=2f00d1e0-c91b-40e6-8524-501dffca5e18, tags={ com.nextcloud.client.jobs.MediaFoldersDetectionWork, *, name:immediate_media_folder_detection, timestamp:1704785714230, class:MediaFoldersDetectionWork } ]
WM-Processor            I  Moving WorkSpec (29319770-c67b-40c5-bf9e-84dc3f2ac140) to the foreground
WM-WorkerWrapper        I  Worker result SUCCESS for Work [ id=29319770-c67b-40c5-bf9e-84dc3f2ac140, tags={ com.nextcloud.client.jobs.FilesSyncWork, *, name:immediate_files_sync, timestamp:1704785714229, class:FilesSyncWork } ]
WM-SystemFgDispatcher   I  Stopping foreground service
```

</p>
</details> 

This occurred after I moved a 1GB test file into the specified auto-upload directory. At first glance this looks to be another issue, that doesn't stem from this change.

Later on, I've tried again, renaming the test file and got the following log entries:

<details><summary>Logcat</summary>
<p>

```
WM-WorkerWrapper        I  Work [ id=c9bd3090-e9fe-4f4b-bc37-95dc04b3144c, tags={ com.nextcloud.client.jobs.ContentObserverWork, *, name:content_observer, timestamp:1704785714230, class:ContentObserverWork } ] was cancelled
                           java.util.concurrent.CancellationException: Task was cancelled.
                                at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1184)
                                at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:514)
                                at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
                                at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:317)
                                at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                at java.lang.Thread.run(Thread.java:1012)
MediaProvider           D  Reading images for DCIM
WM-WorkerWrapper        I  Worker result SUCCESS for Work [ id=8f23593d-5431-4981-a960-39f82e604679, tags={ com.nextcloud.client.jobs.MediaFoldersDetectionWork, *, name:immediate_media_folder_detection, timestamp:1704786164352, class:MediaFoldersDetectionWork } ]
WM-Processor            I  Moving WorkSpec (381138c2-92f5-44a4-b84d-5eff98203d3a) to the foreground
WM-SystemFgDispatcher   I  Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=com.nextcloud.client/androidx.work.impl.foreground.SystemForegroundService (has extras) }
UploadsStorageManager   D  QUERY: (status== ? OR last_result==9 OR last_result==13 OR last_result==11 OR last_result==14 ) AND last_result!= 16 ROWID: -1
UploadsStorageManager   V  getUploads() got 0 rows from page 0, 0 rows total so far, last ID -1
UploadsStorageManager   V  getUploads() returning 0 (0) rows after reading 1 pages
UploadsStorageManager   D  QUERY: (status== ? OR last_result==9 OR last_result==13 OR last_result==11 OR last_result==14 ) AND last_result!= 16 ROWID: -1
UploadsStorageManager   V  getUploads() got 0 rows from page 0, 0 rows total so far, last ID -1
UploadsStorageManager   V  getUploads() returning 0 (0) rows after reading 1 pages
WM-Processor            I  Moving WorkSpec (381138c2-92f5-44a4-b84d-5eff98203d3a) to the foreground
WM-Processor            I  Moving WorkSpec (381138c2-92f5-44a4-b84d-5eff98203d3a) to the foreground
WM-Processor            I  Moving WorkSpec (381138c2-92f5-44a4-b84d-5eff98203d3a) to the foreground
UploadsStorageManager   V  Inserting 1 uploads
FileContentProvider     D  applying batch in provider com.owncloud.android.providers.FileContentProvider@8486d7d (temporary: false)
FileContentProvider     D  applied batch in provider com.owncloud.android.providers.FileContentProvider@8486d7d
UploadsStorageManager   D  notifyObserversNow
WM-WorkerWrapper        I  Wor [...]

2024-01-09 15:41 UTC, JonasMayerDev commented
@ZetaTom I am not entirely sure but as you said I can not imagine how these fails are caused by this pr... Could you maybe do the exact same thing on master and see if it works there? And if you have time test again in this PR to see if it is a reliably reproducible issue for you?

2024-01-10 13:53 UTC, ZetaTom approved these changes
After some trial and error, I think there's either something wrong with my local instance or it's also happening on master. Either way, this PR doesn't seem to directly affect this behaviour.

2024-01-11 08:10 UTC, alperozturk96 approved these changes

2024-01-11 08:10 UTC, merged

2024-01-17 14:32 UTC, JonasMayerDev commented
/backport to stable-3.27