Make sure only one sync job is running at a time
nextcloud/android pull request #12372
Opened 2024-01-15 14:58 UTC by JonasMayerDev

Before running sync worker, check if another sync worker is already running.
Before in theory 2 sync jobs could run and potentially mess with each other (maybe leads to https://github.com/nextcloud/android/issues/11974)

- [X] Tests written, or not not needed

2024-01-29 13:09 UTC, ZetaTom approved these changes
In my brief testing everything worked as expected. Although I didn't check any edge cases (what happens when a worker is stuck, for example). This might be out of scope for this pull request.

The suggestions are just a minor change and, in reality, just eye candy.

2024-01-29 14:31 UTC, JonasMayerDev commented on app/src/main/java/com/nextcloud/utils/extensions/WorkManagerExtensions.kt
> +    return running
Thanks, I have replaced 2 for loops with your solution :)

2024-04-09 15:11 UTC, JonasMayerDev commented
Problem: With current implementation when periodic sync worker is started and immediate filesync is already running because of changed files it will skip periodic sync which is not intended... But it is really unlikely since immediate file sync with changed files should only run for under 1 sec.

2024-04-26 06:55 UTC, alperozturk96 requested changes
We can get rid of repeated codes in WorkManagerExtensions with this code.

```
private const val TAG = "WorkManager"

fun WorkManager.isWorkRunning(tag: String): Boolean = checkWork(tag, listOf(WorkInfo.State.RUNNING))

fun WorkManager.isWorkScheduled(tag: String): Boolean =
    checkWork(tag, listOf(WorkInfo.State.RUNNING, WorkInfo.State.ENQUEUED))

private fun WorkManager.checkWork(tag: String, stateConditions: List<WorkInfo.State>): Boolean {
    val statuses: ListenableFuture<List<WorkInfo>> = getWorkInfosByTag(tag)
    var workInfoList: List<WorkInfo> = emptyList()

    try {
        workInfoList = statuses.get()
    } catch (e: ExecutionException) {
        Log_OC.d(TAG, "ExecutionException in checkWork: $e")
    } catch (e: InterruptedException) {
        Log_OC.d(TAG, "InterruptedException in checkWork: $e")
    }

    return workInfoList.any { workInfo -> stateConditions.contains(workInfo.state) }
}

```

2024-05-03 11:29 UTC, alperozturk96 approved these changes
Tested didn't came across with any regression

2024-05-03 11:53 UTC, merged