Add global upload pause button
nextcloud/android pull request #12527
Opened 2024-02-09 20:54 UTC by JonasMayerDev

- [ ] Tests written, or not not needed

2024-02-12 12:23 UTC, alperozturk96 requested changes

2024-02-12 12:23 UTC, alperozturk96 commented on app/src/main/java/com/nextcloud/client/jobs/upload/FileUploaderIntents.kt
> +            operation?.file,
Why you are passing optinal operation? Do we need this function for pause uploads?

You can check existance of optional operation if its null just return null PendingIntent.

2024-02-12 12:23 UTC, alperozturk96 commented on app/src/main/java/com/nextcloud/client/jobs/upload/UploadNotificationManager.kt
> +        notificationBuilder = NotificationUtils.newNotificationBuilder(context, viewThemeUtils).apply {
Why you are recreating notificationBuilder? You can simply change current message or dismiss all previous message and show a new message.

2024-02-12 12:23 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
> +        if (menu.getItem(0).getItemId() == R.id.action_toggle_global_pause){
You can extract this big if block into the another function. Also if user don't have any upload progress no need to show any icon. Only show paused/resume icon if user have ongoing upload process.

No need to repeat  menu.getItem(0).setIcon, menu.getItem(0).setTitle functions. You can create two variable e.g String uploadStateTitle and Int uploadStateIcon then inside if else block assign correct values then only one time call menu.getItem(0)... functions

2024-02-12 12:23 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
> +            preferences.setGlobalUploadPaused(!preferences.getGlobalUploadPaused());
Could you move that else if block into the another function?

2024-02-12 12:23 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/adapter/UploadListAdapter.java
> +                    popup = new PopupMenu(MainApp.getAppContext(), headerViewHolder.binding.uploadListAction);
Same here you can extract PopupMenu into the another function.

2024-02-12 14:15 UTC, JonasMayerDev commented on app/src/main/java/com/nextcloud/client/jobs/upload/UploadNotificationManager.kt
> +        notificationBuilder = NotificationUtils.newNotificationBuilder(context, viewThemeUtils).apply {
You are right. I now also reuse notificationBuilder in prepareForStart, please check if my changes are ok!

2024-02-12 14:20 UTC, JonasMayerDev commented on app/src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
> +        if (menu.getItem(0).getItemId() == R.id.action_toggle_global_pause){
I think it makes sense to show the pause button even if not upload is in progress since the idea is also to prevent future uploads e.g. trough auto upload when for example in bad Wi-Fi. So it is important that the user can at any time deactivate the upload, even for future uploads.

Thanks for the improvement ideas!

2024-02-12 16:02 UTC, alperozturk96 approved these changes
Refactored, tested working on Android 14 Emulator

2024-02-13 08:31 UTC, alperozturk96 requested changes

2024-02-13 12:57 UTC, JonasMayerDev commented on app/src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
> +        return true;
Good catch, thank you!

2024-02-13 13:36 UTC, alperozturk96 approved these changes

2024-02-13 22:50 UTC, merged