Bugfix editing folder description
nextcloud/android pull request #12752
Opened 2024-03-27 18:04 UTC by JonasMayerDev

Before editing of folder description using readme.md files would lead to error message.
With this PR editing works.

[Screen_recording_20240327_190105.webm](https://github.com/nextcloud/android/assets/43114340/a7bb1435-e9ec-4bf3-b016-e9f7b2c29b5d)

Known Issue:
Folder README will only be updated when manually refreshing. 

- [X] Tests written, or not not needed

2024-03-28 07:47 UTC, alperozturk96 requested changes
You can use LocalBroadcastManager to trigger refresh automatically.

GalleryFragment.#L113 -> sample usage

2024-03-28 12:54 UTC, alperozturk96 approved these changes
tested working

2024-04-02 10:13 UTC, JonasMayerDev commented
Approved by Alper

2024-04-03 07:51 UTC, merged

2024-04-03 08:04 UTC, ZetaTom reviewed
This changes fixes the issue at hand but also introduces a new undesirable behaviour where the user is unable to return to the normal file view.

2024-04-03 08:04 UTC, ZetaTom commented on app/src/main/java/com/owncloud/android/ui/preview/PreviewTextStringFragment.java
> +            fileDisplayActivity.getSupportFragmentManager().popBackStack();
This line causes an issue when the editor is opened from an active search. I've been able to reproduce the issue using the following steps:

1. Open any folder (excl. root directory) containing a `README.md`
2. Select preview at top of folder
3. Open text search using icon on top right
4. Enter some text
5. Enter edit mode using FAB
6. Exit back out of editor

Now one is unable to return to the normal files view.

Given all of this, I'm unsure how severe this issue really is.

2024-04-03 11:49 UTC, JonasMayerDev commented on app/src/main/java/com/owncloud/android/ui/preview/PreviewTextStringFragment.java
> +            fileDisplayActivity.getSupportFragmentManager().popBackStack();
Yes, good catch. I created an Issue https://github.com/nextcloud/android/issues/12805. I work on it when I have time, but right now I would not prioritize it...