Fix upload download problems
nextcloud/android pull request #12794
Opened 2024-04-02 08:53 UTC by JonasMayerDev

**By Alper**
This PR Fixes Following Problems

Sync icon visibility during download
Accessing after download attempt to etag throws null point exception
Remove file dialog actions order is wrong for downloaded and normal file
File download
Note

The Spotbugs count increased due to the reintroduction of old code (with improvements) in this PR.

- [X] Tests written, or not not needed

2024-04-02 11:45 UTC, tobiasKaminsky commented
Can you either suppress spotbugs, or manually increase count, so that CI is green?

2024-04-02 21:57 UTC, AndyScherzinger commented
/backport to stable-3.28

2024-04-03 08:36 UTC, ZetaTom requested changes
Downloading and uploading worked flawlessly in my tests.

Please address my comment on `FileDownloadHelper`.

2024-04-03 08:36 UTC, ZetaTom commented on app/src/main/java/com/nextcloud/client/jobs/OfflineSyncWork.kt
> +        }
`Log_OC.d()` should be able to handle `null` values, shouldn't it?

```suggestion
        Log_OC.d(TAG, "$folderName: currentEtag: ${ocFolder.etag}")
```

2024-04-03 08:36 UTC, ZetaTom commented on app/src/main/java/com/nextcloud/client/jobs/download/FileDownloadHelper.kt
> +            backgroundJobManager.isStartFileDownloadJobScheduled(user, topParentId)
Shouldn't `isJobScheduled` be joined onto line 54 (inside the `if` branch) instead of line 53? Was this change made on purpose?
Otherwise this could change the return value of `isDownloading()`.

2024-04-04 07:11 UTC, tobiasKaminsky approved these changes

2024-04-04 07:25 UTC, merged