Add visual hint to collapsible headers in uploads tab
nextcloud/android pull request #12847
Opened 2024-04-09 09:28 UTC by JonasMayerDev

The dividers / headers in the upload tab are collapsible, but I think it is missing a visual hint that it is.

The fact that I only found out about that feature after countless hours in that view underlines my point :)

![Screenshot_2024-04-09-11-25-17-06_367f977887f4a5f4712ef04f9b973e21](https://github.com/nextcloud/android/assets/43114340/145ba51a-587f-48da-a1d6-ab1ca283977d)
Current design

![Screenshot_2024-04-09-11-18-53-22_06ea656a9ba653ff96746f477f32d0f9](https://github.com/nextcloud/android/assets/43114340/a41944d1-e114-464a-bd49-dc59167d0c50)
I just quickly added an icon for it

@nextcloud/designers what do you think? Is that icon ok?
(TODO: Color in dark theme, better alignment)
 

- [X] Tests written, or not not needed

2024-05-23 17:45 UTC, JonasMayerDev commented
Does anyone know if that change in the license header is the right procedure when modifying the material icon? @alperozturk96 @tobiasKaminsky @ZetaTom

2024-05-24 02:06 UTC, nimishavijay requested changes
Definitely an improvement, great catch! One small nitpick about alignment: the arrow could be center-aligned with the file icons, and the text ("Aktuell (5)", "Hochgeladen (5)") could be left aligned with the file names :)

2024-05-24 08:22 UTC, alperozturk96 approved these changes

2024-05-29 06:59 UTC, marcoambrosini approved these changes

2024-05-29 07:03 UTC, AndyScherzinger approved these changes

2024-05-29 17:55 UTC, merged