Unify Notifications
nextcloud/android pull request #12907
Opened 2024-04-19 13:47 UTC by alperozturk96

- [ ] Tests written, or not not needed

**Improvements**

+ All notifications are dismissible. Some user have issue with stucked notifications.

+ One notification used for downloads and uploads. Instead of showing progress with one by one now we can show all progress with one notifications such as 1 / 10 abc.rtf …

**How to Test**

+ Test one file download

+ Test one file upload

+ Test multiple file upload

+ Test multiple file download

+ Test all above scenarios for e2e

2024-05-07 09:26 UTC, ZetaTom requested changes
In general these changes seem to work and not break anything.

Please revert any changes made to `app/src/main/res/values-*/strings.xml` as these files are managed via transifex.

2024-05-07 09:26 UTC, ZetaTom commented on app/src/main/java/com/nextcloud/client/jobs/upload/UploadNotificationManager.kt
>      ) {
The function `prepareForStart()` is called by `FileUploadWorker#uploadFiles()`, which is in turn called from `FileUploadWorker#retrievePagesBySortingUploadsByID()`. This function queries the database for pending uploads using `UploadsStorageManager#getCurrentAndPendingUploadsForAccountPageAscById()`.

Because of `QUERY_PAGE_SIZE = 100`, `totalUploadSize` will never exceed 100. Even if one uploads a large folder containing several hundred files.

All of this results in the notification *always* displaying *n / 100 - filename.ext*.

2024-05-07 12:19 UTC, AndyScherzinger commented on app/src/main/res/values/strings.xml
> +    <string name="upload_notification_manager_start_text" translatable="false">%1$d / %2$d - %3$s</string>
It won't be added on transifex, text within the UI element will be right aligned, nothing else. Hence the text block will be right aligned while the information in its order ir ltr sorted.

Hence it makes sense to make it translatable even thought it won't differ in its from except for RTL / LTR

2024-05-28 08:50 UTC, alperozturk96 commented on app/src/main/java/com/nextcloud/client/jobs/upload/FileUploadWorker.kt
> +                    return@uploads
It was break before, return will exit the entire method so logic is changing.

2024-05-28 09:07 UTC, alperozturk96 commented on app/src/main/java/com/nextcloud/client/jobs/upload/FileUploadWorker.kt
> +                notificationManager.dismissWorkerNotifications()
I guess this logic left over from the foreground service. I tested without calling this function, seems like okay.

2024-05-28 09:31 UTC, ZetaTom commented on app/src/main/java/com/nextcloud/client/jobs/upload/FileUploadWorker.kt
> +                    return@uploads
If we are just doing code cleanup in this pull request, we should move this change to another pull request of a different nature.

This `run` or `for` statement is the last statement of `uploadFiles`. It should not matter if we use `return` or `break` here because the function will return right after the loop even if we use `break`.

<details><summary>Consider the following code snippets:</summary>
<p>

```kotlin
fun original(list: List<Int>) {
    for (i in list) {
        if (i == 2) {
            break
        }
        println(i)
    }
}

fun proposed(list: List<Int>) {
    run uploads@{
        list.forEachIndexed { index, i ->
            if (i == 2) {
                return@uploads
            }
            println(i)
        }
    }
}

fun suggested(list: List<Int>) {
    list.forEachIndexed { index, i ->
        if (i == 2) {
            return
        }
        println(i)
    }
}
```

All of them perform the same operation. They are functionally equivalent. And if they are equivalent, we are free to choose any one of them. Now that we are substituting the `for` loop with a `forEach` loop, we might as well leave out the `run` statement.

We should check the logic nonetheless, even if we are sure that the functions perform equivalent actions.

</p>
</details>

2024-05-28 09:45 UTC, alperozturk96 commented on app/src/main/java/com/nextcloud/client/jobs/upload/UploadNotificationManager.kt
>      ) {
Solved with https://github.com/nextcloud/android/pull/12907/commits/7a772d2398ee51f1369eb5a7e3b00b5187ba14e4

2024-05-28 09:48 UTC, alperozturk96 commented on app/src/main/res/values/strings.xml
> +    <string name="upload_notification_manager_start_text" translatable="false">%1$d / %2$d - %3$s</string>
https://github.com/nextcloud/android/pull/12907/commits/9e3610928149f15fd6dc53b60d352afa5e03788a

2024-06-03 09:10 UTC, AndyScherzinger approved these changes

2024-06-03 10:32 UTC, merged