Added upload from video camera #7358
nextcloud/android pull request #12995
Opened 2024-05-09 14:09 UTC by timedin-de

Regarding feature request #7358
- Adding Option to directly upload a video
- If camera permissions are not already granted, it will ask if for video or image after granting (its seems not not to be possible to get the camera-action after the permission request)
-  It seems that the videointent doesn't work on emulator? Tested with real GooglePixel 6a

- [ ] Tests written, or not not needed

2024-05-13 10:44 UTC, alperozturk96 requested changes
I try to upload video directly on Android 14 emulator, after completing video shooting upload didn't work. The video file didn't upload.

After my second attempt, the app is crashed. Logcat didn't show any crash log for nextcloud package and general android

2024-05-14 07:39 UTC, timedin-de commented
> Thanks for the contribution.
> 
> I try to upload video directly on Android 14 emulator, after completing video shooting upload didn't work. The video file didn't upload.
> 
> After my second attempt, the app is crashed. Logcat didn't show any crash log for nextcloud package and general android
> 
> Could you test via Android 14 emulator and share your findings with us?

Thanks for testing, thats what i meant with "It seems that the videointent doesn't work on emulator?", I tried countless times using the videointent on an emulator and it crashes or exits. I currently have no idea why this happens. On a hardware device it just works... (i was unsure if it was maybe just my underpowered laptop, but this ensures the bug)

I'll try some tests with only video intents on emulator to check for the issue.

2024-05-21 10:20 UTC, timedin-de commented
Hey, I'm sorry, but I currently don't have the time (and motivation) to further check on this issue in the emulator. Maybe someone else finds the problem, or just discard the PR?

2024-05-21 12:25 UTC, alperozturk96 commented
> Hey, I'm sorry, but I currently don't have the time (and motivation) to further check on this issue in the emulator. Maybe someone else finds the problem, or just discard the PR?

I'll check it. Thank you for your contribution; it's wonderful to see support from the community 👍

2024-05-21 14:05 UTC, JonasMayerDev commented
For me, the PR seems to work on real device (One Plus running Android 12).

2024-05-21 14:14 UTC, JonasMayerDev commented
What do you think of not having 2 different uploads from camera in the Dialog Fragment but just one and then showing the user the dialog that's currently shown when accepting the permissions with the options video and image? I think the DialogFragment is already a little crowded, and it would make the experience a little more consistent since the dialog is currently only shown once regardless if "upload from camera" or "upload from video camera" is clicked...

@alperozturk96 @timedin-de What do you think?

2024-05-22 09:06 UTC, timedin-de commented
> @timedin-de What do you think?

Yep I could do it this way if you agree on it.
It would mean one more click to open the camera, but i think would cause less confusion, (especially the current additional prompt after the permission granting). 
 
I chose the current approach because of the comment in the issue
_by @joshtrichards in https://github.com/nextcloud/android/issues/7358#issuecomment-1755486359_

2024-05-22 11:16 UTC, JonasMayerDev commented
@timedin-de thank you! I guess the best persons to decide on that is the design team @nextcloud/designers 
To summarize for them:

Option 1 for adding a "capture video" implementation would look something like this:

![image](https://github.com/nextcloud/android/assets/43114340/1ee77e8a-4dfe-403d-bf55-548f56d79e90)

Pro: One click video capture
Con: Too crowded dialog when clicking plus button, Inconsistent since dialog from option 2 would still show once when accepting video permissions.

Option 2 would look something like this:

![Screenshot_2024-05-21-15-59-40-98_06ea656a9ba653ff96746f477f32d0f9](https://github.com/nextcloud/android/assets/43114340/ae3c162b-621a-4c65-867c-4dec5541b407)

Pro: Consistent, less crowded
Con: 2 Clicks for video capture

2024-05-22 14:39 UTC, timedin-de commented
> Honestly I dont unterstand what is the difference between upload from camera and upload from video camera?

On Android when a camera gets started it needs to be specified if it should record a video or take a picture (you cant decide/change it inside of the camera preview).

So "video camera" starts in video-recording-mode, "camera" in photo-mode

2024-05-22 18:19 UTC, JonasMayerDev commented
@szaimen Yes good point. But the question is if we should use 2 separate buttons (video and image) when clicking on the plus in the app. Or if we combine it in one button and the ask the user in a dialog if wants video or image. Take a look at my message for the pro and cons in my opinion. https://github.com/nextcloud/android/pull/12995#issuecomment-2124541988

2024-05-28 14:24 UTC, szaimen commented
I would probably indeed combine these two things into one option:
`Take photo or video and upload` and keep using the camera icon.

Then if clicking on that, indeed open a popup and ask this question but put the photo button to the right as it is more likely that you want to take a photo imho.

2024-05-28 17:15 UTC, timedin-de commented
Ok I left it on "Upload from camera".

For implementation I moved the permissons-code from `FileOperationsHelper` to `OCFileListFragment`, I thought the dialog should be part of the Fragment not the FileHelper. Hit me up if I should change it.

2024-05-28 17:17 UTC, timedin-de commented on app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
> +                    getOCFileListFragmentFromFile().directCameraUpload();
displaying the dialog in OCFileListFragment

2024-05-28 17:18 UTC, timedin-de commented on app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
> +                            DisplayUtils.showSnackMessage(getActivity(), R.string.error_uploading_direct_camera_upload);
not regarding the video-upload itself, small improvement

2024-05-28 17:18 UTC, timedin-de commented on app/src/main/java/com/owncloud/android/ui/fragment/OCFileListBottomSheetDialog.java
> +        viewThemeUtils.platform.colorImageView(binding.menuIconAddFolderInfo, ColorRole.PRIMARY);
Not regarding video upload. Fixing Deprecation

2024-06-17 15:49 UTC, JonasMayerDev approved these changes
Works for me on OnePlus Nord 2 and code looks good to me.

2024-06-18 07:14 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
> +        if(isVideo) {
```suggestion
        if (isVideo) {
```

2024-06-18 07:32 UTC, alperozturk96 commented
Thanks for the PR and contribution.

I just did some small refactoring and add FIXME note for uploading video from emulator. I can't push commit for this branch because it's not branched out from our master branch.

Could you please apply this git patch? Then we can merge it.

[refactor.patch](https://github.com/user-attachments/files/15882070/refactor.patch)

2024-06-18 08:42 UTC, timedin-de commented
@alperozturk96 Thank you for your work and time.

Until now i haven't worked with patches, when i just apply it I get an error. Should I just undo my commit, apply the patch (with `git apply refactor.patch` or `git am < refactor.patch` and force-push or should i apply the patch on another branch (without my commit) and create a merge to the fork-master branch. 

And how do I have to handle signing off.

2024-06-18 11:59 UTC, JonasMayerDev commented
@timedin-de not 100% sure but I would suggest number 1 ("remove your commits and add them via the patch back") since the patch seems to contain all changes you made compared to master. You can sign your commit with -S so eg. git commit -S -m "message" after you applied the patch

2024-06-19 08:27 UTC, alperozturk96 approved these changes

2024-06-19 10:13 UTC, merged