Use DI if getStorageManager is null
nextcloud/android pull request #13074
Opened 2024-06-06 08:17 UTC by alperozturk96

- [ ] Tests written, or not not needed

2024-06-06 11:56 UTC, tobiasKaminsky commented
Hm. DI uses CurrentAccountProvider.
SessionMixin uses UserAccountManager, which extends from CurrentAccountProvider.

So I guess it is okay to use them.

But the real fix would be to find out why it is null in first place.
Else app might then bail out on next NPE inside SessionMixin.

Can you see a bit more of stracktrace to guess when this might happen?

2024-06-06 12:13 UTC, alperozturk96 commented
> Hm. DI uses CurrentAccountProvider. SessionMixin uses UserAccountManager, which extends from CurrentAccountProvider.
> 
> So I guess it is okay to use them.
> 
> But the real fix would be to find out why it is null in first place. Else app might then bail out on next NPE inside SessionMixin.
> 
> Can you see a bit more of stracktrace to guess when this might happen?

```
fun setAccount(account: Account?) {
        val validAccount = account != null && accountManager.setCurrentOwnCloudAccount(account.name)
        if (validAccount) {
            currentAccount = account
        } else {
            swapToDefaultAccount()
        }

        currentAccount?.let {
            val storageManager = FileDataStorageManager(getUser().get(), contentResolver)
            this.storageManager = storageManager
        }
    }
```

This function set the storage manager inside SessionMixin passed parameter can be null so currentAccount become a null.

2024-06-11 07:49 UTC, ZetaTom requested changes

2024-06-11 07:49 UTC, ZetaTom commented on app/src/main/java/com/nextcloud/client/mixins/SessionMixin.kt
> +    private fun getDefaultAccount(): Account {
In my opinion this function should be inlined or the comment adjusted appropriately.

2024-06-11 07:49 UTC, ZetaTom commented on app/src/main/java/com/nextcloud/client/mixins/SessionMixin.kt
> +            getDefaultAccount()
Previously, when calling `swapToDefaultAccount()`, this set some internal variables and cause `startAccountCreation()` to be called in certain circumstances. Given that this function has been refactored to a single `return`, the effect on this line will need to be investigated.

2024-06-11 08:01 UTC, alperozturk96 commented on app/src/main/java/com/nextcloud/client/mixins/SessionMixin.kt
> +    private fun getDefaultAccount(): Account {
https://github.com/nextcloud/android/pull/13074/commits/3872a6f8ef3e4025164062e9ab8da5c1ebbdbbc8

2024-06-11 08:15 UTC, alperozturk96 commented
/rebase

2024-06-11 08:16 UTC, ZetaTom requested changes
On my test device the app crashes on the first launch after a fresh install.

<details><summary>Logcat</summary>
<p>

```
FATAL EXCEPTION: main
Process: com.nextcloud.client, PID: 4224
java.lang.RuntimeException: Unable to create application com.owncloud.android.MainApp: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
        at com.nextcloud.client.account.UserAccountManagerImpl.getCurrentAccount(UserAccountManagerImpl.java:157)
        at com.nextcloud.client.account.UserAccountManagerImpl.getUser(UserAccountManagerImpl.java:225) 
        at com.owncloud.android.utils.theme.MaterialSchemesProviderImpl.getMaterialSchemesForCurrentUser(MaterialSchemesProviderImpl.kt:48)
        at com.nextcloud.client.di.ThemeModule$Companion.provideMaterialSchemes(ThemeModule.kt:42)
        at com.nextcloud.client.di.ThemeModule_Companion_ProvideMaterialSchemesFactory.provideMaterialSchemes(ThemeModule_Companion_ProvideMaterialSchemesFactory.java:47)
        at com.nextcloud.client.di.ThemeModule_Companion_ProvideMaterialSchemesFactory.get(ThemeModule_Companion_ProvideMaterialSchemesFactory.java:37)
        at com.nextcloud.client.di.ThemeModule_Companion_ProvideMaterialSchemesFactory.get(ThemeModule_Companion_ProvideMaterialSchemesFactory.java:13)
        at com.owncloud.android.utils.theme.ViewThemeUtils_Factory.get(ViewThemeUtils_Factory.java:39)  
        at com.owncloud.android.utils.theme.ViewThemeUtils_Factory.get(ViewThemeUtils_Factory.java:12)  
        at com.owncloud.android.MainApp.onCreate(MainApp.java:301)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

</p>
</details>

2024-06-11 12:22 UTC, alperozturk96 commented
> UserAccountManagerImpl

AnonymousAccount logic added for fresh install.

2024-06-12 06:40 UTC, tobiasKaminsky commented
> test-Unit test failed: https://www.kaminsky.me/nc-dev/android-integrationTests/13074-Unit-test-15-03

@alperozturk96 this seems to be related to your changes.

2024-06-12 06:41 UTC, tobiasKaminsky commented
Have you tested multiple accounts?

2024-06-12 07:26 UTC, alperozturk96 commented
> > test-Unit test failed: https://www.kaminsky.me/nc-dev/android-integrationTests/13074-Unit-test-15-03
> 
> @alperozturk96 this seems to be related to your changes.

This test is not valid anymore. Account can't be null so I removed the test.

2024-06-13 13:42 UTC, tobiasKaminsky approved these changes

2024-06-13 13:42 UTC, merged

2024-06-13 15:48 UTC, alperozturk96 commented
/backport to stable-3.29