Bug-Fix Percentage Value During Download or Upload
nextcloud/android pull request #13145
Opened 2024-06-17 14:09 UTC by alperozturk96

- [ ] Tests written, or not not needed

2024-06-18 11:35 UTC, JonasMayerDev requested changes

2024-06-18 11:35 UTC, JonasMayerDev commented on app/src/main/java/com/nextcloud/utils/extensions/OnDataTransferProgressListenerExtensions.kt
> + * SPDX-FileCopyrightText: 2024 Your Name <your@email.com>
Add your name :)

2024-06-18 13:00 UTC, alperozturk96 commented on app/src/main/java/com/nextcloud/utils/extensions/OnDataTransferProgressListenerExtensions.kt
> + * SPDX-FileCopyrightText: 2024 Your Name <your@email.com>
I'm always changing Copyright from Android Studio but still not applying it correctly, thanks for the review.

2024-06-18 13:32 UTC, JonasMayerDev approved these changes
Could not reproduce bug but works for me and code looks good.

2024-06-19 08:07 UTC, AndyScherzinger approved these changes

2024-06-19 08:07 UTC, merged