fix for media tab not showing thumbnails when image not in cache manager
nextcloud/android pull request #13158
Opened 2024-06-20 12:39 UTC by camillo-positano

[x] Tests written, or not not needed

Hello i've had this issue for a long time and wanted to fix it.

The problem i found was that the cache manager never requested the server for a thumbnail because the condition to do so was never true. This caused that all my remote photos thumbnails were the default thumbnail image.

From what i understand if there is not a preview but there is a remote id it should ask the server for a thumbnail.

This never happened because of an && instead of an ||.

I also had to set updateThumbnailNeeded to false when it finished otherwise it entered a loop because it kept passing the validation: if (thumbnail == null || file.isUpdateThumbnailNeeded()).

Regarding test i didn't really understand where and how to test this functionality because, in case of an integration test, i need a server to call.

I would be more than happy to add a test if some kind soul could give me a little help xD <3

2024-06-20 13:26 UTC, alperozturk96 requested changes
Hello

Thanks for your contribution 💯 

After this change, I came across something like this. Besides that current implementation on master for ThumbnailsCacheManager also not ideal and good, we will check it, thank you so much 👍 

https://github.com/nextcloud/android/assets/67455295/f1f2b47d-2c8b-4da4-aeb9-e22051638a57

2024-06-20 13:29 UTC, camillo-positano commented
Thanks for the test, will verify! 

Could you give me any info of the steps you did to encounter this issue? 

Because on my device with my nextcloud instance that didn't happen. 
Were those images on the device or on the server? 

ty!

2024-06-20 13:33 UTC, camillo-positano commented
Hey should be fixed now! could you give it a check?

2024-06-20 14:34 UTC, alperozturk96 requested changes

2024-06-20 14:34 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
>              file = (OCFile) params[0];
Thanks for the fast response. It's working now like master, but file can be null, because **_Object... params_** maybe not OCFile, maybe empty OCFile array etc.

Could you add those null checks and type checks inside doInBackground function? 

```
            if (params != null && params.length > 0 && params[0] instanceof OCFile downloadedFile) {
                file = downloadedFile;
            } else {
                Log_OC.d(TAG, "Downloaded file is null");
                return null;
            }

            if (file.getRemoteId() == null || !file.isPreviewAvailable()) {
                Log_OC.d(TAG, "File cannot be previewed");
                return null;
            }
```

2024-06-20 14:46 UTC, camillo-positano commented on app/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
>              file = (OCFile) params[0];
Sure thing, will do!

2024-06-20 15:16 UTC, camillo-positano commented on app/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
>              file = (OCFile) params[0];
i added the check on params but inverted what you asked to implement a fail fast principle.

then the check you asked to add on the remote id and preview available was already "implemented" so i simply added a log when it enters the else statement.
Because if there is no remote id and the preview is false it will enter that else statement instead of trying to get from the cache or server

2024-06-20 15:52 UTC, camillo-positano commented on app/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
>              file = (OCFile) params[0];
I've also just pushed the extraction in two separate methods!

2024-06-21 06:28 UTC, alperozturk96 approved these changes
Tested, working

2024-06-23 10:53 UTC, camillo-positano commented
This merge should also close this isse: #10389

2024-06-27 01:55 UTC, AndyXheli commented
@camillo-positano do you have an apk so I can insult and test this please ?

2024-06-27 08:34 UTC, merged

2024-06-27 08:44 UTC, camillo-positano commented
@AndyXheli if you want to give it a try here is the apk: https://we.tl/t-MCTLpO7EyX

2024-06-27 08:46 UTC, AndyScherzinger commented
It will also be part of the next daily build :)