Check for right media type in auto upload
nextcloud/android pull request #13255
Opened 2024-07-09 15:10 UTC by JonasMayerDev

Fixes #13087, #13035, #12910.

To test this PR, have images and videos in the same folder, activate auto upload for videos OR images and put a new file of the opposite type in the folder. Without this PR it uploads the file regardless. With that PR it first checks if it is the correct type and then uploads.

- [X] Tests written, or not not needed

2024-07-11 07:35 UTC, alperozturk96 requested changes
Auto upload, not uploading to the correct path after configure.


https://github.com/nextcloud/android/assets/67455295/48934779-ac41-4617-9c2d-8396accc6249

**How to Reproduce?**

1. Enable auto upload for new detected media folder
2. InstantUpload folder will be used for auto upload
3. Configure the auto upload path (e.g. MyFavFolder) for selected folder
4. Still uploading to the InstantUpload folder

2024-07-11 07:37 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/datamodel/SyncedFolder.java
>      public boolean containsFile(String filePath){
```
 public boolean containsFile(String filePath) {
        return filePath.contains(localPath);
    }

 public boolean isImageOrVideo(String filePath) {
        return (getType() == MediaFolderType.IMAGE && MimeTypeUtil.isImage(new File(filePath))) ||
                (getType() == MediaFolderType.VIDEO && MimeTypeUtil.isVideo(new File(filePath))) ||
                getType() == MediaFolderType.CUSTOM;
 }
```

It would be good to separate the logic because otherwise containsFile doing two jobs and the name of the function will mislead us.

Why getType() == MediaFolderType.CUSTOM used?

2024-07-11 08:19 UTC, JonasMayerDev commented
> Auto upload, not uploading to the correct path after configure.
> 
>  f.mp4 
> **How to Reproduce?**
> 
> 1. Enable auto upload for new detected media folder
> 2. InstantUpload folder will be used for auto upload
> 3. Configure the auto upload path (e.g. MyFavFolder) for selected folder
> 4. Still uploading to the InstantUpload folder

I think this is also an issue on master (could you pls test). When you activate auto upload and then afterward change the directory for upload, it already uploaded the files to the wrong directory. Only new files will be uploaded to the newly specified folder. To mitigate this, you can activate and change the path of the folder using the 3 dot menu in one go.

2024-07-11 08:22 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/datamodel/SyncedFolder.java
>      public boolean containsFile(String filePath){
Yes, we know that this is the case and that is exactly why we need to separate it into two functions. Otherwise, we have to give such a long explanation. 

The code should explain itself as much as possible, rather than us explaining it.

2024-07-11 08:44 UTC, alperozturk96 commented
> > Auto upload, not uploading to the correct path after configure.
> > f.mp4
> > **How to Reproduce?**
> > 
> > 1. Enable auto upload for new detected media folder
> > 2. InstantUpload folder will be used for auto upload
> > 3. Configure the auto upload path (e.g. MyFavFolder) for selected folder
> > 4. Still uploading to the InstantUpload folder
> 
> I think this is also an issue on master (could you pls test). When you activate auto upload and then afterward change the directory for upload, it already uploaded the files to the wrong directory. Only new files will be uploaded to the newly specified folder. To mitigate this, you can activate and change the path of the folder using the 3 dot menu in one go.

[Issue](https://github.com/nextcloud/android/issues/13264)

2024-07-12 06:55 UTC, alperozturk96 approved these changes

2024-07-12 06:55 UTC, merged