Internal 2way sync
nextcloud/android pull request #13294
Opened 2024-07-19 08:29 UTC by tobiasKaminsky

- [ ] Tests written, or not not needed

2024-08-03 21:08 UTC, superzanti commented
This would be a dream come true.

2024-08-08 06:53 UTC, CptCurk commented
> APK file: https://www.kaminsky.me/nc-dev/android-artifacts/13294.apk ![qrcode](https://camo.githubusercontent.com/309d39a0ddf6adf5558f7ce9c81e0b62349e7f5234ab386352b7af9a45441202/68747470733a2f2f7777772e6b616d696e736b792e6d652f6e632d6465762f616e64726f69642d6172746966616374732f31333239342e706e67) To test this change/fix you can simply download above APK file and install and test it in parallel to your existing Nextcloud app.

Hello, 

It looks like the link is dead. Where I can download this apk for testing ?

2024-08-20 11:48 UTC, alperozturk96 requested changes

2024-08-20 11:48 UTC, alperozturk96 commented on app/src/main/java/com/nextcloud/client/jobs/InternalTwoWaySyncWork.kt
> +        if (!powerManagementService.isPowerSavingEnabled ||
We can reverse the if condition and get rid of the if block.

```
if (powerManagementService.isPowerSavingEnabled && (!connectivityService.isConnected || connectivityService.isInternetWalled)) {
  Log_OC.d(TAG, "Not starting due to constraints!")
  return Result.failure()
}

  ..
  ..
  ..
  logic
  ..
  ..
```

2024-08-20 11:48 UTC, alperozturk96 commented on app/src/main/java/com/nextcloud/client/jobs/InternalTwoWaySyncWork.kt
> +            // TODO check storage left
We can remove TODO if unnecessary

2024-08-20 11:48 UTC, alperozturk96 commented on app/src/main/java/com/nextcloud/client/jobs/InternalTwoWaySyncWork.kt
> +            for (user in users) {
Optional alternative

```
users.forEach { user ->
    val fileDataStorageManager = FileDataStorageManager(user, context.contentResolver)
    val folders = fileDataStorageManager.getInternalTwoWaySyncFolders(user)

    folders.forEach { folder ->
        Log_OC.d(TAG, "Folder ${folder.remotePath}: started!")
        
        val operation = SynchronizeFolderOperation(context, folder.remotePath, user, fileDataStorageManager)
            .execute(context)

        if (operation.isSuccess) {
            Log_OC.d(TAG, "Folder ${folder.remotePath}: finished!")
        } else {
            Log_OC.d(TAG, "Folder ${folder.remotePath} failed!")
            result = false
        }

        folder.apply {
            internalFolderSyncResult = operation.code.toString()
            internalFolderSyncTimestamp = System.currentTimeMillis()
        }
        
        fileDataStorageManager.saveFile(folder)
    }
}
```

2024-08-20 11:48 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/activity/InternalTwoWaySyncActivity.kt
> + * SPDX-FileCopyrightText: 2024 Your Name <your@email.com>
Please update license header

2024-08-20 11:48 UTC, alperozturk96 commented on app/src/main/java/com/nextcloud/client/jobs/InternalTwoWaySyncWork.kt
> + * SPDX-FileCopyrightText: 2024 Your Name <your@email.com>
Please update license header

2024-08-20 11:48 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/adapter/InternalTwoWaySyncAdapter.kt
> + * SPDX-FileCopyrightText: 2024 Your Name <your@email.com>
Please update license header

2024-08-20 11:48 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/adapter/InternalTwoWaySyncViewHolder.kt
> + * SPDX-FileCopyrightText: 2024 Your Name <your@email.com>
Please update license header

2024-08-20 11:48 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/adapter/InternalTwoWaySyncViewHolder.kt
> +        binding.apply {
You can use `run` instead of `apply`. `apply` returning binding value after applying all changes, but result of the `apply` didn't used in this class.

2024-08-20 11:48 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
> +                getFile().setInternalFolderSyncTimestamp(0L);
can `getFile()` cause NPE?

2024-08-23 06:27 UTC, tobiasKaminsky commented on app/src/main/java/com/nextcloud/client/jobs/InternalTwoWaySyncWork.kt
> +            // TODO check storage left
I added it.
Please check logic.

2024-08-23 06:30 UTC, tobiasKaminsky commented on app/src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
> +                getFile().setInternalFolderSyncTimestamp(0L);
We are using it in same onClick() function on other occurences, so hopefully not.

2024-08-23 08:43 UTC, alperozturk96 requested changes

2024-08-23 08:43 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/activity/InternalTwoWaySyncActivity.kt
> + * SPDX-FileCopyrightText: 2024 Your Name <your@email.com>
Please update header license

2024-08-26 07:43 UTC, AndyScherzinger approved these changes

2024-08-26 07:44 UTC, merged

2024-08-26 17:34 UTC, AndyXheli commented
Hey @AndyScherzinger so i download this on S24 Ultra to try it out and when i click on Internal two way sync i get a white screen and nothing else.

2024-08-27 21:54 UTC, saziton commented
Hi, same as @AndyXheli on a Nokia XR20, and same logs.

Thank you to work on this long awaited feature.

2024-08-27 22:39 UTC, phikman commented
Same issue and logs on Google Pixel 6 and Android 14.

2024-09-03 07:16 UTC, tobiasKaminsky commented
A better UI is in https://github.com/nextcloud/android/pull/13494

2024-09-03 15:57 UTC, Pitachmok commented
> Same issue and logs on Google Pixel 6 and Android 14.
> 
> Edit: I've worked it out, looking at the screen shots above, navigate to the folder you want synced in App, go details, tick "sync" then it should appear in the settings page.
> 
> I'd suggest a UI review to see how we can make it more intuitive to the users.
> 
> Now onto testing!

Same issue and logs on POCO and Android 13 and pre-syncing the folder does not help

2024-09-19 11:18 UTC, ivanhercaz commented
Hi! First of all, thank you very much for this awesome feature, @tobiasKaminsky. It is really great to have it in Nextcloud because it is a really useful feature.

I don't know if this PR is the best place to ask about this feature, if it isn't, just let me know and I will move the comment there:

How often should the internal 2-way sync be fired? Is it scheduled to be fired in a specific amount of time (`x` minutes)? Or this feature depends of the workload of each user's application and server instances?

Regards

2024-09-20 13:52 UTC, AndyScherzinger commented
@ivanhercaz the sync is scheduled to run every 15 minutes and will do so given it has a WiFi connection at that time and else try 15 minutes later again

2024-09-20 18:21 UTC, ivanhercaz commented
@AndyScherzinger, thank you very much for the information!

2024-09-23 18:27 UTC, superzanti commented
With this latest update, when I go to "menu -> settings -> internal two way sync" I just get a black screen.

2024-09-23 18:58 UTC, AndyScherzinger commented
Van you please raise it as a new ticket and ping @tobiasKaminsky and @alperozturk96 please? Thanks in advance 🙏

2024-09-24 20:38 UTC, superzanti commented
Okay. The above issue was fixed with #13607 however, no two way sync seems to be happening.

My test:
- enable 2 way sync on a folder
- double check in the "internal two way sync" settings that the folder has been enabled.
- Add a file using my android file manager to the synced folder
- wait two hours

The file never seems to be uploaded to nextcloud.
Updating a file that already existed seems slow, but it does work. However, it doesn't seem any different than before when I would manually go into the app and click sync.

Is this behavior expected?

2024-09-24 22:03 UTC, AndyScherzinger commented
I'd say no. Expected behavior would be that the files gets picked up.

Cc @tobiasKaminsky

2024-09-25 10:26 UTC, alperozturk96 commented
@superzanti @tobiasKaminsky  @AndyScherzinger I [fix the worker](https://github.com/nextcloud/android/pull/13612/commits/d81ddfda0d8ff7e1ead0c81675d65bf336e6a5e4) as well. It should work now, fyi.

2024-09-25 22:45 UTC, superzanti commented
Unfortunately I still have the same behavior. Is there anything I can provide to assist in the debug?

2024-09-26 18:11 UTC, tobias0409 commented
Hey,

I encountered the same behavior that I described a week ago in the [Nextcloud Forum](https://help.nextcloud.com/t/trouble-with-2-way-sync-in-nextcloud-v3-30-0-notes-not-updating-properly/204293/5). Unfortunately, the proposed fix isn't working for me either.

I’d be happy to assist further if needed or provide any additional information that could help with the resolution.

2024-09-27 18:07 UTC, saziton commented
Test results : 
At the beginning it's woukd try repeatidly to download everything with the same kind of fail downloads that the regular app has when i try to synchronize a huge number of files 

Then i turned off notifications forgot about it and it seems to work perfectly now , after some weeks.

I didn't try to place a new file in the dir without using the app to see if it uploads.

2024-09-27 18:26 UTC, superzanti commented
> I didn't try to place a new file in the dir without using the app to see if it uploads.

@saziton  Would you try this? It doesn't work for me.

2024-09-30 13:54 UTC, alperozturk96 commented
With the [latest changes](https://github.com/nextcloud/android/pull/13612#issuecomment-2383171070), these issues have been solved as well.

2024-09-30 15:40 UTC, tobias0409 commented
Unfortunately, the new version does not solve the problem for me. Perhaps someone can confirm this?

2024-09-30 16:56 UTC, superzanti commented
@tobias0409 Confirmed.

And no matter how long I leave it syncing I still see "Not yet, soon to be synced" in Settings > Internal two way sync

![image](https://github.com/user-attachments/assets/0a419450-bbfd-4aef-8635-b113203af35d)

2024-09-30 17:57 UTC, alperozturk96 commented
After the latest changes, I tried and it worked as expected. Background job runs every 15 minute.

Thank you very much for your messages and feedback. @tobias0409 Could you try with this [apk](https://www.kaminsky.me/nc-dev/android-artifacts/13612.apk)?

2024-09-30 18:50 UTC, superzanti commented
I'm running a test now.
Steps:
- Uninstall old QA app and remove all data
- Install new [QA app](https://www.kaminsky.me/nc-dev/android-artifacts/13612.apk)
- Login to nextcloud and grant access
- Select details on folder and check the "sync" checkbox
- Force a sync on that folder
- Wait till sync finishes (for a 340KB folder you'd expect this to be quick, but it takes about 10 minutes on my phone)
- Us the phone's  file browser to create a file in the nextcloud folder that I'm syncing. (Done at 11:24 my time)
- Refresh the nextcloud folder (Done at intervals: 11:25, 11:30, 11:34, 11:38, 11:49)

The changes were never picked up.

2024-09-30 19:35 UTC, tobias0409 commented
> After the latest changes, I tried and it worked as expected. Background job runs every 15 minute.
> 
> Thank you very much for your messages and feedback. @tobias0409 Could you try with this [apk](https://www.kaminsky.me/nc-dev/android-artifacts/13612.apk)?

Hey, I tried the new version. Still the same error - all data changes (create, modify, delete) outside the nc app are not recognized or reset.

2024-10-07 18:02 UTC, superzanti commented
Are there any updates or progress on this?
If it's just a setup error on my end, I'd like to fix that.

2024-10-08 07:55 UTC, alperozturk96 commented
> Are there any updates or progress on this? If it's just a setup error on my end, I'd like to fix that.

We released [3.30.1 RC1](https://github.com/nextcloud/android/releases/tag/rc-3.30.1-01). However, the checked status of the folder disappears after some time. We will gather more information based on this RC release and address the issue. I suggest collecting more details from [this link](https://github.com/nextcloud/android/issues/13734). Thank you.

2024-10-08 17:25 UTC, superzanti commented
@alperozturk96 
Yeah it's not that syncing gets disabled, it's that I can't update outside the nextcloud app as mentioned by @tobias0409

2024-10-09 07:11 UTC, alperozturk96 commented
@superzanti It seems like we might be dealing with two issues here, as I encountered the one I mentioned earlier. 

@tobias0409 Would it be possible to create an issue for this?

I just wanted to kindly remind everyone that we have a dedicated page for discussing bugs. It would be great if we could continue the conversation there to keep things organized. Thank you for understanding 💯 

We are aware of this issue and the one I mentioned before.