Improve Media Player
nextcloud/android pull request #13467
Opened 2024-08-26 01:31 UTC by parneet-guraya

Fixes:
#925
#5037
#11810

- Changes Introduced: 
- [x]  Audio files now can be streamed over network.
- [x]  Audio playback in background with media style notification.
- [x]  Player can also handle bluetooth commands.
- [ ] WIP ...

https://github.com/user-attachments/assets/f452b2a1-0ffe-43d5-b794-d0d7872522dd

![Screenshot_2024-08-26-06-12-09-82](https://github.com/user-attachments/assets/bfa80d27-42ae-456e-8994-d18ecec26135)

2024-09-09 12:53 UTC, alperozturk96 requested changes
Thank you for your contribution! I've created a Git patch to eliminate the use of the "!!" operator.

[force_unwrap1.patch](https://github.com/user-attachments/files/16930464/force_unwrap1.patch)

Could you apply this patch?

Additionally, the use of `runBlocking` blocks the current thread until it completes. `BackgroundPlayerService` runs on the main thread. I tested, general flow looks okay. It might be acceptable in this case, but for `initNextcloudExoPlayer()`, would it be possible to notify the service after this function finishes?

2024-09-09 13:02 UTC, parneet-guraya commented
> Thank you for your contribution! I've created a Git patch to eliminate the use of the "!!" operator.
> 
> [force_unwrap1.patch](https://github.com/user-attachments/files/16930464/force_unwrap1.patch)
> 
> Could you apply this patch?

Sure

> 
> Additionally, the use of `runBlocking` blocks the current thread until it completes. `BackgroundPlayerService` runs on the main thread. I tested, general flow looks okay. It might be acceptable in this case, but for `initNextcloudExoPlayer()`, would it be possible to notify the service after this function finishes?

Ah, I was aware of this forgot to add the comment. I know it would block the main thread it's just that the `Nextcloud client` needs to be created on background thread. but in that time service already starts and player doesn't get initialized. It doesn't do that much of a task while creating a client so I add a run blocking so to wait for the client. 

Also, we're not the one starting the service, it is started when session token is created. So no way we can tell it to start after the client init on background. 

since controlling when service starts not in our control. Can we have some other option to inject Exoplayer without having to create client instance? tell me if you have any ideas I will see.

thanks :+1:

2024-09-11 13:38 UTC, alperozturk96 commented
@parneet-guraya Could you please address the Codacy Static Code Analysis issues and apply a git patch to eliminate the use of the `!!` operator so we can proceed with the merge? Thanks for your contribution! 💯

2024-09-12 09:20 UTC, alperozturk96 approved these changes

2024-09-12 09:20 UTC, merged