2way sync: Better view handling
nextcloud/android pull request #13494
Opened 2024-08-30 12:12 UTC by tobiasKaminsky

- empty state

- [ ] Tests written, or not not needed

2024-09-03 07:49 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/activity/InternalTwoWaySyncActivity.kt
>          binding.list.apply {
You can omit the binding prefix for emptyList.
Instead of apply, use run when there’s no need to return a modified instance at the end of the block. Use apply only when assigning to a variable.


```
binding.list.run {
            setEmptyView(binding.emptyList.emptyListView)

            binding.emptyList.run {
                emptyListViewHeadline.run {
                    visibility = View.VISIBLE
                    setText(R.string.internal_two_way_sync_list_empty_headline)
                }
                emptyListViewText.run {
                    visibility = View.VISIBLE
                    setText(R.string.internal_two_way_sync_text)
                }
                emptyListIcon.run {
                    visibility = View.VISIBLE
                    setImageDrawable(
                        viewThemeUtils.platform.tintDrawable(
                            context,
                            R.drawable.ic_sync,
                            ColorRole.PRIMARY
                        )
                    )
                }
            }

            adapter = InternalTwoWaySyncAdapter(fileDataStorageManager, user.get(), context).apply {
                notifyDataSetChanged()
            }
            layoutManager = LinearLayoutManager(context)
        }
```


Alternatively you can omit second binding as well.

```

binding.run {
            list.run {
                setEmptyView(binding.emptyList.emptyListView)

                emptyList.run {
                    emptyListViewHeadline.run {
                        visibility = View.VISIBLE
                        setText(R.string.internal_two_way_sync_list_empty_headline)
                    }
                    emptyListViewText.run {
                        visibility = View.VISIBLE
                        setText(R.string.internal_two_way_sync_text)
                    }
                    emptyListIcon.run {
                        visibility = View.VISIBLE
                        setImageDrawable(
                            viewThemeUtils.platform.tintDrawable(
                                context,
                                R.drawable.ic_sync,
                                ColorRole.PRIMARY
                            )
                        )
                    }
                }

                adapter = InternalTwoWaySyncAdapter(fileDataStorageManager, user.get(), context).apply {
                    notifyDataSetChanged()
                }
                layoutManager = LinearLayoutManager(context)
            }
        }
```

2024-09-03 07:50 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/activity/InternalTwoWaySyncActivity.kt
>      override fun onCreate(savedInstanceState: Bundle?) {
Add @SuppressLint("NotifyDataSetChanged") since code updates InternalTwoWaySyncAdapter items.

2024-10-29 06:39 UTC, tobiasKaminsky commented
/backport to stable-3.30

2024-10-29 08:02 UTC, ZetaTom requested changes
Unfortunately, this change breaks the *Internal two way sync* screen on my device. *No two way sync folder yet* always appears even when multiple folders are set up for two way sync.

The `InternalTwoWaySyncAdapter` does, however, accurately reflect the number of folders when evaluating the following expressing using the debugging console: `binding.list.adapter.itemCount`.

2024-10-29 08:54 UTC, alperozturk96 approved these changes

2024-10-30 09:25 UTC, ZetaTom approved these changes
Everything seems to work on my end.

2024-10-30 10:29 UTC, merged