Enforced servers
nextcloud/android pull request #13493
Opened 2024-08-30 06:25 UTC by tobiasKaminsky

similar to "enforce domain" this allows to build an app with a dropdown menu with pre-defined servers.

- [ ] Tests written, or not not needed

2024-08-30 08:00 UTC, alperozturk96 requested changes

2024-08-30 08:00 UTC, alperozturk96 commented on app/src/main/res/layout/account_setup.xml
> +            <LinearLayout
Why do you need to wrap Spinner with LinearLayout?

```
         <Spinner
                android:id="@+id/servers_spinner"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:visibility="gone"
                tools:visibility="visible"
                android:foregroundTint="#FFFFFF"
                android:spinnerMode="dialog"
                android:textColor="@color/white_helper_text" />
```

This should work without LinearLayout.

2024-09-02 07:15 UTC, tobiasKaminsky commented on app/src/main/res/layout/account_setup.xml
> +            <LinearLayout
I first thought, that I need more elements.
will try to remove it.

2024-09-12 07:01 UTC, alperozturk96 approved these changes

2024-09-12 07:16 UTC, merged

2024-09-23 07:15 UTC, tobiasKaminsky commented
/backport to stable-3.30