Feature - Offline File Creation
nextcloud/android pull request #13501
Opened 2024-09-02 08:52 UTC by alperozturk96

- [ ] Tests written, or not not needed

2024-09-23 08:22 UTC, tobiasKaminsky commented
This fails for me with a SQLite upgrade error.
Can you rebase it and test 
- uninstall all
- install and run master
- install and run this PR?

2024-09-23 12:55 UTC, alperozturk96 commented
> This fails for me with a SQLite upgrade error. Can you rebase it and test
> 
> * uninstall all
> * install and run master
> * install and run this PR?

Previously, I thought we needed the `parentPath` column, but it turns out we don't since we already have the `parent_oc_file_id` and the `offline_operation_type` sealed class, which effectively differentiates between operations. After adding the migration from version 84 to 85, the issue was resolved.

2024-09-26 10:07 UTC, alperozturk96 commented
> What I tested
> 
> * be offline
> * create folder "offline" -> not sorted correctly (sort order was newest first), but at end
> * added 5 images files -> no thumbnail, but we could show one (similar like we do on upload view)
> * after online again: needed to refresh to see that files have been uploaded
> * date is wrong?
> 
> ![image](https://private-user-images.githubusercontent.com/5836855/370762837-275a55f2-41bb-4d72-b7bb-d67d814f467b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDEyODEsIm5iZiI6MTcyNzM0MDk4MSwicGF0aCI6Ii81ODM2ODU1LzM3MDc2MjgzNy0yNzVhNTVmMi00MWJiLTRkNzItYjdiYi1kNjdkODE0ZjQ2N2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjZUMDg1NjIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDI4MjY3NDFiZmRjZTQxYjFjZTRhMWE3MzQ5ZjA1NzQwNzI3Njg0MGUwNTQ2YjYxNTYzM2Y4ZjRmZDdmZTkzNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.F2cFG3hDVZdUO_Yt8TBJXSEM6RzCLt7rn-J73E8no2E)

I set the creation and modification date with the correct UTC timestamp (e.g., 1727343315600) for `OCFile`, but the `FileStorageUtils.fillOCFile(RemoteFile remote)` function overrides it with an invalid UTC timestamp (e.g., 15032385535000).

To create a file in the `OfflineOperationWorker`, the correct values for the creation and modification timestamps are also used. Do you have any idea why the server returns this value?

2024-09-26 13:07 UTC, alperozturk96 commented
@tobiasKaminsky The sorting order may change after the upload because the stored value is being overridden by remoteFile after a successful upload.

**Fixes:**

https://github.com/user-attachments/assets/d2fd0faa-4867-485f-b735-8f7b2bfb38aa

2024-10-07 13:42 UTC, AndyScherzinger requested changes

2024-10-07 13:42 UTC, AndyScherzinger commented on app/schemas/com.nextcloud.client.database.NextcloudDatabase/84.json
> -        "createSql": "CREATE TABLE IF NOT EXISTS `${TABLE_NAME}` (`_id` INTEGER PRIMARY KEY AUTOINCREMENT, `offline_operations_parent_oc_file_id` INTEGER, `offline_operations_parent_path` TEXT, `offl
why is an existing DB migration being changed? This will fail on any installation where the DB is already at v84 (!)

2024-10-07 13:50 UTC, alperozturk96 commented on app/schemas/com.nextcloud.client.database.NextcloudDatabase/84.json
> -        "createSql": "CREATE TABLE IF NOT EXISTS `${TABLE_NAME}` (`_id` INTEGER PRIMARY KEY AUTOINCREMENT, `offline_operations_parent_oc_file_id` INTEGER, `offline_operations_parent_path` TEXT, `offl
We didn't release any version contains this feature. However, master have that unnecessary field. Nevertheless, Migration84to85 should handle it, I will update the code, thanks.

2024-10-08 12:50 UTC, tobiasKaminsky approved these changes

2024-10-09 13:53 UTC, merged