Only Download Necessary Files
nextcloud/android pull request #13683
Opened 2024-10-02 13:51 UTC by alperozturk96

- [ ] Tests written, or not not needed

**Changes**

- Download only files that haven't been downloaded and aren't media files.
- Return early if requestDownloads is empty.

2024-10-04 07:34 UTC, tobiasKaminsky commented
Can you explain reason behind filtering media files?

This worker is also used when exporting files (FilesExportWork.kt), so this would then not work if you want to export a pdf file?

2024-10-04 07:34 UTC, tobiasKaminsky requested changes
see comment

2024-10-08 09:51 UTC, alperozturk96 commented
> Can you explain reason behind filtering media files?
> 
> This worker is also used when exporting files (FilesExportWork.kt), so this would then not work if you want to export a pdf file?


![Screenshot 2024-10-08 at 11 49 09](https://github.com/user-attachments/assets/9b4f38ac-0576-4b94-8643-923b8490f2a8)

FilesExportWork only triggers the FileDownloadWorker when a file hasn’t been downloaded, so the filter introduced in this PR won’t be applied.

Here’s a demo of FilesExportWork with already downloaded files.

https://github.com/user-attachments/assets/042674cc-aace-48aa-b353-e0dd31c991f3

You can check the PR description for more details on the purpose of this PR.

2024-10-15 13:52 UTC, fegauthier commented
I'm eagerly waiting for this PR. I have a Google Pixel 8, and files are constantly resyncing every 15 minutes. It drains the battery significantly and uses bandwidth unnecessarily. Do you guys know when it will be merged?

Thanks.

2024-10-29 09:43 UTC, alperozturk96 commented
Not Valid after: https://github.com/nextcloud/android/pull/13897

2024-10-29 09:43 UTC, closed without merging