BugFix - Check Nullable Fields During Folder Changes Check
nextcloud/android pull request #13937
Opened 2024-11-04 10:24 UTC by alperozturk96

- [ ] Tests written, or not not needed

**How to Test?**

1. Place a debugger in the checkForChanges() function.
2. Try syncing both a changed and an unchanged folder; the debugger should hit the selected line, and the correct result should be returned.

2024-11-04 10:30 UTC, alperozturk96 commented
@tobiasKaminsky Could you check the returned ResultCodes? Are they correct? Maybe some other result codes can suit better.

2024-11-11 13:17 UTC, alperozturk96 commented
/backport to stable-3.30

2024-11-11 13:25 UTC, tobiasKaminsky requested changes
These changes are too risky without real tests.

2025-06-05 10:11 UTC, alperozturk96 commented
outdated PR

2025-06-05 10:11 UTC, closed without merging