BugFix - Sync Nested Folder
nextcloud/android pull request #13974
Opened 2024-11-07 13:34 UTC by alperozturk96

- [ ] Tests written, or not not needed

2024-11-11 13:11 UTC, alperozturk96 commented
/backport to stable-3.30

2024-11-11 13:21 UTC, tobiasKaminsky commented on app/src/main/java/com/owncloud/android/operations/SynchronizeFolderOperation.java
> +        List<OCFile> children = getStorageManager().getAllFilesRecursivelyInsideFolder(mLocalFolder);
If we want to have nested folder sync, we should start with SynchronizeFolderOperation on folders, but not only on files.

2024-11-11 13:22 UTC, tobiasKaminsky requested changes
SynchronizeFolderOperation needs to be used.

2024-12-30 08:47 UTC, alperozturk96 commented
Duplication of https://github.com/nextcloud/android/pull/14166

2024-12-30 08:47 UTC, closed without merging

2025-07-13 09:11 UTC, pretubedongit commented
Why is this closed? It's not a duplication of #14166. This is about nested folder or level 1 files only. It's still present in the latest version.