Improved "Choose storage location" dialogue
nextcloud/android pull request #14005
Opened 2024-11-12 10:13 UTC by ZetaTom

This change introduces a new dialogue that allows users to change the local storage location. It replaces the current dialogue, which may be too complicated for the average user.

Instead of providing the user with a list of paths to choose from, the user is presented with a simple UI allowing them to choose if they want to use internal or external storage. Additionally, users can choose if they want to enable media indexation or not. Enabling media indexation allows other apps to access local files from Nextcloud.

### Screenshots

Old | New
--- | ---
![data_storage_location_old](https://github.com/user-attachments/assets/0b79c992-d5fc-43cc-a37a-9bfda1d840a6) | ![data_storage_location_new](https://github.com/user-attachments/assets/51627ab4-b84c-4783-b762-c470d71c1c41)

### Known Issues
For some users the *External Storage* selection may behave unexpectedly. Even if no external storage is present, it may still be shown as an option. This is to be expected, as this dialogue only interprets the results from calling `DataStorageProvider.getAvailableStoragePoints()`.

Language strings are included since a string was renamed.

Fixes #1088 #2416

---
- [ ] Tests written, or not not needed

2024-11-12 10:26 UTC, jancborchardt reviewed
Awesome @ZetaTom! :)

> Enabling media indexation allows other apps to access local files from Nextcloud.

Good point – should we then rename "Allow media indexing" to "Allow other apps to access local Nextcloud files"? Or something shorter of course. :) This will make it way more understandable since I was also unsure what it meant.

2024-11-13 10:04 UTC, ZetaTom commented
> Good point – should we then rename "Allow media indexing" to "Allow other apps to access local Nextcloud files"? Or something shorter of course. :) This will make it way more understandable since I was also unsure what it meant.

I've since changed the string to *Allow access from other apps*. In my opinion this still gets the point across and is reasonably short.

2024-11-13 10:26 UTC, jancborchardt approved these changes
Nice, looks great! :)

2024-11-15 15:07 UTC, alperozturk96 requested changes
It looks good 💯. With a bit more polishing, I think it’ll be ready to merge.

2024-11-15 15:07 UTC, alperozturk96 commented on app/src/main/java/com/nextcloud/ui/ChooseStorageLocationDialogFragment.kt
> +        binding.storageExternalRadio.isEnabled = hasExternalStorage
hasInternalStorage or hasExternalStorage can be false, in that case no need to call formatFreeSpaceString.

This approach could be better:

```
val hasInternalStorage = storagePoints.any { it.storageType == StorageType.INTERNAL }
binding.storageInternalRadio.isEnabled = hasInternalStorage
binding.storageInternalRadio.text = if (hasInternalStorage) formatFreeSpaceString(StorageType.INTERNAL, selectedPrivacyType) else ""
```

2024-11-15 15:07 UTC, alperozturk96 commented on app/src/main/java/com/nextcloud/ui/ChooseStorageLocationDialogFragment.kt
> +    private fun formatFreeSpaceString(storageType: StorageType, privacyType: PrivacyType): String {
This function does not just format a string but also returns it; therefore, I would name it something like `getFormattedFreeSpaceString`.

2024-11-18 09:51 UTC, ZetaTom commented on app/src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
> +                Intent intent = new Intent(MainApp.getAppContext(), ChooseStorageLocationActivity.class);
Since `SettingsActivity` extends the deprecated `PreferenceActivity`, we unfortunately need a intermediary Activity to show the fragment. We already have a similar workaround in place for `SyncedFoldersActivity`, `ContactsPreferenceActivity`, and `SetupEncryptionActivity`.

2024-11-18 10:06 UTC, ZetaTom commented on app/src/main/java/com/nextcloud/ui/ChooseStorageLocationDialogFragment.kt
> +        binding.storageExternalRadio.isEnabled = hasExternalStorage
To provide a intuitive user experience, we still need all available options to be displayed with the respective labels. `formatFreeSpaceString` will return a String already properly formatted, ready to be displayed, even if the storage type isn't available.

The suggested approach would show a non-selectable option without any associated label to provide context:

![untitled](https://github.com/user-attachments/assets/84396644-c8e6-47ce-879e-b87a6843bade)

2024-11-18 10:11 UTC, ZetaTom commented on app/src/main/java/com/nextcloud/ui/ChooseStorageLocationDialogFragment.kt
> +    private fun formatFreeSpaceString(storageType: StorageType, privacyType: PrivacyType): String {
I've renamed `formatFreeSpaceString` to `getStoragePointLabel`.

2024-11-18 10:23 UTC, alperozturk96 commented on app/src/main/java/com/nextcloud/ui/ChooseStorageLocationDialogFragment.kt
> +        binding.storageExternalRadio.isEnabled = hasExternalStorage
If a storage type isn’t available, I will hide its radio button and text. We shouldn’t attempt to calculate the free space for unavailable storage.

2024-11-18 12:41 UTC, ZetaTom commented on app/src/main/java/com/nextcloud/ui/ChooseStorageLocationDialogFragment.kt
> +        binding.storageExternalRadio.isEnabled = hasExternalStorage
We aren't performing any calculations for storage locations which aren't available.

Using `storagePoints.firstOrNull()` we figure out if any locations match the given criteria. If no location is found, `storagePath` is set to `null` and `typeString` is returned.

2024-11-18 13:14 UTC, alperozturk96 approved these changes

2024-11-20 10:13 UTC, tobiasKaminsky approved these changes

2024-11-20 11:33 UTC, merged

2025-08-31 23:56 UTC, Eiernase commented
nice that i need to dig into some random change on github to find where my files are stored because the UI doesn't show me :(

2025-09-01 05:54 UTC, AndyScherzinger commented
@Eiernase you don't, it is the first item if you navigate to the settings from the main menu.

2025-09-04 08:24 UTC, Eiernase commented
@AndyScherzinger the option is the first item in the settings, but there's no mention anymore of where the internal and external storage locations are.
I was expecting there to just be a "Nextcloud" folder in my files next to all other initial directories – you know, like most apps do.
But it doesn't matter anyway, since there's apparently no way to keep a folder offline (feature requested seven years ago).

2025-09-04 08:58 UTC, AndyScherzinger commented
> But it doesn't matter anyway, since there's apparently no way to keep a folder offline (feature requested seven years ago).

Yes there is since quite a while. Open the details tab of a folder and hit the checkbox "Sync"

2025-09-06 20:04 UTC, Eiernase commented
I tried using that too, but it doesn't download the folder.

2025-09-08 07:31 UTC, AndyScherzinger commented
looping in @tobiasKaminsky since you build the sync feature I if am not mistaken.