BugFix - Icon Visibilities
nextcloud/android pull request #14030
Opened 2024-11-15 11:00 UTC by alperozturk96

- [ ] Tests written, or not not needed

• Hide the people icon after sharing with at least one user (fixes share icon visibility)
• Correct overlay icons for folders (e.g., shared with users, shared via link, locked, encrypted)

2024-11-15 13:58 UTC, AndyScherzinger commented
Screenshot Tests look good to me. Just replace the existing ones with the new ones. They are visually similar but fail due to the update of the common lib which has m3 theming so the blue and Grey tones are slightly different now 👍

2024-11-15 14:28 UTC, AndyScherzinger commented
LGTM

@alperozturk96 As a follow up maybe, did you see that the folder icons with an overlay are slightly smaller see their width than folders without an overlay? 🔍

2024-11-15 15:46 UTC, alperozturk96 commented
@AndyScherzinger Thank you. Good point. I will update the PR.

2024-11-19 09:46 UTC, ZetaTom requested changes
During my testing I've noticed some inconsistencies compared to the previous implementation. Otherwise it seems to work as expected; the share icon is only displayed when expected.

1. Corners of thumbnails are no longer rounded (see screenshot below)
2. Thumbnails of images are only displayed after a manual reload (pull to refresh)
3. The `ic_movie` overlay for video files is scaled wrong (see screenshot below)
4. Appearance of auto-upload folder has changed (icon used to be taller)

![image](https://github.com/user-attachments/assets/ae83f79d-b251-4836-8ffc-38396329fca1)

2024-11-19 09:46 UTC, ZetaTom commented on app/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
> +            }
During testing, I've notices that transparent PNGs are always displayed with a white and WEBPs with a black background. Is there a reason why PNGs are handled differently in this case?

![image](https://github.com/user-attachments/assets/db6a56d5-492c-4120-ba80-76cfec351b3e)

2024-11-21 10:03 UTC, jancborchardt reviewed
Just a small thing – the avatar seems to be a bit off to the right compared to the sharing icons. Not super important but might be easy to fix?
![image](https://github.com/user-attachments/assets/e3e869ef-5ed0-4566-a6b6-4b0af083b590)

2024-11-25 13:28 UTC, merged