request media_location
nextcloud/android pull request #14247
Opened 2024-12-27 07:20 UTC by tobiasKaminsky

Part of https://github.com/nextcloud/android/issues/14135#issuecomment-2563380986

- [ ] Tests written, or not not needed

2025-01-01 12:30 UTC, BluePixel4k commented
https://github.com/nextcloud/android/issues/14135#issuecomment-2563475719 - Quote with my answer/question:

> > Thus I created a draft PR, with an APK, that you can install in parallel: [#14247](https://github.com/nextcloud/android/pull/14247) (comment)
> > [@BluePixel4k](https://github.com/BluePixel4k) can you test this?
> 
> Thanks a lot! Yes, it's working fine for me with this version 👍 But is it possible to enable the ACCESS_MEDIA_LOCATION already before the user grants the image and video permission? Because if a user doesn't grant the permission but shares a picture via his local gallery app to the Nextcloud app, the GPS information is missing.

Is this possible?

2025-01-02 22:08 UTC, hw-hass23 commented
> [#14135 (comment)](https://github.com/nextcloud/android/issues/14135#issuecomment-2563475719) - Quote with my answer/question:
> 
> > > Thus I created a draft PR, with an APK, that you can install in parallel: [#14247](https://github.com/nextcloud/android/pull/14247) (comment)
> > > [@BluePixel4k](https://github.com/BluePixel4k) can you test this?
> > 
> > 
> > Thanks a lot! Yes, it's working fine for me with this version 👍 But is it possible to enable the ACCESS_MEDIA_LOCATION already before the user grants the image and video permission? Because if a user doesn't grant the permission but shares a picture via his local gallery app to the Nextcloud app, the GPS information is missing.
> 
> Is this possible?

Some gallery apps themselves have settings for "safe sharing" which zeros the GPS information upon sharing. Xiaomi Poco gallery is one of them (needed to disable "share without location" for proper sharing to Nextcloud app), whereas Google Foto left GPS intact.

2025-01-09 06:23 UTC, tobiasKaminsky commented
/backport to stable-3.30

2025-01-09 08:36 UTC, tobiasKaminsky commented
If no custom upload folder is found:
![2025-01-09-091542](https://github.com/user-attachments/assets/a6c99559-89d4-41d9-ab8a-96ddd2117e3f)

If custom upload folder is found:
![2025-01-09-091306](https://github.com/user-attachments/assets/7c92e7ab-86fd-4ede-b1cb-710ef4bb15cc)

2025-01-09 15:24 UTC, Whisprin commented
thanks @tobiasKaminsky 
Do you intend to send a notification to users after the upgrade? In order to satisfy https://github.com/nextcloud/android/issues/14349: Inform users who don't open the app regularly and rely on automatic background backups.

In case any (not just a custom) auto upload folder pair is found: Users should be informed explicitly that past Auto uploads didn't run since 3.30.6 (probably some time in mid December) and future Auto uploads won't run unless the new permission is granted.
It can also be made more explicit that Auto uploads of files other than photos and videos remain broken, even after granting the new permissions.
I'll post a revised draft of this message here later.

Is there way or a plan to ensure that those missed Auto uploads are carried out after the Photo and video permission is granted?
In my tests those past, missed uploads are not picked up automatically after the permission is granted.

2025-01-09 16:04 UTC, Whisprin commented
How about:

**Important Update for Auto Uploads**

Google denied the file permission needed for Auto Uploads. To restore functionality:

- **Manually check for missing uploads** since mid-December
- **Grant "Photos and Videos" permission**  in the next dialog
- **Grant "Location" permission** to retain GPS data in photos

Note that Auto Uploads for **files other than photos**/videos are currently **not possible** with the Play Store version of the Nextcloud app.

2025-01-13 11:17 UTC, alperozturk96 requested changes

2025-01-13 11:17 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
> +        }
```
if (!preferences.isAutoUploadGPlayWarning2Shown()) {
            String title = showAutoUploadDialog ? getString(R.string.auto_upload_gplay) : getString(R.string.upload_gplay);
            String message = showAutoUploadDialog ? getString(R.string.auto_upload_gplay_desc2) : getString(R.string.upload_gplay_desc);

            new MaterialAlertDialogBuilder(this, R.style.Theme_ownCloud_Dialog)
                .setTitle(title)
                .setMessage(message)
                .setNegativeButton(R.string.dialog_close, (dialog, which) -> {
                    dialog.dismiss();
                    preferences.setAutoUploadGPlayWarning2Shown(true);
                })
                .setIcon(R.drawable.nav_synced_folders)
                .create()
                .show();
        }
```

Please use this only title and message is changing

2025-01-13 11:17 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
> +        // only show on Android11+
No need for this comment. Code already explains itself.

2025-01-13 11:17 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
> +            // show dialog only on
No need for this comment. Code already explains itself.

2025-01-13 11:17 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
> +        if (!BuildHelper.GPLAY.equals(BuildConfig.FLAVOR) || MainApp.isClientBranded()) {
```
import com.owncloud.android.BuildConfig

object BuildHelper {
    private const val GPLAY: String = "gplay"

    fun isFlavourGPlay(): Boolean = GPLAY == BuildConfig.FLAVOR
}

```

BuildHelper object should include the check logic, thus no need to repeat same code for every use.

2025-01-13 11:17 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
> +        checkAutoUploadOnGPlay2();
These function names `notifyGPlayPermissionChanges() ` `showAutoUploadWarningForGPlayFlavour()` would be more clear.

2025-01-13 11:17 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
> +                new MaterialAlertDialogBuilder(this, R.style.Theme_ownCloud_Dialog)
Please use this logic in the separate function

2025-01-13 11:17 UTC, alperozturk96 commented on app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
> +                    .show();
**Optional:**

All three restriction is related to the Google Play Version. Adding all three in FileDisplayActivity directly will make the activity more hard to maintain. I would suggest extracting all these logics into a different class and use that class in the activity.

2025-01-13 16:04 UTC, ZetaTom requested changes

2025-01-14 06:34 UTC, tobiasKaminsky commented on app/src/main/java/com/nextcloud/client/jobs/MediaFoldersDetectionWork.kt
> +            sendAutoUploadNotification()
True, but another class might bring another risk.
And as we want to have this as a "hotfix" released soon, I think it is okay.

2025-01-14 06:34 UTC, tobiasKaminsky commented on app/src/gplay/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.READ_MEDIA_VISUAL_USER_SELECTED" />
Gplay

2025-01-14 07:36 UTC, alperozturk96 approved these changes

2025-01-14 07:49 UTC, alperozturk96 commented
@tobiasKaminsky How can you suppress this or maybe reduce condition count?

![Screenshot 2025-01-14 at 08 48 54](https://github.com/user-attachments/assets/96612f0a-a271-42f5-82e5-37b2d148e0da)

2025-01-14 08:46 UTC, merged

2025-01-17 07:21 UTC, AndreKoepke commented on app/src/main/java/com/nextcloud/client/jobs/MediaFoldersDetectionWork.kt
> +            sendAutoUploadNotification()
This causes a bug. See #14417. I've got also spammed by this notification.