BugFix - NetworkOnMainThreadException: FileDataStorageManager.saveFileWithParent
nextcloud/android pull request #14268
Opened 2024-12-30 11:26 UTC by alperozturk96

- [ ] Tests written, or not not needed

2025-01-03 14:33 UTC, tobiasKaminsky requested changes
Please fix in FileDisplayActivity

2025-01-07 09:21 UTC, alperozturk96 commented
> I think FileDataStorageManager shall not handle this. Instead, as seen in the linked bug, the root cause is that requestUploadOfFilesFromFileSystem() from FileDisplayActivity runs on MainThread.

After your comment, I checked again, and the actual issue is with the method:

`void isNetworkAndServerAvailable(@NonNull GenericCallback<Boolean> callback);`

This callback runs on the main thread, which is necessary for some cases. However, in other cases, like this one, it must run on a background thread instead of the main thread.

**Current Usage of isNetworkAndServerAvailable:**

**Must run on a background thread:**
	•	fileOperationsHelper?.removeFiles
	•	fileDataStorageManager.addRemoveFileOfflineOperation
	•	FileUploadHelper.Companion.instance().uploadNewFiles
        •	fileDataStorageManager.addCreateFileOfflineOperation

**Must run on the main thread:**
	•	DisplayUtils.showSnackMessage
	•	ocFileListFragment.setEmptyListMessage
	•	fileDisplayActivity.refreshCurrentDirectory

To address this, it would be better to create a new PR. Before proceeding, I want to inform you because this PR will touch multiple files. While it won’t be a large PR, it will require careful testing.

What do you think? Is it okay for you?

2025-01-15 10:37 UTC, alperozturk96 commented
@tobiasKaminsky How are we going to proceed? I explained earlier I have to change multiple files to fix [this](https://github.com/nextcloud/android/issues/14238) issue. Shall I create a PR for that?

2025-06-05 10:13 UTC, alperozturk96 commented
outdated PR

2025-06-05 10:13 UTC, closed without merging