Screenshots white
nextcloud/android pull request #6652
Opened 2020-08-05 13:38 UTC by tobiasKaminsky

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [ ] Tests written, or not not needed

2020-08-05 14:55 UTC, AndyScherzinger commented
@tobiasKaminsky something seems wrong with the build (missing most steps)

2020-10-20 20:29 UTC, AndyScherzinger requested changes
skips most CI steps

2020-10-29 12:40 UTC, tobiasKaminsky commented
Base branch needs to be merged before

2020-11-20 20:14 UTC, AndyScherzinger approved these changes

2020-12-09 13:12 UTC, merged