bump to new android docker
nextcloud/android pull request #6915
Opened 2020-09-09 06:12 UTC by tobiasKaminsky

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [ ] Tests written, or not not needed

2020-10-07 16:54 UTC, AndyScherzinger approved these changes

2020-10-07 17:57 UTC, AndyScherzinger commented
pinging @tobiasKaminsky - can this be merged?

2020-12-08 12:25 UTC, AndyScherzinger requested changes
@tobiasKaminsky needs rebase and conflicts resolved (probably also an update in the docker image in use...

2020-12-16 07:06 UTC, tobiasKaminsky commented
Obsolete, as after resolving conflicts, nothing changed.

2020-12-16 07:06 UTC, closed without merging