Auto Upload: Ignore folders that have no-images or seem to be music albums
nextcloud/android pull request #7042
Opened 2020-10-02 08:35 UTC by AndyScherzinger

(->just a single cover art image)

block detection notification and hide in lists

related to #3239

Signed-off-by: Andy Scherzinger <info@andy-scherzinger.de>

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [ ] Tests written, or not not needed

2020-10-02 10:49 UTC, tobiasKaminsky commented on src/main/java/com/owncloud/android/utils/FileUtil.java
> +            return filePath.substring(filePath.lastIndexOf(FileUtils.PATH_SEPARATOR) + 1);
I am unsure if this handles all special cases correctly.
new File(path).getName() will work, though I have no idea if needed or if there is a performance drawback

2020-10-02 10:54 UTC, tobiasKaminsky commented
Code looks good, but test cases would be awesome.
If you do not have time for it, I will write some.

2020-10-02 11:07 UTC, AndyScherzinger commented
> Code looks good, but test cases would be awesome.
If you do not have time for it, I will write some.

can you give me a hint on how to implement them? Or just for the utils class (as in plain junit)?

2020-10-02 11:23 UTC, AndyScherzinger commented on src/main/java/com/owncloud/android/utils/FileUtil.java
> +            return filePath.substring(filePath.lastIndexOf(FileUtils.PATH_SEPARATOR) + 1);
yeah, also not sure, so let's try new file variant

2020-10-02 12:14 UTC, tobiasKaminsky commented
>  Or just for the utils class (as in plain junit)?

Yeah, only the utils classes should be enough.
I guess you still need them as instrumented tests (in androidTest) as you use e.g. localFolder.listFiles(…) which uses Android SDK / needs file system access.

Otherwise you would have to mock all those.

2020-10-02 15:30 UTC, tobiasKaminsky requested changes

2020-10-02 15:30 UTC, tobiasKaminsky commented on src/androidTest/java/com/owncloud/android/utils/FileUtilTest.kt
> +        Assert.assertEquals("text returned when searchText was not empty",
The string printed in case of assertion error is a bit misleading, or? 
I think you can just remove it, as in all these cases it is direct understandable what should be tested

2020-10-02 15:30 UTC, tobiasKaminsky commented on src/main/java/com/owncloud/android/utils/FileUtil.java
>      public static @NonNull String getFilenameFromPathString(@Nullable String filePath) {
Can you add "in case of null or path is a a folder it returns "" "

2020-10-02 16:01 UTC, AndyScherzinger commented on src/androidTest/java/com/owncloud/android/utils/FileUtilTest.kt
> +        Assert.assertEquals("text returned when searchText was not empty",
yeah c&p issue, I'll remove it, just didn't get the test to run locally so I tried a push top see if CI can work with it, many more test to come tough for the other utility stuff.

2020-10-02 16:01 UTC, AndyScherzinger commented on src/main/java/com/owncloud/android/utils/FileUtil.java
>      public static @NonNull String getFilenameFromPathString(@Nullable String filePath) {
sure thing!

2020-10-06 13:44 UTC, tobiasKaminsky submitted a review, later dismissed

2020-10-06 13:45 UTC, tobiasKaminsky commented on src/main/java/com/owncloud/android/utils/SyncedFolderUtils.java
> +public final class SyncedFolderUtils {
Can we have also tests for this class? 💙💙💙

2020-10-07 12:27 UTC, AndyScherzinger commented on src/main/java/com/owncloud/android/utils/SyncedFolderUtils.java
> +public final class SyncedFolderUtils {
DONE 👍

2020-10-14 18:05 UTC, AndyScherzinger commented
@tobiasKaminsky I successfully tested folder detection filtering and auto upload list view filtering 👍

2020-10-15 07:36 UTC, tobiasKaminsky commented on src/androidTest/java/com/owncloud/android/utils/SyncedFolderUtilsTest.kt
> +        THUMBDATA_FILE
What is this?

2020-10-15 07:39 UTC, tobiasKaminsky commented on src/main/java/com/owncloud/android/utils/FileUtil.java
> +        if (filePath != null && filePath.length() > EMPTY_LENGTH) {
You can use TextUtils.isEmpty(), which checks for null and empty
(it requires then tests to be run in androidTest )

2020-10-15 08:11 UTC, AndyScherzinger commented on src/androidTest/java/com/owncloud/android/utils/SyncedFolderUtilsTest.kt
> +        THUMBDATA_FILE
Whoops, will be removed with next commit 👍

2020-10-15 08:17 UTC, AndyScherzinger commented on src/main/java/com/owncloud/android/utils/FileUtil.java
> +        if (filePath != null && filePath.length() > EMPTY_LENGTH) {
Changed it, the tests already run in androidTest 👍

2020-10-15 12:39 UTC, tobiasKaminsky approved these changes

2020-10-15 13:26 UTC, merged