Closed the screen when press back button from App passcode screen
nextcloud/android pull request #7372
Opened 2020-11-19 10:25 UTC by Kuuuna98

Signed-off-by: Kuuuna98 <yunaghgh@naver.com>

### Testing 

1. Set APP passcode
2. Press the back button on the passcode screen that you see when you run the app.

Result: Leave the app.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [ ] Tests written, or not not needed

https://github.com/nextcloud/android/issues/7343 Issue implemented in code. Please check.😊

2020-11-20 09:17 UTC, tobiasKaminsky commented on src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.java
> +                finishAndRemoveTask();
This is only available in API >= 21, but not on 19, which we still support.
If there is no fitting function that also works on 19, I suggest to have a version check, so that on <21 it simply does not work, but works with >=21.

2020-11-20 15:57 UTC, Kuuuna98 commented
I didn't think about it! 
@tobiasKaminsky , thank you for testing and letting me know. :)
It has been modified from finishAndRemoveTask() to finish() in consideration of API  < 21.

2020-11-20 19:56 UTC, AndyScherzinger commented on src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.java
> +                finishAndRemoveTask();
@Kuuuna98 could you rather put in a version check and support 21+ and <21 because according to our Android version support guideline we will drop 4.4 with the next feature release. So since you are targeting master this way would could then easily find this part in the code.

cc @tobiasKaminsky, I already out this in the 3.15. Overview issue.

2020-11-23 10:13 UTC, tobiasKaminsky requested changes

2020-11-23 10:13 UTC, tobiasKaminsky commented on src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.java
> +                finish();
Have you tried this?
I think this will just close the PassCodeActivity, but not the app and thus lets the user allow to go into the app without entering correct pin code.

2020-11-23 10:31 UTC, Kuuuna98 commented on src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.java
> +                finish();
I thought so, but it wasn't the result.
As a result, the app closed well.
Can you see the main screen as a result from other versions of Android?
If so, I will modify it to check the version in the first code.

Below is a test video.
https://drive.google.com/file/d/1e7D9w7HeiOg74xRNwr2AzndOLJAfEVR8/view?usp=sharing

Android version: 5
Device model: Samsung Galaxy S9

2020-11-23 17:38 UTC, AndyScherzinger commented on src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.java
> +                finish();
@Kuuuna98 you can/should also try the "wack-up" scenario:

* open the app
* put in PIN
* navigate a bit through the app 
* switch to another app
* bring the app back to the front (not having killed the app in between!)

This way you do have a filled "back-stack" within the app and not just a single activity, so `finish()` should just kill the last one and with this change you should have access to the app (which is what @tobiasKaminsky suggested will happen with this change).

Other than that, again: It is fine to implement this for API >= 21 only which will be the minimum Android version anyways for the next release.

2020-11-24 04:24 UTC, Kuuuna98 commented
Thank you for your opinion, @tobiasKaminsky @AndyScherzinger 
I modified the code to check the API version in the first code.

2020-11-24 08:39 UTC, tobiasKaminsky commented on src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.java
> +            if(ACTION_CHECK.equals(getIntent().getAction()) && Build.VERSION.SDK_INT>=21){
Please change this to proper name (Lollipop).

2020-11-24 08:39 UTC, tobiasKaminsky commented
One last thing, other than that I tested it and is is :+1:

2020-11-24 14:51 UTC, tobiasKaminsky approved these changes

2020-11-24 16:12 UTC, AndyScherzinger approved these changes

2020-11-25 10:44 UTC, merged