Sharing dialog improvement
nextcloud/android pull request #8598
Opened 2021-06-18 09:32 UTC by TSImc

Improvement of sharing dialog for Android client

### Overview
1. Improve sharing process for Internal and External Share
2. Popup sharing option menu changed to bottom sheet actions
3. New screen for changing permissions and sending note
4. Added a new button for fast viewing and updating the permissions

### Screenshots

#### Screen 1
<img src="https://user-images.githubusercontent.com/85738307/122533982-63fe2e80-d022-11eb-82d2-1e8bc289164d.png" width="200">

#### Screen 2
<img src="https://user-images.githubusercontent.com/85738307/122534002-682a4c00-d022-11eb-8545-a9af6da71910.png" width="200">

#### Screen 3
<img src="https://user-images.githubusercontent.com/85738307/122534018-6b253c80-d022-11eb-99b6-e9b520da97bb.png" width="200">

#### Screen 4
<img src="https://user-images.githubusercontent.com/85738307/122534035-6e202d00-d022-11eb-81c6-123c9821df71.png" width="200">

#### Screen 5
<img src="https://user-images.githubusercontent.com/85738307/122534044-71b3b400-d022-11eb-8450-32f46ac9abda.png" width="200">

### Testing 
In addition to the existing sharing dialog tests we created new testcases for the enhancement.

2021-06-23 12:34 UTC, tobiasKaminsky commented
Hi,

thanks for your awesome contribution!

Tests are not working due to 
https://github.com/nextcloud/android/pull/8565/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R12

which I wanted to add, but apparently I do not have write permission to your branch.

Please see all other comments inline :)

2021-06-23 12:53 UTC, tobiasKaminsky requested changes

2021-06-23 12:53 UTC, tobiasKaminsky commented on src/androidTest/java/com/owncloud/android/ui/fragment/FileDetailSharingFragmentUpdatedIT.kt
> +/*
Is this a new file? Additional? 
What is the reason to have it separated and not putting the tests in existing FileDtailSharingFragmentIT?

2021-06-23 12:53 UTC, tobiasKaminsky commented on src/androidTest/java/com/owncloud/android/ui/fragment/FileDetailSharingFragmentUpdatedIT.kt
> + * @author Tobias Kaminsky
If it as a new file by you, please update copyright/author section.
This is true for all changed/new created files.

2021-06-23 12:53 UTC, tobiasKaminsky commented on src/main/java/com/owncloud/android/operations/CreateShareWithShareeOperation.java
> +    public void setLabel(String label) {
What is the reason to have this separate from the new constructor?

2021-06-23 12:53 UTC, tobiasKaminsky commented on src/main/java/com/owncloud/android/operations/UpdateShareInfoOperation.java
> +public class UpdateShareInfoOperation extends SyncOperation {
This seems to be a copy and extension of UpdateSharePermissionsOperation.
What is the purpose of having this two times?

2021-06-23 12:53 UTC, tobiasKaminsky commented on src/main/java/com/owncloud/android/ui/activity/FileActivity.java
> +    /**
while those are valid code syntax changes it is best to separate those from a PR which changes/adds new features.
Otherwise it is hard to review as reviewer do not directly see changing /relevante code.

2021-06-23 12:53 UTC, tobiasKaminsky commented on src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
> +        popup.show();*/
If this is not needed, please remove.

2021-06-23 12:53 UTC, tobiasKaminsky commented on src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
> +        popup.show();*/
Same here :)

2021-06-23 12:53 UTC, tobiasKaminsky commented on src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
> +          /*  case R.id.allow_editing:
Also here, please remove all commented code.

2021-06-23 12:53 UTC, tobiasKaminsky commented on src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingMenuBottomSheetDialog.java
> + * Copyright (C) 2018 Andy Scherzinger
Update copyright

2021-06-23 12:53 UTC, tobiasKaminsky commented on src/main/java/com/owncloud/android/ui/fragment/FileDetailsSharingProcessFragment.kt
> +    private fun showExpirationDateDialog() {
This is a copy of ExpirationDatePickerDialogFragment.
Can't this be re-used?

2021-06-23 12:53 UTC, tobiasKaminsky commented on src/main/res/drawable/ic_baseline_arrow_drop_down_24.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Copyright/license header?

2021-06-28 07:23 UTC, TSImc commented on src/androidTest/java/com/owncloud/android/ui/fragment/FileDetailSharingFragmentUpdatedIT.kt
> +/*
We will update testcases in exiting file and keep header section as it is.

2021-06-28 07:24 UTC, TSImc commented on src/androidTest/java/com/owncloud/android/ui/fragment/FileDetailSharingFragmentUpdatedIT.kt
> + * @author Tobias Kaminsky
We will update this in PR and check in created files.

2021-06-28 07:24 UTC, TSImc commented on src/main/java/com/owncloud/android/operations/CreateShareWithShareeOperation.java
> +    public void setLabel(String label) {
Because that variable will only used for Link Share not for Internal and External share. That's why I kept is separate from new constructor. If I will keep this variable in new constructor then developer has to pass this variable unnecessary for other shares.

2021-06-28 07:25 UTC, TSImc commented on src/main/java/com/owncloud/android/operations/UpdateShareInfoOperation.java
> +public class UpdateShareInfoOperation extends SyncOperation {
No, this is not the copy of UpdateSharePermissionsOperation because UpdateSharePermissionsOperation responsible for updating permissions, password and expirydate for share. The new class I created is responsible to update permissions, password, expiry date, note, label and hideFileDownload as well. (Means if user want to update all information at once he can use this class to do it.)

2021-06-28 07:26 UTC, TSImc commented on src/main/java/com/owncloud/android/ui/activity/FileActivity.java
> +    /**
This is a code formatting issue. We will remove the code formatting and update PR

2021-06-28 07:26 UTC, TSImc commented on src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
> +        popup.show();*/
This is for code which is commented. We left it as it is because this was old implementation. We will remove the comments and will update in PR.

2021-06-28 07:27 UTC, TSImc commented on src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingMenuBottomSheetDialog.java
> + * Copyright (C) 2018 Andy Scherzinger
We’ll update the copyright for new files

2021-06-28 07:29 UTC, TSImc commented on src/main/java/com/owncloud/android/ui/fragment/FileDetailsSharingProcessFragment.kt
> +    private fun showExpirationDateDialog() {
ExpirationDatePickerDialogFragment is used for existing functionality and it needs lot of changes to make it use of it for our new changes. That's the reason we created new DatePicker to do so.
But we will change it and will update it in PR.

2021-07-02 06:21 UTC, tobiasKaminsky commented on src/main/java/com/owncloud/android/datamodel/QuickPermissionModel.kt
> +package com.owncloud.android.datamodel
License header

2021-07-02 06:28 UTC, tobiasKaminsky commented
@TSImc nice, we are close to merge it :-)
If you need help rebasing it, please ping me :)

2021-07-12 07:40 UTC, TSImc commented
Hi @tobiasKaminsky. We updated the license info. Please let us know if you got open points.

2021-08-04 21:02 UTC, AndyScherzinger commented
@TSImc there are some conflicts, could you rebase your branch/pr against latest `nextcloud:master` - I think from reading @tobiasKaminsky's comment we would be good to go after the rebase 👍

2021-08-11 10:08 UTC, tobiasKaminsky commented
I rebased it and will merge after green CI: https://github.com/nextcloud/android/pull/8848

2021-09-08 06:35 UTC, closed without merging