Compute localId from remote id with unique server id
nextcloud/android pull request #8643
Opened 2021-06-30 06:19 UTC by tobiasKaminsky

@juliushaertl 
we need to 
- do not use localID (which might make sense in terms of federation)
- or expose unique server id via capabilities

E.g. my instance has 14 chars for unique id @juliushaertl 
To handle this properly we need uniqe id exposed via registered capability, if this is ok for you.

2021-06-30 06:19 UTC, tobiasKaminsky commented on src/main/java/com/owncloud/android/datamodel/OCFile.java
> +        return getRemoteId().substring(0, getRemoteId().length() - 12).replaceAll("^0*", "");
We cannot rely on 12 long instance id!

2021-06-30 08:19 UTC, juliushaertl commented
> EDIT: using localId via webdav is the solution!

yep sounds like the better approach :+1:

2022-12-02 11:05 UTC, tobiasKaminsky commented on app/src/main/java/com/nextcloud/client/database/NextcloudDatabase.kt
> +        AutoMigration(from = 65, to = 67)
@AlvaroBrey is this needed?
I also changed it in https://github.com/nextcloud/android/pull/8643/files#diff-ffa8f9b74f7af219ebf0927bb94e6c8d03e2b34eb9e39b1287edb1b65532a72fR38

2022-12-02 11:05 UTC, tobiasKaminsky commented on app/src/main/java/com/nextcloud/client/database/NextcloudDatabase.kt
> +        AutoMigration(from = 65, to = 67)
If needed, can we combine this? Otherwise I fear we will forget it at some point.

2022-12-02 12:11 UTC, AlvaroBrey requested changes

2022-12-02 12:11 UTC, AlvaroBrey commented on app/schemas/com.nextcloud.client.database.NextcloudDatabase/66.json
>      "formatVersion": 1,
Please undo changes to this file. We must _never_ change already existing schemas when changing database, that's why the new one is created. Otherwise migrations will break.

2022-12-02 12:11 UTC, AlvaroBrey commented on app/src/main/java/com/nextcloud/client/database/NextcloudDatabase.kt
> +        AutoMigration(from = 65, to = 67)
```suggestion
        AutoMigration(from = 65, to = 66),
        AutoMigration(from = 66, to = 67),
```

See https://developer.android.com/training/data-storage/room/migrating-db-versions#automated. Your original change would not allow migration from 66 to 67, only from 65.

> If needed, can we combine this? Otherwise I fear we will forget it at some point.

No, we can't combine this. The migration specs need to reference static DB versions as they must be immutable in time, not a constant that will be changed later.

2022-12-02 12:11 UTC, AlvaroBrey commented on app/schemas/com.nextcloud.client.database.NextcloudDatabase/66.json
>      "formatVersion": 1,
To prevent this happening, you should bump the DB version _before_ making changes to the entities.

2022-12-02 12:11 UTC, AlvaroBrey commented on app/src/androidTest/java/com/owncloud/android/datamodel/FileDataStorageManagerIT.java
> +    }
Empty test?

2022-12-02 12:11 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/datamodel/OCFile.java
> +    }
This feels out of place, the `OCFile` shouldn't have image-specific things in my opinion. I'd just use `getRemoteId` where it is needed.

2022-12-02 13:05 UTC, tobiasKaminsky commented on app/schemas/com.nextcloud.client.database.NextcloudDatabase/66.json
>      "formatVersion": 1,
I never intentionally changed there something.
Must be done by Room…

I only changed FileEntity.

2022-12-02 13:06 UTC, tobiasKaminsky commented on app/schemas/com.nextcloud.client.database.NextcloudDatabase/66.json
>      "formatVersion": 1,
> To prevent this happening, you should bump the DB version before making changes to the entities.

That might be the keypoint! I changed Entity, started app, Room complained and then I adjusted DB version.

2022-12-02 13:13 UTC, tobiasKaminsky commented on app/src/main/java/com/owncloud/android/datamodel/OCFile.java
> +    }
This is such an old PR, that I even do not know why I did this back then.
And you are right, this feels totally off!

2022-12-02 13:14 UTC, AlvaroBrey commented on app/schemas/com.nextcloud.client.database.NextcloudDatabase/66.json
>      "formatVersion": 1,
Yep, the schemes get autogenerated by Room when building. In any case, just undo the changes in 66.json and it will be good to go.

2022-12-02 13:40 UTC, tobiasKaminsky commented on app/src/main/java/com/owncloud/android/datamodel/OCFile.java
> +    }
I know remember.
We have TrashbinFile, FileVersion and OCFile, all extending form ServerFileInterface.
imageKey was then used to abstract from actual detail on ThumbnailCacheManager.

But I reverted it.

2022-12-02 16:35 UTC, AlvaroBrey approved these changes

2022-12-06 07:16 UTC, tobiasKaminsky commented
/rebase

2022-12-06 12:23 UTC, tigermick commented
hi,
I have a problem here : https://github.com/nextcloud/android/issues/10261
and your Nextcloud QA release here : https://www.kaminsky.me/nc-dev/android-artifacts/8643.apk fix my problem

2022-12-13 16:32 UTC, AlvaroBrey commented
@tobiasKaminsky is this available in all supported server versions?

Btw the new attribute in the DB will likely conflict with #11098 , so I'd rather merge that one first and solve conflicts here. Otherwise we risk losing the new attribute.

2022-12-13 16:32 UTC, AlvaroBrey commented
/rebase

2022-12-14 16:54 UTC, AlvaroBrey commented
@tobiasKaminsky can you see what's happening with the failing test?

2022-12-15 14:22 UTC, tobiasKaminsky commented
> @tobiasKaminsky is this available in all supported server versions?

Yes, I tested it with NC16, our oldest supported version, and it returns:
```
<oc:id>00000002oc8wojm72e0q</oc:id>
<oc:fileid>2</oc:fileid>
```

2022-12-15 14:25 UTC, tobiasKaminsky commented
> @tobiasKaminsky can you see what's happening with the failing test?

Strange, I do not understand why it fails with this change.
It should have been failing either all the time, or not at all.

I will continue to check.

2022-12-19 15:13 UTC, AlvaroBrey commented
/rebase

2022-12-20 11:53 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/datamodel/OCFile.java
> +            return Long.parseLong(remoteId.substring(0, 8).replaceAll("^0*", ""));
Are there servers with a remoteID shorter than 8 characters? If so we should do `substring(0, Math.min(remoteId.length(), 8)` instead of `substring(0.8)`.

2022-12-20 13:28 UTC, tobiasKaminsky commented on app/src/main/java/com/owncloud/android/datamodel/OCFile.java
> +            return Long.parseLong(remoteId.substring(0, 8).replaceAll("^0*", ""));
I think 8 is minimum, but there might be some with more than 8.
But as this is the old behaviour, it should not break any existing installation.

2022-12-20 13:30 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/datamodel/OCFile.java
> +            return Long.parseLong(remoteId.substring(0, 8).replaceAll("^0*", ""));
Then I don't understand why some tests failed in this pr due to a too short remoteId, but didn't fail before :\

2022-12-20 14:31 UTC, AlvaroBrey approved these changes

2022-12-21 07:34 UTC, tobiasKaminsky commented on app/src/main/java/com/owncloud/android/datamodel/OCFile.java
> +            return Long.parseLong(remoteId.substring(0, 8).replaceAll("^0*", ""));
Me neither. Which one is failing? Then I can try to debug it locally.

2022-12-21 07:44 UTC, tobiasKaminsky commented on app/src/main/java/com/owncloud/android/datamodel/OCFile.java
> +            return Long.parseLong(remoteId.substring(0, 8).replaceAll("^0*", ""));
https://github.com/nextcloud/android/pull/8643/commits/e1d564026f7c479b61d4404083126fbee71fbbdb#diff-940d35bacfe8905a4b0b8019f3b78e40fcb366e8b3f313dc350ecbdf671f8385R249

Here it is because of:
It tries to save file in FileDataStorageManager:460
-> and saves localId, which is then as fallback tries to substring(0,8).
In this case (on master) we just used remoteId, as is. And thus it never failed.

2023-01-09 16:36 UTC, AlvaroBrey commented
/rebase

2023-01-11 14:11 UTC, AlvaroBrey commented
```
/drone/src/app/src/androidTest/java/com/nextcloud/client/EndToEndRandomIT.java:656: error: cannot find symbol
--
712 | assertTrue(new DeletePrivateKeyOperation().execute(client).isSuccess());

```

2023-01-19 08:22 UTC, tobiasKaminsky commented
Library merged, so let us merge this asap.

2023-01-19 10:19 UTC, merged