Migrate ThumbnailCacheManager to User model
nextcloud/android pull request #8656
Opened 2021-07-04 15:48 UTC by ezaquarii

Signed-off-by: Chris Narkiewicz <hello@ezaquarii.com>

2021-07-05 07:30 UTC, AndyScherzinger approved these changes

2021-08-06 08:27 UTC, tobiasKaminsky commented on src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
> +        private User mAccount;
```suggestion
        private User user;
```

Then type and name matches :)

2021-08-06 08:28 UTC, tobiasKaminsky requested changes
Variable rename

2021-08-07 23:06 UTC, ezaquarii commented on src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
> +        private User mAccount;
@tobiasKaminsky done

2021-08-11 09:45 UTC, tobiasKaminsky approved these changes

2021-08-17 14:06 UTC, AndyScherzinger commented
/rebase

2021-09-04 10:48 UTC, AndyScherzinger approved these changes

2021-09-05 16:51 UTC, AndyScherzinger commented
/rebase

2021-09-07 15:50 UTC, AndyScherzinger commented
/rebase

2021-09-08 10:38 UTC, AndyScherzinger commented
/rebase

2021-09-09 11:58 UTC, merged