add custom PatchMethod class to use http PATCH requests with the Nextcloud SSO api
nextcloud/android pull request #8818
Opened 2021-08-06 00:31 UTC by binsky08

should solve https://github.com/nextcloud/Android-SingleSignOn/issues/355

Seems like the used org.apache.commons.httpclient is end of life: https://hc.apache.org/httpclient-legacy/
Therefore I created a PatchMethod class based on the official PostMethod class. It works. :)

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [ ] Tests written, or not not needed

2021-08-06 05:30 UTC, tobiasKaminsky commented on src/main/java/com/nextcloud/android/sso/PatchMethod.java
> +package com.nextcloud.android.sso;
Please add license header.
If this is a copy from PostMethod please also note this somewhere.

2021-08-06 05:30 UTC, tobiasKaminsky commented on src/main/java/com/nextcloud/android/sso/PatchMethod.java
> +    // -------------------------------------------------------------- Constants
As we do not use such kind of comments, please remove them.

2021-08-06 05:30 UTC, tobiasKaminsky commented on src/main/java/com/nextcloud/android/sso/PatchMethod.java
> +    private static final Log LOG = LogFactory.getLog(PatchMethod.class);
We use another log approach.

2021-08-06 05:31 UTC, tobiasKaminsky commented on src/main/java/com/nextcloud/android/sso/PatchMethod.java
> +        LOG.trace("enter PatchMethod.hasRequestContent()");
Please remove those logs, as we do not need them.

2021-08-06 05:31 UTC, tobiasKaminsky commented on src/main/java/com/nextcloud/android/sso/PatchMethod.java
> +     * @since 2.0beta1
This is from c&p I assume, so please remove.

2021-08-06 05:32 UTC, tobiasKaminsky requested changes
Adopt to our code syntax

2021-08-06 09:41 UTC, binsky08 commented on src/main/java/com/nextcloud/android/sso/PatchMethod.java
> +package com.nextcloud.android.sso;
I haven't had to do a lot with licenses yet. Do you think that's okay?

```
/*
 * Nextcloud SingleSignOn
 *
 * @author Timo Triebensky
 * Copyright (C) 2021 Timo Triebensky
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * More information here: https://github.com/abeluck/android-streams-ipc
 *
 * ====================================================================
 *
 * The required methods of this class are copied and customized from PostMethod.
 */
```

2021-08-07 13:43 UTC, binsky08 commented on src/main/java/com/nextcloud/android/sso/PatchMethod.java
> +     * @since 2.0beta1
removed it

2021-08-07 13:44 UTC, binsky08 commented on src/main/java/com/nextcloud/android/sso/PatchMethod.java
> +        LOG.trace("enter PatchMethod.hasRequestContent()");
removed it

2021-08-07 13:45 UTC, binsky08 commented on src/main/java/com/nextcloud/android/sso/PatchMethod.java
> +    private static final Log LOG = LogFactory.getLog(PatchMethod.class);
ah yes, Log_OC. I removed the log method that i took over from the parent class

2021-08-07 13:46 UTC, binsky08 commented on src/main/java/com/nextcloud/android/sso/PatchMethod.java
> +    // -------------------------------------------------------------- Constants
removed it

2021-08-12 06:22 UTC, tobiasKaminsky commented
Cool, thanks for your code changes.
One last thing: as spotbugs increased, but it complains "only" about complexity, can you adjust number in findbugs-results.txt to 464?

2021-08-12 06:22 UTC, tobiasKaminsky approved these changes

2021-08-30 09:37 UTC, binsky08 commented
do i have to do anything else?

2021-09-01 07:18 UTC, stefan-niedermann approved these changes

2021-09-27 10:09 UTC, merged