[DO NOT MERGE] Revert "Bump hwsecurity-fido from 4.1.0 to 4.4.0"
nextcloud/android pull request #8933
Opened 2021-09-02 14:17 UTC by AlvaroBrey

This reverts commit 0d7d40e1d3afae4bf1822a265667f85b2e182137.

This is a test.

2021-09-02 16:23 UTC, Valdnet approved these changes

2021-09-03 07:14 UTC, AlvaroBrey commented
/backport to stable-3.17

2021-09-03 08:19 UTC, tobiasKaminsky requested changes

2021-09-03 08:19 UTC, tobiasKaminsky commented on build.gradle
> -    fidoVersion = "4.4.0"
Having this version pattern is quite good to make sure that the libs are on the same version.
Otherwise we would get two different version bumps by depend a bot, and if both libs are relying on each other, they might then fail.
So better just switch it here :)

2021-09-03 08:44 UTC, AlvaroBrey commented on build.gradle
> -    fidoVersion = "4.4.0"
Sure, I just reverted the original commit. Will change it back to the previous pattern and just bump down the number.

2021-09-06 08:56 UTC, tobiasKaminsky approved these changes

2021-09-06 08:56 UTC, merged