Fix swipe up glitch
nextcloud/android pull request #9470
Opened 2021-12-06 17:02 UTC by tobiasKaminsky

Fix https://github.com/nextcloud/android/issues/9403

- allow swipe up on second folder hierarchy
- disallow swipe up on empty folder

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

- [ ] Tests written, or not not needed

2021-12-06 17:02 UTC, tobiasKaminsky commented
/backport to stable-3.18

2021-12-09 11:19 UTC, AlvaroBrey requested changes
Can still reproduce the issue:

1. Create a folder (let's call it folder A)
2. Create another empty folder (B) within folder A
3. Navigate to folder B
4. Swipe up on the title bar, over the folder name

This hides the titlebar and there's no way to bring it back.

2021-12-13 13:21 UTC, tobiasKaminsky commented
This also happens if you have an empty cloud and scroll up on search widget… :/

2021-12-16 12:20 UTC, AbdulrhmanSayedAli approved these changes

2022-03-22 17:56 UTC, AlvaroBrey commented
Superseded by #10009

2022-03-22 17:56 UTC, closed without merging