Change naming in conflicts to location instead of date
nextcloud/android pull request #9534
Opened 2021-12-11 20:39 UTC by gabmert

- [x] Tests not not needed

Hi, I had following experience and wanted to make it better: I downloaded/synchronized a file to my android phone. I edited the file on my mobile via an offline editor (markor). Later I made some changes to the file in the cloud. When I tried to sync the files from the android app, the conflicts dialog popped up with `New File` and `Already existing file`. I was stuck as I had no clue which file was which: I didn't create a new file and my changes to the local file were made before the changes to the cloud file. That's why I propose to describe these files with `Local file` and `File in cloud`. 

Other options I can think of are:
* `New file (local)`
* `Cloud file`
* `File already in cloud`
* `Already existing file (cloud)`

I am a total newbie to contributing to FLOSS and appreciate any hints about how to fit in your processes.

2021-12-14 13:44 UTC, gabmert commented
@AlvaroBrey Thank you for your comments. I hope the changes I made are correct. I was unsure in which way I should take care of the git history and was thinking of maybe opening a different branch and pull request to have only one commit? I'm happy to hear about the proper way

2021-12-15 14:53 UTC, AlvaroBrey requested changes
Awesome! Can you please remove the two now-unused strings too, so lint doesn't complain? Thank you!

2021-12-15 14:53 UTC, AlvaroBrey commented on src/main/res/values/strings.xml
>      <string name="conflict_already_existing_file">Already existing file</string>
Please remove these!

2021-12-16 08:35 UTC, merged

2021-12-16 08:35 UTC, AlvaroBrey commented
Thank you!

2021-12-16 22:41 UTC, gabmert commented
Thank you for your guidance and patience @AlvaroBrey