sandeepBranch
nextcloud/android pull request #9622
Opened 2021-12-27 08:19 UTC by sandeep021

issue #9170 fixed the visibilty of slide in dark theme
Steps to check:
1. Select "Settings" of the application
2. Select "Contacts and Calendar backup"

2022-01-03 17:22 UTC, AlvaroBrey requested changes
Thanks for your contribution @sandeep021! There are some things that need attention, please check the comments below.

2022-01-03 17:22 UTC, AlvaroBrey commented on src/main/res/layout/backup_fragment.xml
> +            app:theme="@style/Color1SwitchStyle"
The changes in this file and the other XML seem to be unneeded. Is that right? If so, remove them.

2022-01-03 19:07 UTC, sandeep021 commented on src/main/res/layout/backup_fragment.xml
> +            app:theme="@style/Color1SwitchStyle"
I have made all the suggested changes Thank you for the review and suggestions

2022-01-04 10:17 UTC, AlvaroBrey commented on src/main/java/com/owncloud/android/ui/fragment/contactsbackup/BackupFragment.java
> +            binding.contacts, getContext().getResources().getColor(R.color.color_accent));
Is this change needed?

2022-01-04 17:59 UTC, sandeep021 commented on src/main/java/com/owncloud/android/ui/fragment/contactsbackup/BackupFragment.java
> +            binding.contacts, getContext().getResources().getColor(R.color.color_accent));
actually no both are doing same thing

2022-01-10 16:19 UTC, AlvaroBrey commented on src/main/java/com/owncloud/android/utils/theme/ThemeCheckableUtils.java
>      public static void tintSwitch(SwitchCompat switchView, int color) {
the `color` param is now unused, so you can remove it to fix the Spotbugs increase.

Additionally please follow https://github.com/nextcloud/android/pull/9622/checks?check_run_id=4705568539 to sign off your commits, and then we can merge  this after both things are done.

2022-01-10 18:03 UTC, sandeep021 commented on src/main/java/com/owncloud/android/utils/theme/ThemeCheckableUtils.java
>      public static void tintSwitch(SwitchCompat switchView, int color) {
- removed the color param
-i am not sure i have followed the second suggestion or not i am unable to push using terminal getting 403, if not done properly please let me know i will try again

2022-01-11 09:13 UTC, AlvaroBrey approved these changes

2022-01-11 09:13 UTC, merged

2022-01-11 09:14 UTC, AlvaroBrey commented
Thanks @sandeep021!