Prevent upload from sensitive path
nextcloud/android pull request #9645
Opened 2022-01-04 13:48 UTC by tobiasKaminsky

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

- [ ] Tests written, or not not needed

2022-01-04 14:16 UTC, AlvaroBrey approved these changes

2022-01-07 09:27 UTC, AlvaroBrey commented
/rebase

2022-01-07 12:27 UTC, AlvaroBrey commented
/rebase

2022-01-10 14:22 UTC, AlvaroBrey commented
/rebase

2022-01-10 16:09 UTC, AlvaroBrey requested changes
```
com.owncloud.android.files.services.FileUploaderIT > testKeepCancelStatic[android(AVD) - 8.1.0] [31mFAILED [0m
	junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:48)

com.owncloud.android.files.services.FileUploaderIT > testKeepBothStatic[android(AVD) - 8.1.0] [31mFAILED [0m
	junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:48)

com.owncloud.android.files.services.FileUploaderIT > testKeepLocalAndOverwriteRemoteStatic[android(AVD) - 8.1.0] [31mFAILED [0m
	junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:48)

com.owncloud.android.files.services.FileUploaderIT > testKeepServerStatic[android(AVD) - 8.1.0] [31mFAILED [0m
	junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:48)
```

2022-01-11 20:03 UTC, AlvaroBrey requested changes
Lots of tests still failing as they upload from temporal path. Perhaps we should add an exception for the temporal paths?

2022-01-12 07:42 UTC, tobiasKaminsky commented
> Perhaps we should add an exception for the temporal paths?

Indeed we need to do this, as we use temporary path when uploading a file from sdcard:

https://github.com/nextcloud/android/blob/883857db32bcda4721e47b14f75f16c4611fa29d/src/main/java/com/owncloud/android/operations/UploadFileOperation.java#L549

Let me change it 👍

2022-01-14 12:17 UTC, AlvaroBrey commented
Tests still failing :\ This might be harder than expected

2022-02-09 09:33 UTC, tobiasKaminsky commented
/rebase

2022-03-23 11:58 UTC, AlvaroBrey requested changes
Quick smoketest: downloads are not working

```
2022-03-23 12:56:44.854 12951-13004/com.nextcloud.client I/DownloadFileRemoteOperation: Download of /100_MB.pdf to /data/user/0/com.nextcloud.client/files/nextcloud/tmp/MY_SERVER/100_MB.pdf: Operation finished with HTTP status code 200 (success)
2022-03-23 12:56:44.861 12951-13004/com.nextcloud.client I/DownloadFileOperation: Download of /100_MB.pdf to /storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/MY_SERVER/100_MB.pdf: Error while moving file to final directory
```

2022-05-09 07:35 UTC, tobiasKaminsky commented
/rebase

2022-05-09 14:22 UTC, AlvaroBrey commented on app/src/androidTest/java/com/owncloud/android/files/services/FileUploaderIT.kt
> +    fun testCheckPath() {
nice!

2022-05-09 14:29 UTC, AlvaroBrey commented on app/src/androidTest/java/com/owncloud/android/utils/SyncedFolderUtilsTest.kt
> +                        InstrumentationRegistry.getInstrumentation().targetContext
Can just use `targetContext`, since this extends `AbstractIT`. Same thing further down in this file.

2022-05-09 14:31 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/files/services/FileUploader.java
> +     * if file is within sensitive path, return false
This comment says the opposite of what the method does.  I would just remove the comment, the method name is descriptive enough.

2022-05-09 14:35 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/operations/DownloadFileOperation.java
> +                Log.e(TAG, "Error moving file", e);
Use `Log_OC` instead

2022-05-09 14:37 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/operations/DownloadFileOperation.java
> +        return FileStorageUtils.getInternalTemporalPath(user.getAccountName(), context) + file.getRemotePath();
```suggestion
        return getTmpFolder() + file.getRemotePath();
```
Also most of these methods look like they can be private

2022-08-08 08:34 UTC, AlvaroBrey commented
Superseded by #10544

2022-08-08 08:34 UTC, closed without merging