Fix sharing from media view
nextcloud/android pull request #9959
Opened 2022-03-11 06:40 UTC by tobiasKaminsky

- open media view
- select an image
- select send/share
- share to an user

This now works, but it is too small, and I have no clue where this size is set:
![image](https://user-images.githubusercontent.com/5836855/157815839-0c0f02da-469e-4e7c-9a6b-29505b459fca.png)
@AlvaroBrey do you have an idea?

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

- [ ] Tests written, or not not needed

2022-03-11 09:39 UTC, AlvaroBrey commented
>  @AlvaroBrey do you have an idea?

Layout for the details sharing fragment is http://github.com/nextcloud/android/blob/5da6fd235f037e52cd5537e87b901e7135514281/src/main/res/layout/file_details_sharing_process_fragment.xml#L28-L28, but I don't think it's prepared for showing in a dialog.

2022-03-11 10:42 UTC, tobiasKaminsky commented
> but I don't think it's prepared for showing in a dialog.

What do you mean by this? I know that dialogs are not fullscreen, but in above screenshot it is so tiny, that there is still half of height possible, but not shown…

2022-03-11 11:05 UTC, AlvaroBrey commented
> > but I don't think it's prepared for showing in a dialog.
> 
> What do you mean by this? I know that dialogs are not fullscreen, but in above screenshot it is so tiny, that there is still half of height possible, but not shown…

I mean that the layout for that fragment has `    android:layout_height="match_parent"`, and the `ScrollView` inside has `        android:layout_height="0dp"` and is sized by constraints. I don't know how that works inside a `Dialog`, which has variable height per se.

2022-03-22 09:17 UTC, AlvaroBrey requested changes
Nice! I've pushed https://github.com/nextcloud/android/pull/9959/commits/f6298f79044703c0cbd59cb31d63e1c48dab2712 to improve the minHeight approach a bit.

Additionally, please look at the comment below.

2022-03-22 09:17 UTC, AlvaroBrey commented on app/src/main/java/com/owncloud/android/ui/fragment/FileDetailsSharingProcessFragment.kt
> +        binding.shareProcessEditShareLink.visibility = View.GONE
Restoring the visibility is needed in `showShareProcessFirst`. Otherwise the text will remain hidden if the user advances to the note screen and then presses Cancel.

2022-03-23 08:30 UTC, AlvaroBrey approved these changes

2022-03-23 08:30 UTC, merged